#!/usr/bin/env bash
# Formal Ordinary Light GPU gate launcher.
set -euo pipefail

gate_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "$gate_dir/../.." && pwd)"
task_python="${WAVE_RENDER_PYTHON:-$repo_root/.venv/bin/python}"
gate_platform="${WAVE_RENDER_GLFW_PLATFORM:-x11}"
if [[ "$gate_platform" == "wayland" ]]; then
  default_logical_width=3072
  default_logical_height=1728
  default_maximize_after_frame=1
else
  default_logical_width=3840
  default_logical_height=2160
  default_maximize_after_frame=0
fi

cd "$repo_root"
exec env \
  WAVE_RENDER_WIDTH="${WAVE_RENDER_GATE_LOGICAL_WIDTH:-$default_logical_width}" \
  WAVE_RENDER_HEIGHT="${WAVE_RENDER_GATE_LOGICAL_HEIGHT:-$default_logical_height}" \
  WAVE_RENDER_MAXIMIZE_AFTER_FRAME="${WAVE_RENDER_MAXIMIZE_AFTER_FRAME:-$default_maximize_after_frame}" \
  WAVE_RENDER_PERFORMANCE_GATE_TARGET_WIDTH=3840 \
  WAVE_RENDER_PERFORMANCE_GATE_TARGET_HEIGHT=2160 \
  WAVE_RENDER_SCENE="${WAVE_RENDER_SCENE:-area_lights}" \
  WAVE_RENDER_BENCHMARK_FRAMES="${WAVE_RENDER_BENCHMARK_FRAMES:-120}" \
  WAVE_RENDER_BENCHMARK_WARMUP_FRAMES="${WAVE_RENDER_BENCHMARK_WARMUP_FRAMES:-30}" \
  WAVE_RENDER_BENCHMARK_REPORT_INTERVAL="${WAVE_RENDER_BENCHMARK_REPORT_INTERVAL:-120}" \
  WAVE_RENDER_PROFILE="${WAVE_RENDER_PROFILE:-0}" \
  WAVE_RENDER_SWAPCHAIN_IMAGES="${WAVE_RENDER_SWAPCHAIN_IMAGES:-6}" \
  WAVE_RENDER_BENCHMARK_CSV="${WAVE_RENDER_BENCHMARK_CSV:-/tmp/ordinarylight_4k_gate.csv}" \
  WAVE_RENDER_BENCHMARK_SUMMARY="${WAVE_RENDER_BENCHMARK_SUMMARY:-/tmp/ordinarylight_4k_gate.json}" \
  WAVE_RENDER_PERFORMANCE_GATE=1 \
  WAVE_RENDER_PERFORMANCE_GATE_MIN_FPS="${WAVE_RENDER_PERFORMANCE_GATE_MIN_FPS:-50}" \
  WAVE_RENDER_PERFORMANCE_GATE_MIN_PIXEL_RATIO="${WAVE_RENDER_PERFORMANCE_GATE_MIN_PIXEL_RATIO:-0.98}" \
  WAVE_RENDER_SAMPLES="${WAVE_RENDER_SAMPLES:-1}" \
  WAVE_RENDER_MAX_BOUNCES="${WAVE_RENDER_MAX_BOUNCES:-4}" \
  WAVE_RENDER_TILE_CAPACITY="${WAVE_RENDER_TILE_CAPACITY:-2097152}" \
  WAVE_RENDER_UNTEXTURED_SPECIALIZATION="${WAVE_RENDER_UNTEXTURED_SPECIALIZATION:-1}" \
  WAVE_RENDER_RESTIR_DI="${WAVE_RENDER_RESTIR_DI:-1}" \
  WAVE_RENDER_RESTIR_CANDIDATES="${WAVE_RENDER_RESTIR_CANDIDATES:-1}" \
  WAVE_RENDER_RESTIR_HISTORY_LIMIT="${WAVE_RENDER_RESTIR_HISTORY_LIMIT:-6}" \
  WAVE_RENDER_RESTIR_SPATIAL="${WAVE_RENDER_RESTIR_SPATIAL:-1}" \
  WAVE_RENDER_RESTIR_SPATIAL_NEIGHBORS="${WAVE_RENDER_RESTIR_SPATIAL_NEIGHBORS:-4}" \
  WAVE_RENDER_RESTIR_SPATIAL_RADIUS="${WAVE_RENDER_RESTIR_SPATIAL_RADIUS:-4}" \
  WAVE_RENDER_RESTIR_PAIRWISE_MIS="${WAVE_RENDER_RESTIR_PAIRWISE_MIS:-1}" \
  WAVE_RENDER_PRESENT_MODE=immediate \
  WAVE_RENDER_PRESENT_PACING=0 \
  "$task_python" -m tools.wavefront_present
