import importlib.util
from pathlib import Path
import unittest


ROOT = Path(__file__).parents[1]


class OrdinaryShadeColorTests(unittest.TestCase):
    def test_generated_aces_helper_is_shared_by_color_output_stages(self):
        helper = (
            ROOT / "ordinarylight/shaders/ordinaryshade_color.glsl"
        ).read_text()
        self.assertIn("vec3 acesApproximation(vec3 color)", helper)
        self.assertIn("vec3 linearToSrgb(vec3 color)", helper)
        for name in (
            "hdr_to_p010.comp",
            "wavefront_tone_map.comp",
            "wavefront_tone_map_image.comp",
        ):
            composed = (ROOT / "ordinarylight/shaders" / name).read_text()
            self.assertIn("vec3 acesApproximation(vec3 color)", composed)
            self.assertIn("vec3 linearToSrgb(vec3 color)", composed)
        reconstruct = (
            ROOT / "ordinarylight/shaders/wavefront_reconstruct.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", reconstruct)
        self.assertIn("vec3 acesApproximation(vec3 color)", reconstruct)
        self.assertIn("vec3 linearToSrgb(vec3 color)", reconstruct)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_checked_in_color_helpers_match_ordinaryshade_output(self):
        path = ROOT / "scripts/generate_color_shaders.py"
        spec = importlib.util.spec_from_file_location(
            "generate_color_shaders", path,
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        expected = (
            ROOT / "ordinarylight/shaders/ordinaryshade_color.glsl"
        ).read_text()
        self.assertEqual(module.generated_source(), expected)


if __name__ == "__main__":
    unittest.main()
