import importlib.util
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).parents[1]


class OrdinaryShadeCoreShaderTests(unittest.TestCase):
    def test_buffer_ray_query_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/ray_query.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("#extension GL_EXT_ray_query : require", source)
        self.assertIn("uniform accelerationStructureEXT scene_tlas", source)
        self.assertIn("// WAVE_RENDER_MATERIAL_BEGIN", source)
        self.assertIn("MaterialEvaluation evaluateMaterial", source)
        self.assertIn("PrimaryRayResult rayQueryPrimaryRay", source)
        self.assertIn("vec3 rayQueryTracePath", source)
        self.assertIn("rayQueryGetIntersectionInstanceCustomIndexEXT", source)
        self.assertIn("packUnorm4x8", source)

    def test_image_ray_query_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/ray_query_image.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("// WAVE_RENDER_MATERIAL_BEGIN", source)
        self.assertIn("RayQueryTraceResult rayQueryImageTracePath", source)
        self.assertIn("AreaLightSampleResult rayQuerySampleAreaLight", source)
        self.assertIn("rayQuerySamplePointLights", source)
        self.assertIn("imageStore(accumulation_a", source)
        self.assertIn("imageStore(gbuffer_b", source)
        self.assertIn("compatible_neighbors", source)
        self.assertIn("history.rgb = clamp", source)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_wavefront_pbr_helpers_form_a_typed_module(self):
        module = self._generator_module()
        helpers = tuple(
            getattr(module, name) for name in (
                "waveCosineHemisphere", "rayQueryRandomState",
                "rayQueryRandomValue", "rayQueryReflect",
                "shadePbrFresnel", "shadeGgxDistribution",
                "shadeGgxSmithComponent", "shadePbrSpecularProbability",
                "shadeEvaluatePbrLobes", "shadeEvaluatePbr", "shadePbrPdf",
                "shadeSampleGgxHalfVector", "shadeSamplePbr",
                "shadeSetMediumIor", "shadeMediumIor",
                "evaluateMaterial", "shadeApplyMaterialEvaluation",
            )
        )
        source = module.osh.compile(
            module.shade_pbr_probe, helpers=helpers
        ).source
        self.assertIn("vec3 shadeEvaluatePbr", source)
        self.assertIn("PbrSampleResult shadeSamplePbr", source)
        self.assertIn("shadeGgxDistribution", source)
        self.assertIn("ShadeMediumStack shadeSetMediumIor", source)
        self.assertIn("MaterialData shadeApplyMaterialEvaluation", source)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_wavefront_packed_texture_helpers_form_a_typed_module(self):
        module = self._generator_module()
        helpers = tuple(
            getattr(module, name) for name in (
                "shadeSrgbChannel", "shadeWrapTextureCoordinate",
                "shadeWrapTextureIndex", "shadeDecodeTextureTexel",
                "shadeFetchTextureTexel", "shadeTextureMipOffset",
                "shadeSampleTextureLevel", "shadeSampleMaterialTexture",
                "shadeTriangleUvDensity", "shadeMaterialHasTextures",
                "shadeTextureBindingUsesUv1", "shadeMaterialUsesUv1",
                "shadeTriangleTangent", "shadeApplyMaterialTextures",
                "shadeApplyNormalTexture", "shadeResolveSurface",
            )
        )
        source = module.osh.compile(
            module.shade_texture_probe, helpers=helpers
        ).source
        self.assertIn("vec4 shadeSampleTextureLevel", source)
        self.assertIn("vec4 shadeSampleMaterialTexture", source)
        self.assertIn("vec4 shadeTriangleTangent", source)
        self.assertIn("MaterialData shadeApplyMaterialTextures", source)
        self.assertIn("vec3 shadeApplyNormalTexture", source)
        self.assertIn("ShadeSurface shadeResolveSurface", source)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_wavefront_native_texture_sampling_is_typed(self):
        module = self._generator_module()
        source = module.osh.compile(
            module.shade_native_texture_probe,
            helpers=(module.shadeSampleNativeMaterialTexture,),
        ).source
        self.assertIn("uniform sampler2D native_textures[128]", source)
        self.assertIn("textureSize(native_textures[nonuniformEXT", source)
        self.assertIn("textureQueryLevels(native_textures[nonuniformEXT", source)
        self.assertIn("textureLod(native_textures[nonuniformEXT", source)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_wavefront_work_counter_profiling_is_typed(self):
        module = self._generator_module()
        source = module.osh.compile(
            module.shade_profile_probe, helpers=(module.shadeProfileWork,)
        ).source
        self.assertIn("void shadeProfileWork", source)
        self.assertIn("atomicAdd(work_counters[counter], amount)", source)
        self.assertIn("work_counters[(uint(16) + bounce)]", source)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_wavefront_shade_hit_loading_is_typed(self):
        module = self._generator_module()
        source = module.osh.compile(
            module.shade_control_probe,
            helpers=(
                module.shadeLoadHit,
                module.shadeRayCone,
                module.shadeSetRayCone,
                module.shadePathRng,
                module.shadePathBounce,
                module.shadePathPreviousPdf,
                module.shadePowerHeuristic,
                module.shadeResolveEnvironmentMiss,
                module.shadeAdvanceBounceOrTerminate,
                module.shadeMediumIor,
                module.shadeSetMediumIor,
                module.shadeTransmitPath,
                module.rayQueryRandomState,
                module.rayQueryRandomValue,
                module.shadeApplyRussianRoulette,
                module.shadeBuildContinuation,
                module.shadeReserveOutputIndex,
                module.shadeEnqueueContinuation,
                module.shadeSmoothstep,
                module.shadePreparePointLight,
                module.shadePointLightVisible,
                module.shadePbrFresnel,
                module.shadeGgxDistribution,
                module.shadeGgxSmithComponent,
                module.shadeEvaluatePbrLobes,
                module.shadeEvaluatePbr,
                module.shadePointLightContribution,
                module.shadeSelectAreaLight,
                module.shadePrepareAreaLight,
                module.shadeAreaLightVisible,
                module.shadePbrSpecularProbability,
                module.shadePbrPdf,
                module.shadeAreaLightContribution,
                module.shadeUnifiedAreaDomainProbability,
                module.shadeSecondaryNeeHash,
                module.shadeSelectSecondaryNee,
                module.shadeEmissionContribution,
                module.shadeAnalyticEnvironment,
                module.shadeFindEnvironmentLight,
                module.shadeEnvironmentUv,
                module.shadeDecodeEnvironmentRadiance,
                module.shadeAccumulateDirectContribution,
                module.rayQueryReflect,
                module.shadeSampleGgxHalfVector,
                module.shadeSamplePbr,
                module.shadeScatterOpaquePath,
                module.waveCosineHemisphere,
                module.shadePrepareEnvironmentLight,
                module.shadeEnvironmentVisible,
                module.shadeEnvironmentContribution,
                module.shadeSelectUnifiedSecondaryDomain,
                module.shadeEncodeEnvironmentDirection,
                module.shadeDecodeEnvironmentDirection,
            ),
        ).source
        self.assertIn("ShadeHitInput shadeLoadHit", source)
        self.assertIn("rayQueryInitializeEXT", source)
        self.assertIn("rayQueryGetIntersectionInstanceCustomIndexEXT", source)
        self.assertIn("uintBitsToFloat", source)
        self.assertIn("floatBitsToUint", source)
        self.assertIn("ShadeMissResult shadeResolveEnvironmentMiss", source)
        self.assertIn("path.metadata.w & (~uint(1))", source)
        self.assertIn("WavePathState shadeAdvanceBounceOrTerminate", source)
        self.assertIn("ShadeTransmissionResult shadeTransmitPath", source)
        self.assertIn("refract(incoming, normal", source)
        self.assertIn("ShadeRouletteResult shadeApplyRussianRoulette", source)
        self.assertIn("ShadeContinuationResult shadeBuildContinuation", source)
        self.assertIn("floatBitsToUint(cone_width)", source)
        self.assertIn("ShadeEnqueueResult shadeEnqueueContinuation", source)
        self.assertIn("subgroupBallotExclusiveBitCount", source)
        self.assertIn("atomicAdd(output_queue.overflow", source)
        self.assertIn("ShadePointLightSample shadePreparePointLight", source)
        self.assertIn("bool shadePointLightVisible", source)
        self.assertIn("vec3 shadePointLightContribution", source)
        self.assertIn("ShadeAreaLightSample shadePrepareAreaLight", source)
        self.assertIn("bool shadeAreaLightVisible", source)
        self.assertIn("vec3 shadeAreaLightContribution", source)
        self.assertIn("ShadeEmissionResult shadeEmissionContribution", source)
        self.assertIn("shadeUnifiedAreaDomainProbability", source)
        self.assertIn("bool shadeSelectSecondaryNee", source)
        self.assertIn("bitfieldReverse(frame_index)", source)
        self.assertIn("ShadeEnvironmentSample shadePrepareEnvironmentLight", source)
        self.assertIn("vec3 shadeEnvironmentContribution", source)
        self.assertIn("ShadeUnifiedDomainSelection", source)
        self.assertIn("shadeEncodeEnvironmentDirection", source)
        self.assertIn("ShadeEnvironmentDescriptor shadeFindEnvironmentLight", source)
        self.assertIn("vec2 shadeEnvironmentUv", source)
        self.assertIn("atan(direction.z, direction.x)", source)
        self.assertIn("WavePathState shadeAccumulateDirectContribution", source)
        self.assertIn("ShadeOpaqueScatterResult shadeScatterOpaquePath", source)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_complete_wavefront_shade_candidate_compiles(self):
        module = self._generator_module()
        source = module.osh.compile(
            module.wavefront_shade_candidate,
            helpers=module.WAVEFRONT_SHADE_CANDIDATE_HELPERS,
        ).source
        self.assertIn("layout(local_size_x = 64", source)
        self.assertIn("ShadeSurface shadeResolveSurface", source)
        self.assertIn("shadeIntegrateVolumesBeforeSurface", source)
        self.assertIn("shadeEnvironmentRadiance", source)
        self.assertIn("shadeApplyMaterialEvaluation", source)
        self.assertIn("shadeReserveOutputIndex", source)
        compiler = ROOT / ".tools/glslang/usr/bin/glslangValidator"
        if compiler.is_file():
            compiled = module.osh.compile(
                module.wavefront_shade_candidate, target="spirv",
                spirv_compiler=str(compiler),
                helpers=module.WAVEFRONT_SHADE_CANDIDATE_HELPERS,
            )
            self.assertTrue(compiled.binary)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_wavefront_shade_candidate_volume_specializations_compile(self):
        compiler = ROOT / ".tools/glslang/usr/bin/glslangValidator"
        if not compiler.is_file():
            self.skipTest("project glslangValidator is unavailable")
        module = self._generator_module()
        source = module.generated_source(
            module.wavefront_shade_candidate,
            module.WAVEFRONT_SHADE_CANDIDATE_HELPERS,
        )
        variants = (
            (),
            ("WAVE_OVERLAPPING_VOLUMES",),
            ("WAVE_VOLUME_EMPTY_SPACE_SKIPPING",),
            ("WAVE_VOLUME_SCATTERING",),
            ("WAVE_NATIVE_TEXTURES",),
            ("WAVE_WORK_COUNTERS",),
            ("WAVE_VOLUME_SCATTERING", "WAVE_VOLUME_MULTIPLE_SCATTERING"),
            (
                "WAVE_OVERLAPPING_VOLUMES",
                "WAVE_VOLUME_EMPTY_SPACE_SKIPPING",
                "WAVE_VOLUME_SCATTERING",
                "WAVE_VOLUME_MULTIPLE_SCATTERING",
                "WAVE_NATIVE_TEXTURES",
                "WAVE_WORK_COUNTERS",
            ),
        )
        with tempfile.TemporaryDirectory() as directory:
            shader = Path(directory) / "candidate.comp"
            output = Path(directory) / "candidate.spv"
            shader.write_text(source)
            for variant in variants:
                result = subprocess.run(
                    [
                        str(compiler), "-V", "--target-env", "vulkan1.2",
                        "-S", "comp", *(f"-D{name}=1" for name in variant),
                        str(shader), "-o", str(output),
                    ],
                    check=False, capture_output=True, text=True,
                )
                self.assertEqual(
                    result.returncode, 0,
                    msg=f"variant {variant} failed:\n{result.stdout}{result.stderr}",
                )

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_wavefront_volume_abi_and_interval_are_typed(self):
        module = self._generator_module()
        source = module.osh.compile(
            module.shade_volume_probe,
            helpers=(
                module.shadeIsVolumePrimitive,
                module.shadeVolumeLocalCoordinate,
                module.shadeVolumeInterval,
                module.shadeVolumeSliceDistances,
                module.shadeVolumeTransferSample,
                module.shadeVolumeScalar,
                module.shadeVolumeBrickIndexFromVoxel,
                module.shadeVolumeBrickOccupiedAtVoxel,
                module.shadeVolumeVoxelRay,
                module.shadeVolumeAxisExitDelta,
                module.shadeVolumeBrickStepAtVoxel,
                module.shadeExtendVolumeUnion,
                module.shadeAccumulateOverlappingMedium,
                module.shadeCompositeOverlappingStep,
                module.shadeVolumeOpaqueVisibility,
                module.shadeApproximateVolumeLightTransmittance,
                module.shadeSmoothstep,
                module.shadeVolumePointLightScattering,
                module.shadeVolumeAreaLightScattering,
                module.shadeVolumeEnvironmentScattering,
                module.shadeFinalizeVolumeScattering,
                module.shadeVolumeScatteringSource,
                module.shadeVolumePhase,
                module.shadeVolumeExtinction,
                module.shadeVolumeStepCount,
                module.shadeCompositeVolumeStep,
                module.shadeApplyVolumeMarch,
                module.shadeIntegrateVolumeUntil,
                module.shadeIntegrateOverlappingVolumes,
                module.shadeIntegrateVolumesBeforeSurfaceConfigured,
                module.shadeIntegrateVolumesBeforeSurface,
                module.shadeVolumeShadowTransmittanceConfigured,
                module.shadeVolumeShadowTransmittance,
            ),
        ).source
        self.assertIn("struct VolumeHeader", source)
        self.assertIn("mat4 world_to_local", source)
        self.assertIn("vec2 shadeVolumeInterval", source)
        self.assertIn("vec4 shadeVolumeTransferSample", source)
        self.assertIn("if ((value < 0.0))", source)
        self.assertIn("return vec4(0.0)", source)
        self.assertIn("float shadeVolumePhase", source)
        self.assertIn("float shadeVolumeExtinction", source)
        self.assertIn("ShadeVolumeMarchState shadeCompositeVolumeStep", source)
        self.assertIn("WavePathState shadeApplyVolumeMarch", source)
        self.assertIn("float shadeVolumeScalar", source)
        self.assertIn("ShadeVolumeIntegrationResult shadeIntegrateVolumeUntil", source)
        self.assertIn("uniform sampler3D volume_textures[16]", source)
        self.assertIn("texture(volume_textures[volume_index], local).r", source)
        self.assertIn("ShadeVolumeBrickStep shadeVolumeBrickStepAtVoxel", source)
        self.assertIn("if ((!brick_step.occupied))", source)
        self.assertIn("ShadeVolumeUnionBounds shadeExtendVolumeUnion", source)
        self.assertIn("ShadeOverlappingMedium shadeAccumulateOverlappingMedium", source)
        self.assertIn("shadeCompositeOverlappingStep", source)
        self.assertIn("float shadeVolumeOpaqueVisibility", source)
        self.assertIn("shadeApproximateVolumeLightTransmittance", source)
        self.assertIn("vec3 shadeVolumePointLightScattering", source)
        self.assertIn("vec3 shadeFinalizeVolumeScattering", source)
        self.assertIn("vec3 shadeVolumeScatteringSource", source)
        self.assertIn("if (scattering_enabled)", source)
        self.assertIn("float entries[16]", source)
        self.assertIn("vec3 scattering_sources[16]", source)
        self.assertIn("shadeIntegrateOverlappingVolumes", source)
        self.assertIn("WavePathState shadeIntegrateVolumesBeforeSurface", source)
        self.assertIn("float shadeVolumeShadowTransmittance", source)
        self.assertIn("rayQueryInitializeEXT", source)
        self.assertIn("binding = 17", source)

    def test_indirect_clear_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_indirect_clear.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("local_size_x = 256", source)
        self.assertIn("layout(push_constant)", source)
        self.assertIn("uint indirect_reservoirs[];", source)
        self.assertIn("reservoir_index >= clear_constants.reservoir_count", source)
        self.assertIn("for (int word = 0; word < 6; word += 1)", source)

    def test_prepare_indirect_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_prepare_indirect.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("local_size_x = 1", source)
        self.assertIn("readonly buffer work_queue_Block", source)
        self.assertIn("writeonly buffer dispatch_arguments_Block", source)
        self.assertIn("uint active_count = min(work_queue.count", source)
        self.assertIn("dispatch_arguments.group_count_x", source)

    def test_resolve_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_resolve.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("local_size_x = 64", source)
        self.assertIn("readonly buffer paths_Block", source)
        self.assertIn("writeonly buffer pixels_Block", source)
        self.assertIn("layout(push_constant) uniform push_Block", source)
        self.assertIn("path_index >= push.path_count", source)
        self.assertIn("pixels[path_index].radiance", source)

    def test_tone_map_is_a_composed_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_tone_map.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("vec3 acesApproximation(vec3 color)", source)
        self.assertIn("vec3 linearToSrgb(vec3 color)", source)
        self.assertIn("packUnorm4x8", source)
        self.assertIn("writeonly buffer rgba8_Block", source)

    def test_tone_map_image_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_tone_map_image.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("writeonly image2D output_image", source)
        self.assertIn("ivec2 output_size = imageSize(output_image)", source)
        self.assertIn("for (int y = first.y", source)
        self.assertIn("imageStore(output_image, ivec2(x, y), output_color)", source)

    def test_nv12_is_a_generated_complete_stage(self):
        source = (ROOT / "ordinarylight/shaders/rgba_to_nv12.comp").read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("uint nv12ByteValue(float value)", source)
        self.assertIn("uvec2 nv12Chroma(vec3 rgb)", source)
        self.assertIn("uint pack4Bytes", source)
        self.assertIn("writeonly buffer words_Block", source)
        self.assertIn("words[chroma_word]", source)

    def test_p010_is_a_composed_generated_complete_stage(self):
        source = (ROOT / "ordinarylight/shaders/hdr_to_p010.comp").read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("uint p010TenBitValue(float value)", source)
        self.assertIn("vec3 p010Color(vec3 linear, float exposure)", source)
        self.assertIn("uint pack2x16", source)
        self.assertIn("ivec2 source_size = imageSize(hdr_input)", source)
        self.assertIn("words[(chroma_word + uint(1))]", source)

    def test_atrous_denoiser_is_a_composed_generated_complete_stage(self):
        source = (ROOT / "ordinarylight/shaders/denoise_atrous.comp").read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("vec3 decodeAtrousNormal(vec2 encoded)", source)
        self.assertIn("float atrousKernel(int index)", source)
        self.assertIn("layout(set = 0, binding = 13, rgba32f)", source)
        self.assertIn("for (int y = (-2); y < 3; y += 1)", source)
        self.assertIn("for (int x = (-2); x < 3; x += 1)", source)
        self.assertIn("imageStore(filtered_a", source)
        self.assertIn("imageStore(filtered_b", source)

    def test_display_tone_map_is_a_composed_generated_complete_stage(self):
        source = (ROOT / "ordinarylight/shaders/tone_map.comp").read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("bool overlayLetterPixel", source)
        self.assertIn("uint overlayDigitMask", source)
        self.assertIn("vec3 fpsOverlay", source)
        self.assertIn("break;", source)
        self.assertIn("layout(set = 0, binding = 13, rgba32f)", source)
        self.assertIn("imageStore(output_image", source)

    def test_primary_ray_generation_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_generate.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("struct WaveRay", source)
        self.assertIn("WaveRay rays[];", source)
        self.assertIn("uint waveHash(uint value)", source)
        self.assertIn("float waveRandomFloat(uint value)", source)
        self.assertIn("layout(std430, set = 0, binding = 3)", source)
        self.assertIn("readonly buffer camera_Block", source)
        self.assertIn("ray_queue.rays[path_index].direction_tmax", source)
        self.assertIn("stacks[(path_index * uint(16))] = 1.0", source)

    def test_ray_intersection_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_intersect.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("#extension GL_EXT_ray_query : require", source)
        self.assertIn("uniform accelerationStructureEXT scene_tlas", source)
        self.assertIn("WaveRay rays[];", source)
        self.assertIn("WaveHit hits[];", source)
        self.assertIn("rayQueryInitializeEXT(query, scene_tlas", source)
        self.assertIn("while (rayQueryProceedEXT(query))", source)
        self.assertIn("rayQueryGetIntersectionBarycentricsEXT", source)
        self.assertIn("cross((vertex_b - vertex_a)", source)

    def test_bucketed_intersection_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_intersect_bucketed.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("GL_KHR_shader_subgroup_basic", source)
        self.assertIn("GL_KHR_shader_subgroup_ballot", source)
        self.assertIn("subgroupBallot(belongs)", source)
        self.assertIn("subgroupBallotExclusiveBitCount(lane_mask)", source)
        self.assertIn("atomicAdd(textured_queue.textured_count", source)
        self.assertIn("any(greaterThanEqual", source)
        self.assertIn("textured_queue.textured_hits[output_index] = hit", source)

    def test_indirect_reuse_probe_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_indirect_reuse_probe.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("struct IndirectLightReservoir", source)
        self.assertIn("uint indirectPackRgb9e5", source)
        self.assertIn("void storeIndirectLightReservoir", source)
        self.assertIn("IndirectLightReservoir loadIndirectLightReservoir", source)
        self.assertIn("memoryBarrierBuffer()", source)
        self.assertIn("indirect_reservoir_words[uint(5)]", source)

    def test_path_to_hdr_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_path_to_hdr.comp"
        ).read_text()
        shade_source = (
            ROOT / "ordinarylight/shaders/wavefront_shade_candidate.glsl"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("struct SecondaryPathState", source)
        self.assertIn("vec4 primary_geometry;", source)
        self.assertIn("vec4 primary_geometry;", shade_source)
        self.assertIn("layout(set = 0, binding = 1, rgba16f)", source)
        self.assertIn("imageStore(hdr_image", source)
        self.assertIn("push.reservoir_width", source)
        self.assertIn("indirect_seed_words[reservoir_index]", source)
        self.assertIn("void storeIndirectLightReservoir", source)
        self.assertIn("camera.origin.xyz", source)

    def test_indirect_candidates_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_indirect_candidates.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("#extension GL_EXT_ray_query : require", source)
        self.assertIn("readonly uimage2D normal_image", source)
        self.assertIn("CandidateProjection candidateReprojectPrevious", source)
        self.assertIn("CandidateMergeResult candidateMergePrevious", source)
        self.assertIn("rayQueryInitializeEXT(query, scene_tlas", source)
        self.assertIn("for (int neighbor = 0; neighbor < 4", source)
        self.assertIn("atomicAdd(counters[uint(15)]", source)
        self.assertIn("storeIndirectLightReservoir(reservoir_index", source)

    def test_indirect_debug_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_indirect_debug.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("readonly uimage2D material_image", source)
        self.assertIn("vec3 indirectAcceptanceColor", source)
        self.assertIn("IndirectCorrectionResult indirectCorrection", source)
        self.assertIn("for (int y = 0; y < 2", source)
        self.assertIn("filtered_correction", source)
        self.assertIn("imageStore(debug_image", source)

    def test_reconstruction_is_a_generated_complete_stage(self):
        source = (
            ROOT / "ordinarylight/shaders/wavefront_reconstruct.comp"
        ).read_text()
        self.assertIn("Generated by scripts/generate_core_shaders.py", source)
        self.assertIn("#if WAVE_BGRA_OUTPUT", source)
        self.assertIn("writeonly image2D output_images[8]", source)
        self.assertIn("ReprojectionResult reconstructReproject", source)
        self.assertIn("vec3 reconstructFilterDiffuse", source)
        self.assertIn("push.variance_confidence_enabled", source)
        self.assertIn("push.outlier_confidence_enabled", source)
        self.assertIn("ordinarylight_outline", source)
        self.assertIn("imageStore(history_color", source)
        self.assertIn("imageStore(output_images[output_index]", source)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_checked_in_stage_matches_ordinaryshade_output(self):
        module = self._generator_module()
        for output, shader in module.GENERATED.items():
            self.assertEqual(
                output.read_text(),
                module.generated_source(shader, module.HELPERS.get(output, ())),
            )

    @staticmethod
    def _generator_module():
        path = ROOT / "scripts/generate_core_shaders.py"
        spec = importlib.util.spec_from_file_location(
            "generate_core_shaders", path,
        )
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        try:
            spec.loader.exec_module(module)
        finally:
            sys.modules.pop(spec.name, None)
        return module


if __name__ == "__main__":
    unittest.main()
