import importlib.util
from pathlib import Path
import unittest


ROOT = Path(__file__).parents[1]


class OrdinaryShadeEffectTests(unittest.TestCase):
    def test_checked_in_tint_helper_is_used_by_reconstruction(self):
        helper = (
            ROOT / "ordinarylight/shaders/ordinaryshade_effects.glsl"
        ).read_text()
        reconstruct = (
            ROOT / "ordinarylight/shaders/wavefront_reconstruct.comp"
        ).read_text()
        self.assertIn("vec3 ordinarylight_tint", helper)
        self.assertIn("vec3 ordinarylight_emissive", helper)
        self.assertIn("vec3 ordinarylight_isolation", helper)
        self.assertIn("vec3 ordinarylight_outline", helper)
        self.assertIn("Generated by scripts/generate_core_shaders.py", reconstruct)
        self.assertIn("vec3 ordinarylight_tint", reconstruct)
        self.assertIn("vec3 ordinarylight_emissive", reconstruct)
        self.assertIn("vec3 ordinarylight_isolation", reconstruct)
        self.assertIn("vec3 ordinarylight_outline", reconstruct)
        self.assertIn("encoded.rgb = ordinarylight_tint(", reconstruct)

    @unittest.skipUnless(
        (ROOT.parent / "ordinaryshade/ordinaryshade").is_dir(),
        "sibling Ordinary Shade checkout is unavailable",
    )
    def test_checked_in_helpers_match_ordinaryshade_output(self):
        path = ROOT / "scripts/generate_effect_shaders.py"
        spec = importlib.util.spec_from_file_location("generate_effect_shaders", path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        expected = (
            ROOT / "ordinarylight/shaders/ordinaryshade_effects.glsl"
        ).read_text()
        self.assertEqual(module.generated_source(), expected)


if __name__ == "__main__":
    unittest.main()
