// Generated by scripts/generate_transport_kernels.py using OrdinaryShade.

uint OL_BOX_ENTRY(vec3 origin, vec3 direction, float t_min, float t_max, vec4 parameters, float tolerance, uint max_steps, inout OrdinaryLightCustomHit hit)
{
    bool found = false;
    float closest = t_max;
    if ((((((any(isnan(parameters.xy)) || any(isinf(parameters.xy))) || (parameters.x < 0.0)) || (parameters.y < 1.0)) || any(notEqual(floor(parameters.xy), parameters.xy))) || any(greaterThan(parameters.xy, vec2(16777216.0)))))
    {
        return uint(2);
    }
    uint first = uint(parameters.x);
    uint count = uint(parameters.y);
    uint index_count = (uint(OL_BOX_RESOURCE.length()) / uint(3));
#if OL_BOX_PARTITIONED
    index_count = uint(OL_BOX_INDICES.length());
#endif
    if (((count > max_steps) || ((first + count) > index_count)))
    {
        return uint(2);
    }
    uint slot = first;
    while ((slot < (first + count)))
    {
        uint i = slot;
#if OL_BOX_PARTITIONED
        i = OL_BOX_INDICES[slot];
#endif
        if ((i >= (uint(uint(OL_BOX_RESOURCE.length())) / uint(3))))
        {
            return uint(2);
        }
        vec4 lower = OL_BOX_RESOURCE[(i * uint(3))];
        vec4 upper = OL_BOX_RESOURCE[((i * uint(3)) + uint(1))];
        if ((lower.w == 0.0))
        {
            slot = (slot + 1);
            continue;
        }
        if (((((((lower.w != 1.0) || any(isnan(lower.xyz))) || any(isinf(lower.xyz))) || any(isnan(upper.xyz))) || any(isinf(upper.xyz))) || any(greaterThanEqual(lower.xyz, upper.xyz))))
        {
            return uint(2);
        }
        float near_t = (-1e+30);
        float far_t = 1e+30;
        vec3 near_n = vec3(0);
        vec3 far_n = vec3(0);
        bool missed = false;
        int axis = 0;
        while ((axis < 3))
        {
            if ((abs(direction[axis]) < 1e-20))
            {
                if (((origin[axis] < lower[axis]) || (origin[axis] > upper[axis])))
                {
                    missed = true;
                }
            }
            else
            {
                float a = ((lower[axis] - origin[axis]) / direction[axis]);
                float b = ((upper[axis] - origin[axis]) / direction[axis]);
                vec3 n = vec3(0);
                n[axis] = ((direction[axis] > 0.0) ? (-1.0) : 1.0);
                if ((min(a, b) > near_t))
                {
                    near_t = min(a, b);
                    near_n = n;
                }
                if ((max(a, b) < far_t))
                {
                    far_t = max(a, b);
                    far_n = (-n);
                }
            }
            axis = (axis + 1);
        }
        if ((missed || (near_t > far_t)))
        {
            slot = (slot + 1);
            continue;
        }
        bool entry = (near_t >= (t_min - tolerance));
        float distance = (entry ? max(near_t, t_min) : far_t);
        if (((distance < t_min) || (distance > closest)))
        {
            slot = (slot + 1);
            continue;
        }
        uvec4 metadata = floatBitsToUint(OL_BOX_RESOURCE[((i * uint(3)) + uint(2))]);
        hit.distance = distance;
        hit.geometric_normal = (entry ? near_n : far_n);
        hit.material = metadata.x;
        hit.boundary = metadata.y;
        hit.identity = metadata.z;
        hit.flags = ((OL_HIT_MATERIAL | OL_HIT_BOUNDARY) | OL_HIT_IDENTITY);
        closest = distance;
        found = true;
        slot = (slot + 1);
    }
    return (found ? uint(1) : uint(0));
}
