// Generated by scripts/generate_transport_shaders.py using OrdinaryShade.
// Edit ordinarylight/shaders/transport_programs.py.
#ifndef ORDINARYLIGHT_GENERATED_TRANSPORT_CONTRACTS
#define ORDINARYLIGHT_GENERATED_TRANSPORT_CONTRACTS 1
struct OrdinaryLightSurfaceSample
{
    vec4 position;
    vec4 geometric_normal;
    vec4 shading_normal;
    vec4 incoming;
    uvec4 identity;
    uvec4 media;
};

uint ordinarylightDestinationMedium(OrdinaryLightSurfaceSample surface, vec3 direction);
bool ordinarylightEnteringMedium(vec3 direction, vec3 geometric_normal)
{
    return (dot(direction, geometric_normal) < 0.0);
}

bool ordinarylightEnteringMedium(vec3 direction, vec3 geometric_normal);
uint ordinarylightDestinationMedium(OrdinaryLightSurfaceSample surface, vec3 direction)
{
    return (ordinarylightEnteringMedium(direction, surface.geometric_normal.xyz) ? surface.media.y : surface.media.x);
}
#endif
