// Generated by scripts/generate_transport_kernels.py using OrdinaryShade.
layout(local_size_x=64) in;
struct Record { vec4 lower; vec4 upper; vec4 parameters; uvec4 metadata; };
layout(set=0,binding=0,std430) readonly buffer Input { Record input_records[]; };
layout(set=0,binding=1,std430) writeonly buffer Output { Record output_records[]; };
layout(set=0,binding=2,std430) writeonly buffer Bounds { float bounds[]; };
layout(set=0,binding=3,std430) writeonly buffer Diagnostics { uint diagnostics[]; };
uint boundaryIndex(uint identity);
bool dielectricMaterial(uint index);
void main()
{
    uint i = gl_GlobalInvocationID.x;
    if ((i >= CAPACITY))
    {
        return;
    }
    Record record = input_records[i];
    uint status = uint(0);
    bool enabled = (record.metadata.x != uint(4294967295));
    if (enabled)
    {
        if (((record.metadata.x >= PROGRAMS) || (record.metadata.y >= MATERIALS)))
        {
            status = (status | uint(1));
        }
        if (((((((any(isnan(record.lower)) || any(isinf(record.lower))) || any(isnan(record.upper))) || any(isinf(record.upper))) || any(isnan(record.parameters))) || any(isinf(record.parameters))) || any(lessThanEqual(record.upper.xyz, record.lower.xyz))))
        {
            status = (status | uint(2));
        }
        uint boundary = boundaryIndex(record.metadata.z);
        if ((((record.metadata.z != uint(4294967295)) && (boundary == uint(4294967295))) || (dielectricMaterial(record.metadata.y) != (boundary != uint(4294967295)))))
        {
            status = (status | uint(4));
        }
        record.metadata.y = (record.metadata.y + TRIANGLES);
        record.metadata.z = boundary;
    }
    if (((!enabled) || (status != uint(0))))
    {
        record.lower = vec4(0);
        record.upper = vec4(0.0001);
        record.parameters = vec4(0);
        record.metadata = uvec4(uint(4294967295), 0, uint(4294967295), 0);
    }
    output_records[i] = record;
    uint axis = uint(0);
    while ((axis < uint(3)))
    {
        bounds[((i * uint(6)) + axis)] = record.lower[axis];
        bounds[(((i * uint(6)) + axis) + uint(3))] = record.upper[axis];
        axis = (axis + 1);
    }
    diagnostics[i] = status;
}
