// Generated by scripts/generate_transport_kernels.py using OrdinaryShade.
layout(local_size_x=64) in;
layout(set=0,binding=0,std430) readonly buffer Counts { uvec4 counts; };
layout(set=0,binding=1,std430) readonly buffer Groups { uvec4 groups[]; };
layout(set=0,binding=2,std430) readonly buffer Indices { uint indices[]; };
layout(set=0,binding=3,std430) readonly buffer Weights { vec2 weights[]; };
layout(set=0,binding=4,std430) readonly buffer Samples { OrdinaryLightSurfaceSample samples[]; };
layout(set=0,binding=5,std430) buffer State { uvec4 state; uvec4 commands[4]; };
struct SampleAccumulation { vec4 radiance; uvec4 counts; uvec4 events; };
layout(set=0,binding=6,std430) buffer Output { SampleAccumulation accumulated[]; };
layout(push_constant) uniform Constants { uint capacity; uint groups_capacity; uint output_capacity; uint mode; } pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if ((pc.mode == uint(0)))
    {
        if ((i != uint(0)))
        {
            return;
        }
        bool valid = ((((counts.x <= pc.capacity) && (counts.y <= pc.groups_capacity)) && (counts.y <= counts.x)) && ((counts.x == uint(0)) == (counts.y == uint(0))));
        state = uvec4((valid ? counts.xy : uvec2(0)), (valid ? uint(0) : uint(32)), 0);
        commands[0] = uvec4(((state.x + uint(63)) / uint(64)), 1, 1, 0);
        commands[1] = uvec4(0, 1, 1, 0);
        commands[2] = uvec4(0, 1, 1, 0);
        commands[3] = uvec4(0, 1, 1, 0);
        return;
    }
    if ((pc.mode == uint(2)))
    {
        if ((i != uint(0)))
        {
            return;
        }
        commands[1] = uvec4(((state.z == uint(0)) ? ((state.x + uint(63)) / uint(64)) : uint(0)), 1, 1, 0);
        commands[2] = uvec4(((state.z == uint(0)) ? ((state.y + uint(63)) / uint(64)) : uint(0)), 1, 1, 0);
        commands[3] = uvec4(((state.z != uint(0)) ? ((pc.output_capacity + uint(63)) / uint(64)) : uint(0)), 1, 1, 0);
        return;
    }
    if ((pc.mode == uint(3)))
    {
        if (((i < pc.output_capacity) && (state.z != uint(0))))
        {
            accumulated[i].counts.z = (accumulated[i].counts.z | uint(32));
        }
        return;
    }
    if ((i >= state.x))
    {
        return;
    }
    if ((i < state.y))
    {
        uvec4 group = groups[i];
        bool valid = ((((group.x < pc.output_capacity) && (group.y <= state.x)) && (group.z > uint(0))) && (group.z <= (state.x - group.y)));
        if ((i == uint(0)))
        {
            valid = (valid && (group.y == uint(0)));
        }
        else
        {
            uvec4 previous = groups[(i - uint(1))];
            valid = ((((valid && (previous.x < group.x)) && (previous.y <= state.x)) && (previous.z <= (state.x - previous.y))) && (group.y == (previous.y + previous.z)));
        }
        if (((i + uint(1)) == state.y))
        {
            valid = (valid && ((group.y + group.z) == state.x));
        }
        if ((!valid))
        {
            atomicOr(state.z, uint(32));
        }
    }
    uint lower = uint(0);
    uint upper = state.y;
    while ((lower < upper))
    {
        uint middle = (lower + ((upper - lower) / uint(2)));
        if ((groups[middle].y <= i))
        {
            lower = (middle + uint(1));
        }
        else
        {
            upper = middle;
        }
    }
    if ((lower == uint(0)))
    {
        atomicOr(state.z, uint(32));
        return;
    }
    uvec4 group = groups[(lower - uint(1))];
    uint slot = indices[i];
    if (((((slot >= state.x) || (group.y > i)) || (group.z > state.x)) || ((i - group.y) >= group.z)))
    {
        atomicOr(state.z, uint(32));
        return;
    }
    if (((((((i > group.y) && (indices[(i - uint(1))] >= slot)) || (samples[slot].identity.x != group.x)) || any(isnan(weights[slot]))) || any(isinf(weights[slot]))) || any(lessThan(weights[slot], vec2(0)))))
    {
        atomicOr(state.z, uint(32));
    }
}
