// Generated by scripts/generate_transport_kernels.py using OrdinaryShade.
// Bound resources are declared by the integrator/diagnostic client.
struct OrdinaryLightHit {
    vec4 position_distance;
    vec4 geometric_normal;
    vec4 shading_normal;
    uvec4 identity; // kind (0 miss,1 triangle,2 custom), primitive, app ID, material
    uvec4 boundary; // boundary index, outside medium, inside medium, status
};
bool ordinarylightBounds(vec3 origin, vec3 direction, vec3 lower, vec3 upper, inout float near_t, inout float far_t)
{
    int axis = 0;
    while ((axis < 3))
    {
        if ((abs(direction[axis]) < 1e-20))
        {
            if (((origin[axis] < lower[axis]) || (origin[axis] > upper[axis])))
            {
                return false;
            }
        }
        else
        {
            float a = ((lower[axis] - origin[axis]) / direction[axis]);
            float b = ((upper[axis] - origin[axis]) / direction[axis]);
            near_t = max(near_t, min(a, b));
            far_t = min(far_t, max(a, b));
        }
        axis = (axis + 1);
    }
    return (near_t <= far_t);
}
bool ordinarylightBounds(vec3 origin, vec3 direction, vec3 lower, vec3 upper, inout float near_t, inout float far_t);
uint ordinarylightCustomIntersect(uint program, vec3 origin, vec3 direction, float t_min, float t_max, vec4 parameters, float tolerance, uint max_steps, inout OrdinaryLightCustomHit result);
OrdinaryLightHit ordinarylightIntersect(vec3 origin, vec3 direction, float t_min, float t_max, float tolerance, uint max_steps)
{
    OrdinaryLightHit hit = OrdinaryLightHit(vec4(0), vec4(0), vec4(0), uvec4(0), uvec4(0));
    hit.position_distance = vec4(0, 0, 0, t_max);
    hit.geometric_normal = vec4(0);
    hit.shading_normal = vec4(0);
    hit.identity = uvec4(0);
    hit.boundary = uvec4(uint(4294967295), 0, 0, 0);
    rayQueryEXT query;
    rayQueryInitializeEXT(query, transport_tlas, gl_RayFlagsOpaqueEXT, 255, origin, t_min, direction, t_max);
    OrdinaryLightHit generated_hit = hit;
    while (rayQueryProceedEXT(query))
    {
        if ((rayQueryGetIntersectionTypeEXT(query, false) != gl_RayQueryCandidateIntersectionAABBEXT))
        {
            continue;
        }
        uint index = rayQueryGetIntersectionPrimitiveIndexEXT(query, false);
        CustomRecord geometry = custom_geometry[index];
        if ((geometry.metadata.x == uint(4294967295)))
        {
            continue;
        }
        float near_t = t_min;
        float far_t = t_max;
        if ((rayQueryGetIntersectionTypeEXT(query, true) != gl_RayQueryCommittedIntersectionNoneEXT))
        {
            far_t = min(far_t, rayQueryGetIntersectionTEXT(query, true));
        }
        if ((!ordinarylightBounds(origin, direction, geometry.lower.xyz, geometry.upper.xyz, near_t, far_t)))
        {
            continue;
        }
        OrdinaryLightCustomHit result = OrdinaryLightCustomHit(float(0), vec3(0), uint(0), uint(0), uint(0), uint(0), vec2(0), vec3(0));
        result.distance = 0;
        result.geometric_normal = vec3(0);
        result.flags = uint(0);
        result.material = uint(0);
        result.boundary = OL_NO_BOUNDARY;
        result.identity = uint(0);
        result.uv = vec2(0);
        result.shading_normal = vec3(0);
        uint status = ordinarylightCustomIntersect(geometry.metadata.x, origin, direction, near_t, far_t, geometry.parameters, tolerance, max_steps, result);
        float distance = result.distance;
        vec3 normal = result.geometric_normal;
        if (((status > uint(1)) || ((status == uint(1)) && ((((((isnan(distance) || isinf(distance)) || any(isnan(normal))) || any(isinf(normal))) || (abs((dot(normal, normal) - 1.0)) > 0.001)) || (distance < (near_t - tolerance))) || (distance > (far_t + tolerance))))))
        {
            hit.boundary.w = uint(1);
            rayQueryTerminateEXT(query);
            return hit;
        }
        if ((((status == uint(1)) && (distance <= far_t)) && (distance >= t_min)))
        {
            uint material = geometry.metadata.y;
            uint boundary = geometry.metadata.z;
            uint identity = geometry.metadata.w;
            if (((result.flags & (~uint(31))) != uint(0)))
            {
                hit.boundary.w = uint(32);
                rayQueryTerminateEXT(query);
                return hit;
            }
            if (((result.flags & OL_HIT_MATERIAL) != uint(0)))
            {
                if ((result.material >= (OL_MATERIAL_COUNT - OL_CUSTOM_MATERIAL_OFFSET)))
                {
                    hit.boundary.w = uint(32);
                    rayQueryTerminateEXT(query);
                    return hit;
                }
                material = (OL_CUSTOM_MATERIAL_OFFSET + result.material);
            }
            if (((result.flags & OL_HIT_BOUNDARY) != uint(0)))
            {
                boundary = OL_NO_BOUNDARY;
                if ((result.boundary != OL_NO_BOUNDARY))
                {
                    uint i = uint(0);
                    while ((i < OL_BOUNDARY_COUNT))
                    {
                        if ((medium_boundaries[i].z == result.boundary))
                        {
                            boundary = i;
                            break;
                        }
                        i = (i + 1);
                    }
                    if ((boundary == OL_NO_BOUNDARY))
                    {
                        hit.boundary.w = uint(32);
                        rayQueryTerminateEXT(query);
                        return hit;
                    }
                }
            }
            if (((material >= OL_MATERIAL_COUNT) || ((boundary != OL_NO_BOUNDARY) && (boundary >= OL_BOUNDARY_COUNT))))
            {
                hit.boundary.w = uint(32);
                rayQueryTerminateEXT(query);
                return hit;
            }
            if (((transport_materials[material].albedo_kind.w == 1.0) != (boundary != OL_NO_BOUNDARY)))
            {
                hit.boundary.w = uint(32);
                rayQueryTerminateEXT(query);
                return hit;
            }
            if (((result.flags & OL_HIT_IDENTITY) != uint(0)))
            {
                identity = result.identity;
            }
            vec2 uv = (((result.flags & OL_HIT_UV) != uint(0)) ? result.uv : vec2(0));
            vec3 shading = (((result.flags & OL_HIT_SHADING_NORMAL) != uint(0)) ? result.shading_normal : normal);
            if ((((((any(isnan(uv)) || any(isinf(uv))) || any(isnan(shading))) || any(isinf(shading))) || (abs((dot(shading, shading) - 1.0)) > 0.001)) || (dot(shading, normal) <= 0.0)))
            {
                hit.boundary.w = uint(1);
                rayQueryTerminateEXT(query);
                return hit;
            }
            rayQueryGenerateIntersectionEXT(query, distance);
            if ((((rayQueryGetIntersectionTypeEXT(query, true) == gl_RayQueryCommittedIntersectionGeneratedEXT) && (rayQueryGetIntersectionPrimitiveIndexEXT(query, true) == index)) && (rayQueryGetIntersectionTEXT(query, true) == distance)))
            {
                generated_hit.identity = uvec4(2, index, identity, material);
                generated_hit.boundary.x = boundary;
                generated_hit.geometric_normal = vec4(normalize(normal), uv.x);
                generated_hit.shading_normal = vec4(normalize(shading), uv.y);
            }
        }
    }
    uint kind = rayQueryGetIntersectionTypeEXT(query, true);
    if ((kind == gl_RayQueryCommittedIntersectionNoneEXT))
    {
        return hit;
    }
    float distance = rayQueryGetIntersectionTEXT(query, true);
    uint index = rayQueryGetIntersectionPrimitiveIndexEXT(query, true);
    hit.position_distance = vec4((origin + (distance * direction)), distance);
    if ((kind == gl_RayQueryCommittedIntersectionTriangleEXT))
    {
        index = (index + rayQueryGetIntersectionInstanceCustomIndexEXT(query, true));
        vec3 a = transport_vertices[(index * uint(3))].xyz;
        vec3 b = transport_vertices[((index * uint(3)) + uint(1))].xyz;
        vec3 c = transport_vertices[((index * uint(3)) + uint(2))].xyz;
        vec3 geometric = normalize(cross((b - a), (c - a)));
        vec2 uv = rayQueryGetIntersectionBarycentricsEXT(query, true);
        vec3 shading = (((transport_attributes[(index * uint(9))].xyz * ((1.0 - uv.x) - uv.y)) + (transport_attributes[((index * uint(9)) + uint(3))].xyz * uv.x)) + (transport_attributes[((index * uint(9)) + uint(6))].xyz * uv.y));
        if ((dot(shading, shading) < 1e-12))
        {
            shading = geometric;
        }
        shading = normalize(shading);
        if ((dot(shading, geometric) < 0))
        {
            shading = (-shading);
        }
        uvec4 metadata = triangle_records[index];
        hit.identity = uvec4(1, index, metadata.z, metadata.x);
        hit.boundary.x = metadata.y;
        vec2 texcoord = (((transport_attributes[((index * uint(9)) + uint(1))].xy * ((1.0 - uv.x) - uv.y)) + (transport_attributes[((index * uint(9)) + uint(4))].xy * uv.x)) + (transport_attributes[((index * uint(9)) + uint(7))].xy * uv.y));
        hit.geometric_normal = vec4(geometric, texcoord.x);
        hit.shading_normal = vec4(shading, texcoord.y);
    }
    else
    {
        hit.identity = generated_hit.identity;
        hit.boundary.x = generated_hit.boundary.x;
        hit.geometric_normal = generated_hit.geometric_normal;
        hit.shading_normal = generated_hit.shading_normal;
    }
    if ((hit.boundary.x != uint(4294967295)))
    {
        hit.boundary.yz = medium_boundaries[hit.boundary.x].xy;
    }
    return hit;
}
