// Generated by scripts/generate_lighting_shaders.py using OrdinaryShade.
// OrdinaryLight transport ABI v1. See docs/renderer_extensions.md.
#if !defined(ORDINARYLIGHT_TRANSPORT_LIGHTING_V1)
#define ORDINARYLIGHT_TRANSPORT_LIGHTING_V1 1
#if !defined(OL_TRANSPORT_RAY_ORIGIN)
#define OL_TRANSPORT_RAY_ORIGIN ordinarylightDefaultRayOrigin
vec3 ordinarylightDefaultRayOrigin(vec3 hit, vec3 normal)
{
    return (hit + (normal * 0.002));
}
#endif
#if !defined(OL_TRANSPORT_AREA_LIGHT_COUNT)
#error Define OL_TRANSPORT_AREA_LIGHT_COUNT before including transport lighting v1
#endif
#if !defined(OL_TRANSPORT_AREA_LIGHT_WEIGHT)
#error Define OL_TRANSPORT_AREA_LIGHT_WEIGHT before including transport lighting v1
#endif
#if !defined(OL_TRANSPORT_ENVIRONMENT_SAMPLES)
#error Define OL_TRANSPORT_ENVIRONMENT_SAMPLES before including transport lighting v1
#endif
#if !defined(OL_TRANSPORT_POINT_LIGHT_COUNT)
#error Define OL_TRANSPORT_POINT_LIGHT_COUNT before including transport lighting v1
#endif
#if !defined(OL_TRANSPORT_SECONDARY_AREA_LIGHT_SAMPLES)
#error Define OL_TRANSPORT_SECONDARY_AREA_LIGHT_SAMPLES before including transport lighting v1
#endif
#include "wavefront_restir.glsl"

#include "transport_v1/sampling.glsl"

float pbrSpecularProbability(MaterialData material)
{
    vec3 f0 = mix(vec3(0.04), material.base_roughness.rgb, material.emission_metallic.a);
    return clamp(max(f0.r, max(f0.g, f0.b)), 0.1, 0.9);
}

// Per-invocation scratch for the most recent BSDF evaluation. Callers
// consume it only for accepted contributions, never candidate target sums.
vec3 transportLastSpecularFraction = vec3(0.0);
vec3 transportPointSpecular = vec3(0.0);

// Per-invocation primary BRDF scratch. Only production ReSTIR enables this:
// generalized proposal evaluations can use a different normal/view, so their
// path must remain uncached. Primary disables the cache before continuation.
#if !defined(WAVE_PREPARED_PRIMARY_PBR)
#define WAVE_PREPARED_PRIMARY_PBR 1
#endif
bool transportPbrPrepared = false;
vec3 transportPbrF0;
vec4 transportPbrLobes;
float transportPbrProbability;
float transportPbrViewCosine;
vec3 transportPbrTangent;
vec3 transportPbrBitangent;
float transportPbrGeometry;
float transportPbrCoatGeometry;
float ggxSmithComponent(float n_dot_direction, float roughness);
float pbrSpecularProbability(MaterialData material);
void preparePrimaryPbr(MaterialData material, vec3 normal, vec3 view)
{
    transportPbrF0 = mix(vec3(0.04), material.base_roughness.rgb, material.emission_metallic.a);
    float anisotropy = clamp(material.advanced0.w, (-1.0), 1.0);
    float alpha = max((material.base_roughness.a * material.base_roughness.a), 0.02);
    transportPbrLobes = vec4(max((alpha * (1.0 - (0.7 * anisotropy))), 0.02), max((alpha * (1.0 + (0.7 * anisotropy))), 0.02), clamp(material.advanced0.y, 0.02, 1.0), clamp(material.advanced0.x, 0.0, 1.0));
    transportPbrProbability = clamp((pbrSpecularProbability(material) + (material.advanced0.x * 0.15)), 0.1, 0.95);
    transportPbrViewCosine = max(dot(normal, view), 0.0);
    transportPbrTangent = normalize(((abs(normal.z) < 0.999) ? cross(normal, vec3(0.0, 0.0, 1.0)) : cross(normal, vec3(0.0, 1.0, 0.0))));
    transportPbrBitangent = cross(normal, transportPbrTangent);
    transportPbrGeometry = ggxSmithComponent(transportPbrViewCosine, material.base_roughness.a);
    transportPbrCoatGeometry = ggxSmithComponent(transportPbrViewCosine, transportPbrLobes.z);
    transportPbrPrepared = true;
}

float ggxDistribution(float n_dot_h, float roughness);
float ggxSmithComponent(float n_dot_direction, float roughness);
vec3 pbrFresnel(vec3 f0, float cosine);
vec3 evaluatePbr(MaterialData material, vec3 normal, vec3 view, vec3 outgoing)
{
    float n_dot_v = (transportPbrPrepared ? transportPbrViewCosine : max(dot(normal, view), 0.0));
    float n_dot_l = max(dot(normal, outgoing), 0.0);
    transportLastSpecularFraction = vec3(0.0);
    if (((n_dot_v <= 0.0) || (n_dot_l <= 0.0)))
    {
        return vec3(0.0);
    }
    vec3 half_vector = normalize((view + outgoing));
    float n_dot_h = max(dot(normal, half_vector), 0.0);
    float v_dot_h = max(dot(view, half_vector), 0.0);
    float metallic = material.emission_metallic.a;
    vec3 f0 = (transportPbrPrepared ? transportPbrF0 : mix(vec3(0.04), material.base_roughness.rgb, metallic));
    vec3 fresnel = pbrFresnel(f0, v_dot_h);
    float anisotropy = clamp(material.advanced0.w, (-1.0), 1.0);
    vec3 tangent = (transportPbrPrepared ? transportPbrTangent : normalize(((abs(normal.z) < 0.999) ? cross(normal, vec3(0.0, 0.0, 1.0)) : cross(normal, vec3(0.0, 1.0, 0.0)))));
    vec3 bitangent = (transportPbrPrepared ? transportPbrBitangent : cross(normal, tangent));
    float alpha = max((material.base_roughness.a * material.base_roughness.a), 0.02);
    float alpha_x = (transportPbrPrepared ? transportPbrLobes.x : max((alpha * (1.0 - (0.7 * anisotropy))), 0.02));
    float alpha_y = (transportPbrPrepared ? transportPbrLobes.y : max((alpha * (1.0 + (0.7 * anisotropy))), 0.02));
    float anisotropic_denominator = ((((dot(half_vector, tangent) * dot(half_vector, tangent)) / (alpha_x * alpha_x)) + ((dot(half_vector, bitangent) * dot(half_vector, bitangent)) / (alpha_y * alpha_y))) + (n_dot_h * n_dot_h));
    float distribution = (1.0 / max(((((3.14159265359 * alpha_x) * alpha_y) * anisotropic_denominator) * anisotropic_denominator), 1e-06));
    float geometry = ((transportPbrPrepared ? transportPbrGeometry : ggxSmithComponent(n_dot_v, material.base_roughness.a)) * ggxSmithComponent(n_dot_l, material.base_roughness.a));
    vec3 specular = (((fresnel * distribution) * geometry) / max(((4.0 * n_dot_v) * n_dot_l), 1e-06));
    vec3 diffuse = ((((vec3(1.0) - fresnel) * (1.0 - metallic)) * material.base_roughness.rgb) / 3.14159265359);
    float subsurface = clamp(material.advanced1.x, 0.0, 1.0);
    diffuse = mix(diffuse, (diffuse * material.subsurface_color.rgb), subsurface);
    float sheen_weight = ((1.0 - clamp(material.advanced0.z, 0.0, 1.0)) * pow((1.0 - v_dot_h), 5.0));
    vec3 sheen = (material.sheen_color.rgb * sheen_weight);
    float clearcoat = (transportPbrPrepared ? transportPbrLobes.w : clamp(material.advanced0.x, 0.0, 1.0));
    float coat_roughness = (transportPbrPrepared ? transportPbrLobes.z : clamp(material.advanced0.y, 0.02, 1.0));
    float coat_distribution = ggxDistribution(n_dot_h, coat_roughness);
    float coat_geometry = ((transportPbrPrepared ? transportPbrCoatGeometry : ggxSmithComponent(n_dot_v, coat_roughness)) * ggxSmithComponent(n_dot_l, coat_roughness));
    float coat_fresnel = (0.04 + (0.96 * pow((1.0 - v_dot_h), 5.0)));
    vec3 coat = vec3(((((clearcoat * coat_distribution) * coat_geometry) * coat_fresnel) / max(((4.0 * n_dot_v) * n_dot_l), 1e-06)));
    float base_energy = (1.0 - (clearcoat * coat_fresnel));
    vec3 combined = ((((diffuse + specular) + sheen) * base_energy) + coat);
    vec3 reflected = (((specular + sheen) * base_energy) + coat);
    transportLastSpecularFraction = clamp((reflected / max(combined, vec3(1e-30))), vec3(0.0), vec3(1.0));
    return combined;
}

float ggxDistribution(float n_dot_h, float roughness);
float pbrSpecularProbability(MaterialData material);
float pbrPdf(MaterialData material, vec3 normal, vec3 view, vec3 outgoing)
{
    float n_dot_l = max(dot(normal, outgoing), 0.0);
    if ((n_dot_l <= 0.0))
    {
        return 0.0;
    }
    vec3 half_vector = normalize((view + outgoing));
    float n_dot_h = max(dot(normal, half_vector), 0.0);
    float v_dot_h = max(dot(view, half_vector), 1e-06);
    float specular_pdf = ((ggxDistribution(n_dot_h, material.base_roughness.a) * n_dot_h) / (4.0 * v_dot_h));
    float diffuse_pdf = (n_dot_l / 3.14159265359);
    float probability = (transportPbrPrepared ? transportPbrProbability : clamp((pbrSpecularProbability(material) + (material.advanced0.x * 0.15)), 0.1, 0.95));
    return mix(diffuse_pdf, specular_pdf, probability);
}

vec3 sampleGgxHalfVector(vec3 normal, float roughness, float random_u, float random_v)
{
    float alpha = max((roughness * roughness), 0.0009);
    float alpha_squared = (alpha * alpha);
    float phi = (6.28318530718 * random_v);
    float cosine = sqrt(((1.0 - random_u) / max((1.0 + ((alpha_squared - 1.0) * random_u)), 1e-06)));
    float sine = sqrt(max(0.0, (1.0 - (cosine * cosine))));
    vec3 tangent = normalize(((abs(normal.z) < 0.999) ? cross(normal, vec3(0.0, 0.0, 1.0)) : cross(normal, vec3(0.0, 1.0, 0.0))));
    vec3 bitangent = cross(normal, tangent);
    return normalize(((((tangent * sine) * cos(phi)) + ((bitangent * sine) * sin(phi))) + (normal * cosine)));
}

vec3 ordinarylight_pbr_cosine_hemisphere(vec3 normal, float random_u, float random_v);
vec3 ordinarylight_pbr_evaluate(vec3 base_color, float roughness, float metallic, vec3 normal, vec3 view, vec3 outgoing);
float ordinarylight_pbr_pdf(vec3 base_color, float roughness, float metallic, vec3 normal, vec3 view, vec3 outgoing);
vec3 ordinarylight_pbr_reflect(vec3 incoming, vec3 half_vector);
vec3 ordinarylight_pbr_sample_half_vector(vec3 normal, float roughness, float random_u, float random_v);
float ordinarylight_pbr_specular_probability(vec3 base_color, float metallic);
vec3 ordinarylight_pbr_weight(vec3 evaluated, float metallic, float occlusion, vec3 normal, vec3 view, vec3 outgoing, float pdf);
float randomFloat(inout uint state);
void samplePbr(MaterialData material, vec3 normal, vec3 incoming, inout uint rng, out vec3 outgoing, out vec3 weight, out float pdf, out float sampled_specular)
{
    vec3 view = (-incoming);
    float probability = ordinarylight_pbr_specular_probability(material.base_roughness.rgb, material.emission_metallic.a);
    bool specular = (randomFloat(rng) < probability);
    sampled_specular = (specular ? 1.0 : 0.0);
    float random_u = randomFloat(rng);
    float random_v = randomFloat(rng);
    outgoing = ordinarylight_pbr_cosine_hemisphere(normal, random_u, random_v);
    if (specular)
    {
        vec3 half_vector = ordinarylight_pbr_sample_half_vector(normal, material.base_roughness.a, random_u, random_v);
        outgoing = ordinarylight_pbr_reflect(incoming, half_vector);
    }
    if ((dot(normal, outgoing) <= 0.0))
    {
        outgoing = ordinarylight_pbr_cosine_hemisphere(normal, randomFloat(rng), randomFloat(rng));
    }
    outgoing = normalize(outgoing);
    pdf = max(ordinarylight_pbr_pdf(material.base_roughness.rgb, material.base_roughness.a, material.emission_metallic.a, normal, view, outgoing), 1e-06);
    vec3 evaluated = ordinarylight_pbr_evaluate(material.base_roughness.rgb, material.base_roughness.a, material.emission_metallic.a, normal, view, outgoing);
    vec3 half_vector = normalize((view + outgoing));
    float view_half = max(dot(view, half_vector), 0.0);
    vec3 f0 = mix(vec3(0.04), material.base_roughness.rgb, material.emission_metallic.a);
    vec3 fresnel = (f0 + ((vec3(1.0) - f0) * pow((1.0 - clamp(view_half, 0.0, 1.0)), 5.0)));
    vec3 diffuse = ((((vec3(1.0) - fresnel) * (1.0 - material.emission_metallic.a)) * material.base_roughness.rgb) / 3.14159265359);
    transportLastSpecularFraction = clamp(((evaluated - diffuse) / max(evaluated, vec3(1e-30))), vec3(0.0), vec3(1.0));
    weight = ordinarylight_pbr_weight(evaluated, material.emission_metallic.a, material.texture_parameters.w, normal, view, outgoing, pdf);
}

vec3 evaluatePbr(MaterialData material, vec3 normal, vec3 view, vec3 outgoing);
float ordinarylight_analytic_light_attenuation(int light_type, float distance_squared, vec3 direction, vec3 light_direction, float spot_inner, float spot_outer);
vec3 ordinarylight_analytic_light_contribution(vec3 evaluated_pbr, vec3 incident, float cosine);
float ordinarylight_analytic_light_cosine(vec3 normal, vec3 direction);
vec3 ordinarylight_analytic_light_direction(int light_type, vec3 light_position, vec3 light_direction, vec3 hit);
float ordinarylight_analytic_light_distance_squared(int light_type, vec3 light_position, vec3 hit);
vec3 ordinarylight_analytic_light_incident(vec3 color, float intensity, float attenuation, float transmittance);
float ordinarylight_analytic_light_shadow_distance(int light_type, float distance_to_light);
void profileWork(uint counter, uint amount);
float volumeShadowTransmittance(vec3 origin, vec3 direction, float maximum_distance);
vec3 samplePointLights(vec3 hit, vec3 normal, vec3 incoming, MaterialData material)
{
    vec3 direct = vec3(0.0);
    transportPointSpecular = vec3(0.0);
    uint index = uint(0);
    while ((index < min(OL_TRANSPORT_POINT_LIGHT_COUNT, uint(64))))
    {
        PointLightData light = point_lights[index];
        int light_type = int((light.position_type.w + 0.5));
        if ((light_type == 3))
        {
            index = (index + 1);
            continue;
        }
        float distance_squared = ordinarylight_analytic_light_distance_squared(light_type, light.position_type.xyz, hit);
        float distance_to_light = ((light_type == 1) ? 10000.0 : sqrt(distance_squared));
        vec3 direction = ordinarylight_analytic_light_direction(light_type, light.position_type.xyz, light.direction_range.xyz, hit);
        if ((((light_type != 1) && (light.direction_range.w > 0.0)) && (distance_to_light > light.direction_range.w)))
        {
            index = (index + 1);
            continue;
        }
        float attenuation = ordinarylight_analytic_light_attenuation(light_type, distance_squared, direction, light.direction_range.xyz, light.spot_parameters.x, light.spot_parameters.y);
        if ((attenuation <= 0.0))
        {
            index = (index + 1);
            continue;
        }
        float cosine = ordinarylight_analytic_light_cosine(normal, direction);
        if ((cosine <= 0.0))
        {
            index = (index + 1);
            continue;
        }
        vec3 shadow_origin = OL_TRANSPORT_RAY_ORIGIN(hit, normal);
        float shadow_distance = ordinarylight_analytic_light_shadow_distance(light_type, distance_to_light);
        rayQueryEXT shadow;
#if WAVE_WORK_COUNTERS
        profileWork(uint(1), uint(1));
#endif
        rayQueryInitializeEXT(shadow, scene_tlas, (gl_RayFlagsOpaqueEXT | gl_RayFlagsTerminateOnFirstHitEXT), 1, shadow_origin, 0.001, direction, shadow_distance);
        while (rayQueryProceedEXT(shadow))
        {
        }
        if ((rayQueryGetIntersectionTypeEXT(shadow, true) != gl_RayQueryCommittedIntersectionNoneEXT))
        {
            index = (index + 1);
            continue;
        }
        vec3 incident = ordinarylight_analytic_light_incident(light.color_intensity.rgb, light.color_intensity.a, attenuation, volumeShadowTransmittance(shadow_origin, direction, shadow_distance));
        vec3 contribution = ordinarylight_analytic_light_contribution(evaluatePbr(material, normal, (-incoming), direction), incident, cosine);
        direct = (direct + contribution);
        transportPointSpecular = (transportPointSpecular + (contribution * transportLastSpecularFraction));
        index = (index + 1);
    }
    return direct;
}

vec3 evaluatePbr(MaterialData material, vec3 normal, vec3 view, vec3 outgoing);
vec3 ordinarylight_area_light_contribution(vec3 evaluated_pbr, vec3 emission, float surface_cosine, float mis, float transmittance, float effective_pdf);
float ordinarylight_area_light_cosine(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec3 direction, bool two_sided);
float ordinarylight_area_light_mis(float effective_pdf, float sample_count, float bsdf_pdf);
float ordinarylight_area_light_pdf(float selection_pdf, float distance_squared, float light_cosine, float area, float technique_probability);
vec3 ordinarylight_area_light_position(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, float root_u, float value_v);
float pbrPdf(MaterialData material, vec3 normal, vec3 view, vec3 outgoing);
void profileWork(uint counter, uint amount);
float randomFloat(inout uint state);
float volumeShadowTransmittance(vec3 origin, vec3 direction, float maximum_distance);
vec3 sampleAreaLightTechnique(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count, float technique_probability)
{
    if ((OL_TRANSPORT_AREA_LIGHT_COUNT == uint(0)))
    {
        return vec3(0.0);
    }
    float selection = ((float(sample_index) + randomFloat(rng)) / float(sample_count));
    uint lower = uint(0);
    uint upper = (OL_TRANSPORT_AREA_LIGHT_COUNT - uint(1));
    uint step = uint(0);
    while (((step < uint(32)) && (lower < upper)))
    {
        uint middle = (lower + ((upper - lower) / uint(2)));
        if ((selection <= area_lights[middle].distribution.x))
        {
            upper = middle;
        }
        else
        {
            lower = (middle + uint(1));
        }
        step = (step + 1);
    }
    AreaLightData light = area_lights[lower];
    float root_u = sqrt(randomFloat(rng));
    float v = randomFloat(rng);
    vec3 light_position = ordinarylight_area_light_position(light.a.xyz, light.b.xyz, light.c.xyz, root_u, v);
    vec3 offset = (light_position - hit);
    float distance_squared = dot(offset, offset);
    float distance_to_light = sqrt(distance_squared);
    vec3 direction = (offset / max(distance_to_light, 1e-06));
    float surface_cosine = max(dot(normal, direction), 0.0);
    float light_cosine = ordinarylight_area_light_cosine(light.a.xyz, light.b.xyz, light.c.xyz, direction, (light.distribution.z > 0.5));
    if (((surface_cosine <= 0.0) || (light_cosine <= 1e-06)))
    {
        return vec3(0.0);
    }
    vec3 shadow_origin = OL_TRANSPORT_RAY_ORIGIN(hit, normal);
    float shadow_distance = max((distance_to_light - 0.004), 0.001);
    rayQueryEXT shadow;
#if WAVE_WORK_COUNTERS
    profileWork(uint(1), uint(1));
#endif
    rayQueryInitializeEXT(shadow, scene_tlas, (gl_RayFlagsOpaqueEXT | gl_RayFlagsTerminateOnFirstHitEXT), 1, shadow_origin, 0.001, direction, shadow_distance);
    while (rayQueryProceedEXT(shadow))
    {
    }
    if ((rayQueryGetIntersectionTypeEXT(shadow, true) != gl_RayQueryCommittedIntersectionNoneEXT))
    {
        return vec3(0.0);
    }
    float effective_pdf = ordinarylight_area_light_pdf(light.distribution.y, distance_squared, light_cosine, light.emission_area.a, technique_probability);
    float bsdf_pdf = pbrPdf(material, normal, (-incoming), direction);
    float mis = ordinarylight_area_light_mis(effective_pdf, float(sample_count), bsdf_pdf);
    float transmittance = volumeShadowTransmittance(shadow_origin, direction, shadow_distance);
    return ordinarylight_area_light_contribution(evaluatePbr(material, normal, (-incoming), direction), light.emission_area.rgb, surface_cosine, mis, transmittance, effective_pdf);
}

vec3 sampleAreaLightTechnique(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count, float technique_probability);
vec3 sampleAreaLight(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count)
{
    return sampleAreaLightTechnique(hit, normal, incoming, material, rng, sample_index, sample_count, 1.0);
}

struct AreaLightCandidate {
    uint light_index;
    vec2 barycentrics;
    float target;
};

const uint ENVIRONMENT_LIGHT_CANDIDATE_INDEX = 0x01fffffeu;

float ordinarylight_unified_area_probability(uint area_light_count, uint environment_samples, float area_light_weight);
float unifiedAreaDomainProbability()
{
    return ordinarylight_unified_area_probability(OL_TRANSPORT_AREA_LIGHT_COUNT, OL_TRANSPORT_ENVIRONMENT_SAMPLES, OL_TRANSPORT_AREA_LIGHT_WEIGHT);
}

vec3 evaluatePbr(MaterialData material, vec3 normal, vec3 view, vec3 outgoing);
vec3 ordinarylight_area_light_barycentric_position(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec2 barycentrics);
vec3 ordinarylight_area_light_contribution(vec3 evaluated_pbr, vec3 emission, float surface_cosine, float mis, float transmittance, float effective_pdf);
float ordinarylight_area_light_cosine(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec3 direction, bool two_sided);
float ordinarylight_area_light_mis(float effective_pdf, float sample_count, float bsdf_pdf);
float ordinarylight_area_light_pdf(float selection_pdf, float distance_squared, float light_cosine, float area, float technique_probability);
float pbrPdf(MaterialData material, vec3 normal, vec3 view, vec3 outgoing);
vec3 evaluateAreaLightCandidateTechnique(AreaLightCandidate candidate, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, float technique_probability, out vec3 direction, out float distance_to_light)
{
    if ((candidate.light_index >= OL_TRANSPORT_AREA_LIGHT_COUNT))
    {
        direction = normal;
        distance_to_light = 0.0;
        return vec3(0.0);
    }
    AreaLightData light = area_lights[candidate.light_index];
    vec3 light_position = ordinarylight_area_light_barycentric_position(light.a.xyz, light.b.xyz, light.c.xyz, candidate.barycentrics);
    vec3 offset = (light_position - hit);
    float distance_squared = dot(offset, offset);
    distance_to_light = sqrt(distance_squared);
    direction = (offset / max(distance_to_light, 1e-06));
    float surface_cosine = max(dot(normal, direction), 0.0);
    float light_cosine = ordinarylight_area_light_cosine(light.a.xyz, light.b.xyz, light.c.xyz, direction, (light.distribution.z > 0.5));
    if (((surface_cosine <= 0.0) || (light_cosine <= 1e-06)))
    {
        return vec3(0.0);
    }
    float effective_pdf = ordinarylight_area_light_pdf(light.distribution.y, distance_squared, light_cosine, light.emission_area.a, technique_probability);
    float bsdf_pdf = pbrPdf(material, normal, (-incoming), direction);
    float mis = ordinarylight_area_light_mis(effective_pdf, float(sample_count), bsdf_pdf);
    return ordinarylight_area_light_contribution(evaluatePbr(material, normal, (-incoming), direction), light.emission_area.rgb, surface_cosine, mis, 1.0, effective_pdf);
}

vec3 evaluateAreaLightCandidateTechnique(AreaLightCandidate candidate, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, float technique_probability, out vec3 direction, out float distance_to_light);
vec3 evaluateAreaLightCandidate(AreaLightCandidate candidate, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, out vec3 direction, out float distance_to_light)
{
    return evaluateAreaLightCandidateTechnique(candidate, hit, normal, incoming, material, sample_count, 1.0, direction, distance_to_light);
}

vec3 evaluateAreaLightCandidate(AreaLightCandidate candidate, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, out vec3 direction, out float distance_to_light);
float ordinarylight_light_candidate_target(vec3 contribution);
float randomFloat(inout uint state);
AreaLightCandidate generateAreaLightCandidate(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count)
{
    AreaLightCandidate candidate = AreaLightCandidate(uint(0), vec2(0), float(0.0));
    candidate.light_index = uint(4294967295);
    candidate.barycentrics = vec2(0.0);
    candidate.target = 0.0;
    if ((OL_TRANSPORT_AREA_LIGHT_COUNT == uint(0)))
    {
        return candidate;
    }
    float selection = ((float(sample_index) + randomFloat(rng)) / float(sample_count));
    uint lower = uint(0);
    uint upper = (OL_TRANSPORT_AREA_LIGHT_COUNT - uint(1));
    uint step = uint(0);
    while (((step < uint(32)) && (lower < upper)))
    {
        uint middle = (lower + ((upper - lower) / uint(2)));
        if ((selection <= area_lights[middle].distribution.x))
        {
            upper = middle;
        }
        else
        {
            lower = (middle + uint(1));
        }
        step = (step + 1);
    }
    float root_u = sqrt(randomFloat(rng));
    float v = randomFloat(rng);
    candidate.light_index = lower;
    candidate.barycentrics = vec2((root_u * (1.0 - v)), (root_u * v));
    vec3 unused_direction = vec3(0);
    float unused_distance = float(0.0);
    vec3 contribution = evaluateAreaLightCandidate(candidate, hit, normal, incoming, material, sample_count, unused_direction, unused_distance);
    candidate.target = ordinarylight_light_candidate_target(contribution);
    return candidate;
}

void profileWork(uint counter, uint amount);
float volumeShadowTransmittance(vec3 origin, vec3 direction, float maximum_distance);
float areaLightCandidateVisibility(vec3 hit, vec3 normal, vec3 direction, float distance_to_light)
{
    if ((distance_to_light <= 0.0))
    {
        return 0.0;
    }
    vec3 shadow_origin = OL_TRANSPORT_RAY_ORIGIN(hit, normal);
    float shadow_distance = max((distance_to_light - 0.004), 0.001);
    rayQueryEXT shadow;
#if WAVE_WORK_COUNTERS
    profileWork(uint(1), uint(1));
#endif
    rayQueryInitializeEXT(shadow, scene_tlas, (gl_RayFlagsOpaqueEXT | gl_RayFlagsTerminateOnFirstHitEXT), 1, shadow_origin, 0.001, direction, shadow_distance);
    while (rayQueryProceedEXT(shadow))
    {
    }
    if ((rayQueryGetIntersectionTypeEXT(shadow, true) != gl_RayQueryCommittedIntersectionNoneEXT))
    {
        return 0.0;
    }
    return volumeShadowTransmittance(shadow_origin, direction, shadow_distance);
}

vec3 ordinarylight_environment_analytic(vec3 direction);
vec3 ordinarylight_environment_radiance(vec3 encoded, float exposure, vec3 color, float intensity, bool textured);
vec2 ordinarylight_environment_uv(vec3 direction, float rotation);
vec4 sampleSceneTexture(int texture_index, vec2 uv);
vec3 environmentColor(vec3 direction)
{
    uint index = uint(0);
    while ((index < min(OL_TRANSPORT_POINT_LIGHT_COUNT, uint(64))))
    {
        PointLightData light = point_lights[index];
        if ((int((light.position_type.w + 0.5)) != 3))
        {
            index = (index + 1);
            continue;
        }
        vec3 radiance = vec3(1.0);
        int texture_index = ((light.spot_parameters.x < 0.0) ? (-1) : int((light.spot_parameters.x + 0.5)));
        if ((texture_index >= 0))
        {
            vec2 uv = ordinarylight_environment_uv(direction, light.spot_parameters.y);
            vec3 encoded = sampleSceneTexture(texture_index, uv).rgb;
            radiance = ordinarylight_environment_radiance(encoded, light.spot_parameters.z, vec3(1.0), 1.0, true);
        }
        return ordinarylight_environment_radiance(radiance, 0.0, light.color_intensity.rgb, light.color_intensity.a, false);
        index = (index + 1);
    }
    return ordinarylight_environment_analytic(direction);
}

vec3 environmentColor(vec3 direction);
vec3 evaluatePbr(MaterialData material, vec3 normal, vec3 view, vec3 outgoing);
float ordinarylight_analytic_light_cosine(vec3 normal, vec3 direction);
vec3 ordinarylight_environment_contribution(vec3 evaluated_pbr, vec3 radiance, float cosine, float mis, float transmittance, float effective_pdf, float occlusion, float metallic);
float ordinarylight_environment_effective_pdf(float cosine, float technique_probability);
float ordinarylight_environment_mis(float cosine, float effective_pdf, float sample_count);
vec3 ordinarylight_pbr_cosine_hemisphere(vec3 normal, float random_u, float random_v);
void profileWork(uint counter, uint amount);
float randomFloat(inout uint state);
float volumeShadowTransmittance(vec3 origin, vec3 direction, float maximum_distance);
vec3 sampleEnvironmentTechnique(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_count, float technique_probability)
{
    vec3 direction = ordinarylight_pbr_cosine_hemisphere(normal, randomFloat(rng), randomFloat(rng));
    vec3 shadow_origin = OL_TRANSPORT_RAY_ORIGIN(hit, normal);
    rayQueryEXT shadow;
#if WAVE_WORK_COUNTERS
    profileWork(uint(1), uint(1));
#endif
    rayQueryInitializeEXT(shadow, scene_tlas, (gl_RayFlagsOpaqueEXT | gl_RayFlagsTerminateOnFirstHitEXT), 1, shadow_origin, 0.001, direction, 1e+30);
    while (rayQueryProceedEXT(shadow))
    {
    }
    if ((rayQueryGetIntersectionTypeEXT(shadow, true) != gl_RayQueryCommittedIntersectionNoneEXT))
    {
        return vec3(0.0);
    }
    float cosine = ordinarylight_analytic_light_cosine(normal, direction);
    float pdf = (cosine / 3.14159265359);
    float effective_pdf = ordinarylight_environment_effective_pdf(cosine, technique_probability);
    float mis = ordinarylight_environment_mis(cosine, effective_pdf, float(sample_count));
    float transmittance = volumeShadowTransmittance(shadow_origin, direction, 1e+30);
    return ordinarylight_environment_contribution(evaluatePbr(material, normal, (-incoming), direction), environmentColor(direction), cosine, mis, transmittance, effective_pdf, material.texture_parameters.w, material.emission_metallic.a);
}

vec3 sampleEnvironmentTechnique(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_count, float technique_probability);
vec3 sampleEnvironment(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_count)
{
    return sampleEnvironmentTechnique(hit, normal, incoming, material, rng, sample_count, 1.0);
}

float ordinarylight_unified_secondary_area_probability(bool area_enabled, bool environment_enabled, float area_light_weight, uint secondary_area_samples, uint environment_samples);
float randomFloat(inout uint state);
vec3 sampleAreaLightTechnique(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count, float technique_probability);
vec3 sampleEnvironmentTechnique(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_count, float technique_probability);
vec3 sampleUnifiedSecondaryLight(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng)
{
    bool area_enabled = (OL_TRANSPORT_AREA_LIGHT_COUNT > uint(0));
    bool environment_enabled = (OL_TRANSPORT_ENVIRONMENT_SAMPLES > uint(0));
    if (((!area_enabled) && (!environment_enabled)))
    {
        return vec3(0.0);
    }
    float area_probability = ordinarylight_unified_secondary_area_probability(area_enabled, environment_enabled, OL_TRANSPORT_AREA_LIGHT_WEIGHT, OL_TRANSPORT_SECONDARY_AREA_LIGHT_SAMPLES, OL_TRANSPORT_ENVIRONMENT_SAMPLES);
    if ((randomFloat(rng) < area_probability))
    {
        return sampleAreaLightTechnique(hit, normal, incoming, material, rng, uint(0), uint(1), area_probability);
    }
    return sampleEnvironmentTechnique(hit, normal, incoming, material, rng, uint(1), (1.0 - area_probability));
}

vec2 ordinarylight_environment_encode_direction(vec3 direction_input);
vec2 encodeEnvironmentCandidateDirection(vec3 direction)
{
    return ordinarylight_environment_encode_direction(direction);
}

vec3 ordinarylight_environment_decode_direction(vec2 encoded);
vec3 decodeEnvironmentCandidateDirection(vec2 encoded)
{
    return ordinarylight_environment_decode_direction(encoded);
}

vec3 decodeEnvironmentCandidateDirection(vec2 encoded);
vec3 environmentColor(vec3 direction);
vec3 evaluatePbr(MaterialData material, vec3 normal, vec3 view, vec3 outgoing);
vec3 ordinarylight_environment_contribution(vec3 evaluated_pbr, vec3 radiance, float cosine, float mis, float transmittance, float effective_pdf, float occlusion, float metallic);
float ordinarylight_environment_effective_pdf(float cosine, float technique_probability);
float ordinarylight_environment_mis(float cosine, float effective_pdf, float sample_count);
vec3 evaluateEnvironmentCandidate(vec2 encoded_direction, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, float technique_probability, out vec3 direction, out float distance_to_light)
{
    direction = decodeEnvironmentCandidateDirection(encoded_direction);
    distance_to_light = 1e+30;
    float cosine = max(dot(normal, direction), 0.0);
    if ((cosine <= 0.0))
    {
        return vec3(0.0);
    }
    float pdf = (cosine / 3.14159265359);
    float effective_pdf = ordinarylight_environment_effective_pdf(cosine, technique_probability);
    float mis = ordinarylight_environment_mis(cosine, effective_pdf, float(sample_count));
    return ordinarylight_environment_contribution(evaluatePbr(material, normal, (-incoming), direction), environmentColor(direction), cosine, mis, 1.0, effective_pdf, material.texture_parameters.w, material.emission_metallic.a);
}

vec3 cosineHemisphere(vec3 normal, float random_u, float random_v);
vec2 encodeEnvironmentCandidateDirection(vec3 direction);
vec3 evaluateAreaLightCandidateTechnique(AreaLightCandidate candidate, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, float technique_probability, out vec3 direction, out float distance_to_light);
vec3 evaluateEnvironmentCandidate(vec2 encoded_direction, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, float technique_probability, out vec3 direction, out float distance_to_light);
AreaLightCandidate generateAreaLightCandidate(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count);
float ordinarylight_light_candidate_target(vec3 contribution);
float randomFloat(inout uint state);
float unifiedAreaDomainProbability();
AreaLightCandidate generateUnifiedPrimaryCandidate(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count)
{
    float area_probability = unifiedAreaDomainProbability();
    if (((OL_TRANSPORT_ENVIRONMENT_SAMPLES == uint(0)) || (randomFloat(rng) < area_probability)))
    {
        AreaLightCandidate candidate = generateAreaLightCandidate(hit, normal, incoming, material, rng, sample_index, sample_count);
        vec3 unused_direction = vec3(0);
        float unused_distance = float(0.0);
        vec3 contribution = evaluateAreaLightCandidateTechnique(candidate, hit, normal, incoming, material, sample_count, area_probability, unused_direction, unused_distance);
        candidate.target = ordinarylight_light_candidate_target(contribution);
        return candidate;
    }
    AreaLightCandidate candidate = AreaLightCandidate(uint(0), vec2(0), float(0.0));
    vec3 direction = cosineHemisphere(normal, randomFloat(rng), randomFloat(rng));
    candidate.light_index = ENVIRONMENT_LIGHT_CANDIDATE_INDEX;
    candidate.barycentrics = encodeEnvironmentCandidateDirection(direction);
    float unused_distance = float(0.0);
    vec3 contribution = evaluateEnvironmentCandidate(candidate.barycentrics, hit, normal, incoming, material, sample_count, (1.0 - area_probability), direction, unused_distance);
    candidate.target = ordinarylight_light_candidate_target(contribution);
    return candidate;
}

vec3 evaluateAreaLightCandidateTechnique(AreaLightCandidate candidate, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, float technique_probability, out vec3 direction, out float distance_to_light);
vec3 evaluateEnvironmentCandidate(vec2 encoded_direction, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, float technique_probability, out vec3 direction, out float distance_to_light);
float unifiedAreaDomainProbability();
vec3 evaluateUnifiedPrimaryCandidate(AreaLightCandidate candidate, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, out vec3 direction, out float distance_to_light)
{
    float area_probability = unifiedAreaDomainProbability();
    if ((candidate.light_index == ENVIRONMENT_LIGHT_CANDIDATE_INDEX))
    {
        return evaluateEnvironmentCandidate(candidate.barycentrics, hit, normal, incoming, material, sample_count, (1.0 - area_probability), direction, distance_to_light);
    }
    return evaluateAreaLightCandidateTechnique(candidate, hit, normal, incoming, material, sample_count, area_probability, direction, distance_to_light);
}

#endif
