// Generated by scripts/generate_transport_shaders.py using OrdinaryShade.
// Edit ordinarylight/shaders/transport_programs.py.
#ifndef ORDINARYLIGHT_GENERATED_TRANSPORT_MATERIAL_CONTRACTS
#define ORDINARYLIGHT_GENERATED_TRANSPORT_MATERIAL_CONTRACTS 1
struct MaterialEvaluation
{
    vec3 base_color;
    vec3 emission;
    float metallic;
    float roughness;
    float transmission;
    float ior;
    vec3 attenuation_color;
    float attenuation_distance;
    float custom_scattering;
    vec3 weight;
    vec3 next_direction;
    float event;
    float pdf;
};
#endif
