// Generated by scripts/generate_transport_kernels.py using OrdinaryShade.
#version 460
layout(local_size_x=64) in;
struct SampleAccumulation { vec4 radiance; uvec4 counts; uvec4 events; };
layout(set=0,binding=0,std430) readonly buffer Scratch { SampleAccumulation contributions[]; };
layout(set=0,binding=1,std430) buffer Output { SampleAccumulation accumulated[]; };
layout(set=0,binding=2,std430) readonly buffer Groups { uvec4 groups[]; };
layout(set=0,binding=3,std430) readonly buffer Indices { uint indices[]; };
layout(set=0,binding=4,std430) readonly buffer Weights { vec2 weights[]; };
layout(push_constant) uniform Constants { uint group_count; } pc;
#ifdef OL_GPU_REDUCTION
layout(set=0,binding=5,std430) readonly buffer GpuControl { uvec4 gpu_control; };
#endif
void main()
{
    uint i = gl_GlobalInvocationID.x;
#if defined(OL_GPU_REDUCTION)
    if (((gpu_control.z != uint(0)) || (i >= min(pc.group_count, gpu_control.y))))
    {
        return;
    }
#else
    if ((i >= pc.group_count))
    {
        return;
    }
#endif
    uvec4 group = groups[i];
    SampleAccumulation result = accumulated[group.x];
    uint j = uint(0);
    while ((j < group.z))
    {
        SampleAccumulation value = contributions[indices[(group.y + j)]];
        vec2 weight = weights[indices[(group.y + j)]];
        result.radiance.rgb = (result.radiance.rgb + (value.radiance.rgb * weight.x));
        result.radiance.w = (result.radiance.w + (float(value.counts.y) * weight.y));
        result.counts.xy = (result.counts.xy + value.counts.xy);
        result.counts.z = (result.counts.z | value.counts.z);
        result.counts.w = (result.counts.w + value.counts.w);
        result.events = (result.events + value.events);
        j = (j + 1);
    }
    if ((any(isnan(result.radiance)) || any(isinf(result.radiance))))
    {
        result.counts.z = (result.counts.z | uint(16));
    }
    accumulated[group.x] = result;
}
