// Generated by scripts/generate_sampling_shaders.py using OrdinaryShade.
#ifndef ORDINARYLIGHT_SAMPLING_V1
#define ORDINARYLIGHT_SAMPLING_V1 1



float randomFloat(inout uint state);
uint secondaryNeeHash(uint value);
bool selectSecondaryNee(float probability, uint pixel_index, uint frame_sample, uint bounce);
vec3 cosineHemisphere(vec3 normal, float random_u, float random_v);
float powerHeuristic(float first_pdf, float second_pdf);
vec3 pbrFresnel(vec3 f0, float cosine);
float ggxDistribution(float n_dot_h, float roughness);
float ggxSmithComponent(float n_dot_direction, float roughness);

float randomFloat(inout uint state)
{
    state = ((state * uint(747796405)) + uint(2891336453));
    uint word = (((state >> ((state >> uint(28)) + uint(4))) ^ state) * uint(277803737));
    word = ((word >> uint(22)) ^ word);
    return (float(word) * (1.0 / 4294967296.0));
}

uint secondaryNeeHash(uint value)
{
    value = (value ^ (value >> uint(16)));
    value = (value * uint(2146121005));
    value = (value ^ (value >> uint(15)));
    value = (value * uint(2221713035));
    return (value ^ (value >> uint(16)));
}

bool selectSecondaryNee(float probability, uint pixel_index, uint frame_sample, uint bounce)
{
    if ((probability >= 0.999999))
    {
        return true;
    }
    uint frame_index = (frame_sample >> uint(8));
    uint sample_index = (frame_sample & uint(255));
    uint scramble = secondaryNeeHash(((pixel_index ^ secondaryNeeHash((bounce + uint(1)))) ^ secondaryNeeHash((sample_index + uint(1)))));
    uint sequence = (bitfieldReverse(frame_index) ^ scramble);
    float selector = ((float(sequence) + 0.5) * (1.0 / 4294967296.0));
    return (selector < probability);
}

vec3 cosineHemisphere(vec3 normal, float random_u, float random_v)
{
    float radius = sqrt(random_u);
    float phi = (6.28318530718 * random_v);
    vec3 tangent = normalize(((abs(normal.z) < 0.999) ? cross(normal, vec3(0.0, 0.0, 1.0)) : cross(normal, vec3(0.0, 1.0, 0.0))));
    vec3 bitangent = cross(normal, tangent);
    return normalize(((((tangent * radius) * cos(phi)) + ((bitangent * radius) * sin(phi))) + (normal * sqrt(max(0.0, (1.0 - random_u))))));
}

float powerHeuristic(float first_pdf, float second_pdf)
{
    float a = (first_pdf * first_pdf);
    float b = (second_pdf * second_pdf);
    return (a / max((a + b), 1e-06));
}

vec3 pbrFresnel(vec3 f0, float cosine)
{
    return (f0 + ((vec3(1.0) - f0) * pow((1.0 - clamp(cosine, 0.0, 1.0)), 5.0)));
}

float ggxDistribution(float n_dot_h, float roughness)
{
    float alpha = max((roughness * roughness), 0.0009);
    float alpha_squared = (alpha * alpha);
    float denominator = (((n_dot_h * n_dot_h) * (alpha_squared - 1.0)) + 1.0);
    return (alpha_squared / max(((3.14159265359 * denominator) * denominator), 1e-06));
}

float ggxSmithComponent(float n_dot_direction, float roughness)
{
    float alpha = max((roughness * roughness), 0.0009);
    float alpha_squared = (alpha * alpha);
    return ((2.0 * n_dot_direction) / max((n_dot_direction + sqrt((alpha_squared + (((1.0 - alpha_squared) * n_dot_direction) * n_dot_direction)))), 1e-06));
}

#endif
