// Generated by scripts/generate_transport_shaders.py using OrdinaryShade.
// Edit ordinarylight/shaders/transport_programs.py.
#ifndef ORDINARYLIGHT_GENERATED_TRANSPORT_SDF_SPHERE
#define ORDINARYLIGHT_GENERATED_TRANSPORT_SDF_SPHERE 1
uint ordinarylightSdfSphere(vec3 origin, vec3 direction, float t_min, float t_max, vec4 parameters, float tolerance, uint max_steps, out float distance, out vec3 geometric_normal)
{
    distance = t_min;
    vec3 start_delta = ((origin + (distance * direction)) - parameters.xyz);
    float start_value = (length(start_delta) - parameters.w);
    float origin_value = (length((origin - parameters.xyz)) - parameters.w);
    bool leaving_origin_root = (((abs(origin_value) <= tolerance) && (abs(start_value) <= tolerance)) && ((start_value * dot(start_delta, direction)) > 0.0));
    uint step = uint(0);
    while ((step < max_steps))
    {
        vec3 delta = ((origin + (distance * direction)) - parameters.xyz);
        float value = (length(delta) - parameters.w);
        if ((leaving_origin_root && (abs(value) > tolerance)))
        {
            leaving_origin_root = false;
        }
        if (((abs(value) <= tolerance) && (!leaving_origin_root)))
        {
            geometric_normal = normalize(delta);
            return uint(1);
        }
        distance = (distance + (leaving_origin_root ? max(abs(value), tolerance) : abs(value)));
        if ((distance > (t_max + tolerance)))
        {
            return uint(0);
        }
        step = (step + 1);
    }
    return uint(2);
}
#endif
