// Generated by scripts/generate_native_intersection.py using OrdinaryShade.
#ifndef ORDINARYLIGHT_NATIVE_INTERSECTION
#define ORDINARYLIGHT_NATIVE_INTERSECTION 1
struct NativeEmitterSample {
    vec3 position;
    vec3 normal;
    vec3 emission;
    float area_pdf;
    bool two_sided;
};
struct NativeOpticalBoundary {
    vec2 ior;
    bool enabled;
};
struct NativeIntersection {
    vec4 position_distance;
    vec4 geometric_normal;
    vec4 shading_normal;
    uvec4 identity;
    uvec4 address;
    vec4 texcoord;
    vec4 previous_position;
};
NativeIntersection nativeIntersectionMiss()
{
    return NativeIntersection(vec4(0.0, 0.0, 0.0, (-1.0)), vec4(0.0), vec4(0.0), uvec4(4294967295), uvec4(4294967295, 4294967295, 0, 0), vec4(0.0), vec4(0.0));
}
uint nativeSurfaceMask()
{
#if WAVE_CUSTOM_GEOMETRY
    return uint(3);
#endif
    return uint(1);
}
bool nativeBoundaryEnabled(NativeOpticalBoundary boundary)
{
    return (((boundary.enabled && all(greaterThan(boundary.ior, vec2(0.0)))) && (!any(isnan(boundary.ior)))) && (!any(isinf(boundary.ior))));
}
NativeIntersection nativeIntersectionMiss();
NativeIntersection nativeIntersectCandidate(vec3 origin, vec3 direction, float t_min, float t_max, uint primitive, uint instance, uint instance_offset);
NativeOpticalBoundary nativeEvaluateBoundary(NativeIntersection hit);
bool nativeBoundaryEnabled(NativeOpticalBoundary boundary);
NativeIntersection nativeTraceSurface(vec3 origin, float t_min, vec3 direction, float t_max, bool visibility, uint mask)
{
    NativeIntersection hit = nativeIntersectionMiss();
    NativeIntersection selected = hit;
    uint selected_primitive = uint(4294967295);
    uint selected_instance = uint(4294967295);
    uint flags = uint(1);
    if (visibility)
    {
        flags = (flags | uint(4));
    }
    rayQueryEXT query;
    rayQueryInitializeEXT(query, scene_tlas, flags, mask, origin, t_min, direction, t_max);
    while (rayQueryProceedEXT(query))
    {
#if WAVE_CUSTOM_GEOMETRY
        if ((rayQueryGetIntersectionTypeEXT(query, false) != uint(1)))
        {
            continue;
        }
        uint primitive = rayQueryGetIntersectionPrimitiveIndexEXT(query, false);
        uint instance = rayQueryGetIntersectionInstanceIdEXT(query, false);
        float limit = t_max;
        if ((rayQueryGetIntersectionTypeEXT(query, true) != uint(0)))
        {
            limit = min(limit, rayQueryGetIntersectionTEXT(query, true));
        }
        NativeIntersection candidate = nativeIntersectCandidate(origin, direction, t_min, limit, primitive, instance, rayQueryGetIntersectionInstanceCustomIndexEXT(query, false));
        float distance = candidate.position_distance.w;
        if (((distance < t_min) || (distance > limit)))
        {
            continue;
        }
        if ((isnan(distance) || isinf(distance)))
        {
            continue;
        }
        if (((any(isnan(candidate.geometric_normal.xyz)) || any(isinf(candidate.geometric_normal.xyz))) || (abs((dot(candidate.geometric_normal.xyz, candidate.geometric_normal.xyz) - 1.0)) > 0.001)))
        {
            continue;
        }
        if ((((any(isnan(candidate.shading_normal.xyz)) || any(isinf(candidate.shading_normal.xyz))) || (abs((dot(candidate.shading_normal.xyz, candidate.shading_normal.xyz) - 1.0)) > 0.001)) || (dot(candidate.shading_normal.xyz, candidate.geometric_normal.xyz) <= 0.0)))
        {
            continue;
        }
        candidate.position_distance = vec4((origin + (distance * direction)), distance);
        candidate.address = uvec4((primitive + rayQueryGetIntersectionInstanceCustomIndexEXT(query, false)), primitive, rayQueryGetIntersectionInstanceCustomIndexEXT(query, false), 2);
#if WAVE_NATIVE_OPTICAL_BOUNDARIES
        if (visibility)
        {
            NativeOpticalBoundary boundary = nativeEvaluateBoundary(candidate);
            if ((nativeBoundaryEnabled(boundary) && (boundary.ior.x == boundary.ior.y)))
            {
                continue;
            }
        }
#endif
        rayQueryGenerateIntersectionEXT(query, distance);
        if (((((rayQueryGetIntersectionTypeEXT(query, true) == uint(2)) && (rayQueryGetIntersectionPrimitiveIndexEXT(query, true) == primitive)) && (rayQueryGetIntersectionInstanceIdEXT(query, true) == instance)) && (rayQueryGetIntersectionTEXT(query, true) == distance)))
        {
            selected = candidate;
            selected_primitive = primitive;
            selected_instance = instance;
        }
#endif
    }
    uint kind = rayQueryGetIntersectionTypeEXT(query, true);
    if ((kind == uint(0)))
    {
        return hit;
    }
    float distance = rayQueryGetIntersectionTEXT(query, true);
    uint primitive = rayQueryGetIntersectionPrimitiveIndexEXT(query, true);
    uint instance = rayQueryGetIntersectionInstanceIdEXT(query, true);
    uint instance_offset = rayQueryGetIntersectionInstanceCustomIndexEXT(query, true);
    if ((kind == uint(2)))
    {
        if (((primitive != selected_primitive) || (instance != selected_instance)))
        {
            return hit;
        }
        hit = selected;
    }
    else
    {
        hit.identity = uvec4(instance, primitive, (primitive + instance_offset), 0);
        hit.texcoord.xy = rayQueryGetIntersectionBarycentricsEXT(query, true);
    }
    hit.position_distance = vec4((origin + (distance * direction)), distance);
    hit.address = uvec4((primitive + instance_offset), primitive, instance_offset, kind);
    return hit;
}
uint nativeEmitterCount();
uint nativeAreaLightCount(uint fallback)
{
#if WAVE_NATIVE_EMITTERS
    return min(nativeEmitterCount(), uint(33554430));
#endif
    return fallback;
}
bool nativeEmitterValid(NativeEmitterSample sample_)
{
    return (((((((((((sample_.area_pdf > 0.0) && (!isnan(sample_.area_pdf))) && (!isinf(sample_.area_pdf))) && (!any(isnan(sample_.position)))) && (!any(isinf(sample_.position)))) && (!any(isnan(sample_.normal)))) && (!any(isinf(sample_.normal)))) && (abs((dot(sample_.normal, sample_.normal) - 1.0)) < 0.001)) && (!any(isnan(sample_.emission)))) && (!any(isinf(sample_.emission)))) && all(greaterThanEqual(sample_.emission, vec3(0.0))));
}
#endif
