// Generated by scripts/generate_color_shaders.py using Ordinary Shade.
// The checked-in artifact keeps Ordinary Shade an optional development tool.
vec3 acesApproximation(vec3 color)
{
    return clamp(((color * ((2.51 * color) + 0.03)) / ((color * ((2.43 * color) + 0.59)) + 0.14)), vec3(0.0), vec3(1.0));
}
vec3 linearToSrgb(vec3 color)
{
    bvec3 low = lessThanEqual(color, vec3(0.0031308));
    vec3 lower = (color * 12.92);
    vec3 upper = ((1.055 * pow(color, vec3((1.0 / 2.4)))) - 0.055);
    return mix(upper, lower, low);
}
