// Generated by scripts/generate_primary_shaders.py using Ordinary Shade.
// Edit the typed Python source, not this generated GLSL.
#ifndef ORDINARYLIGHT_ORDINARYSHADE_PRIMARY_GLSL
#define ORDINARYLIGHT_ORDINARYSHADE_PRIMARY_GLSL 1
void ordinarylight_secondary_trace_query(vec3 origin, vec3 direction, inout bool surface_hit, inout float distance, inout uint primitive, inout vec2 barycentrics)
{
    rayQueryEXT query;
    rayQueryInitializeEXT(query, scene_tlas, uint(1), uint(1), origin, 0.001, direction, 1e+30);
    while (rayQueryProceedEXT(query))
    {
    }
    surface_hit = (rayQueryGetIntersectionTypeEXT(query, true) == uint(1));
    if (surface_hit)
    {
        distance = rayQueryGetIntersectionTEXT(query, true);
        primitive = (rayQueryGetIntersectionPrimitiveIndexEXT(query, true) + rayQueryGetIntersectionInstanceCustomIndexEXT(query, true));
        barycentrics = rayQueryGetIntersectionBarycentricsEXT(query, true);
    }
}
#if WAVE_SER
void ordinarylight_secondary_reorder(uint hint)
{
    reorderThreadNV(hint, uint(7));
}
#endif
#if WAVE_ORDINARYSHADE_SECONDARY_ORCHESTRATION
void integrateVolumesBeforeSurface(vec3 origin, vec3 direction, float distance, inout vec3 radiance, inout vec3 throughput);
void ordinarylight_integrate_secondary_volumes(vec3 origin, vec3 direction, float distance, inout vec3 radiance, inout vec3 throughput)
{
    integrateVolumesBeforeSurface(origin, direction, distance, radiance, throughput);
}
#endif
#if WAVE_ORDINARYSHADE_SECONDARY_ORCHESTRATION && WAVE_WORK_COUNTERS
void profileWork(uint counter, uint amount);
void ordinarylight_profile_work(uint counter, uint amount)
{
    profileWork(counter, amount);
}
#endif
#if WAVE_CUSTOM_MATERIAL_PROGRAM
MaterialEvaluation waveApplyMaterialProgram(inout MaterialData material, vec3 normal, vec2 uv, vec3 direction, bool entering, uint primitive, vec3 weights, float bounce_index);
MaterialEvaluation ordinarylight_apply_material_program(inout MaterialData material, vec3 normal, vec2 uv, vec3 direction, bool entering, uint primitive, vec3 weights, float bounce_index)
{
    return waveApplyMaterialProgram(material, normal, uv, direction, entering, primitive, weights, bounce_index);
}
#endif
#if WAVE_ORDINARYSHADE_SECONDARY_ORCHESTRATION && WAVE_PERSISTENT_COARSE
void processPrimaryPixel(uvec2 pixel);
shared uint persistent_tile_index;
void ordinarylight_persistent_coarse_schedule(uvec2 tile_extent)
{
    uvec2 tile_count = ((tile_extent + uvec2(7)) / uvec2(8));
    uint total_tiles = (tile_count.x * tile_count.y);
    while (true)
    {
        if ((gl_LocalInvocationIndex == uint(0)))
        {
            persistent_tile_index = atomicAdd(ordinarylight_output_queue.count, uint(1));
        }
        barrier();
        if ((persistent_tile_index >= total_tiles))
        {
            return;
        }
        uvec2 tile = uvec2((persistent_tile_index % tile_count.x), (persistent_tile_index / tile_count.x));
        processPrimaryPixel(((tile * uvec2(8)) + gl_LocalInvocationID.xy));
        barrier();
    }
}
#endif
#if WAVE_ORDINARYSHADE_SECONDARY_ORCHESTRATION
bool ordinarylightSecondaryBounce(inout WavePathState path, inout vec3 origin, inout vec3 direction, uint path_index, inout uint medium_depth, inout uint rng, inout float cone_width, inout float cone_spread);
void ordinarylight_trace_remaining(inout WavePathState path, inout vec3 origin, inout vec3 direction, uint path_index, inout uint medium_depth, inout uint rng, inout float cone_width, inout float cone_spread, uint stop_bounce)
{
    while ((uint(path.throughput.w) < stop_bounce))
    {
        if ((!ordinarylightSecondaryBounce(path, origin, direction, path_index, medium_depth, rng, cone_width, cone_spread)))
        {
            break;
        }
    }
    path.metadata.z = rng;
}
#endif
#if WAVE_ORDINARYSHADE_SECONDARY_ORCHESTRATION
void ordinarylight_store_path(uint path_index, WavePathState path)
{
    ordinarylight_paths[path_index] = path;
}
void ordinarylight_deactivate_stored_path(uint path_index)
{
    ordinarylight_paths[path_index].metadata.w = (ordinarylight_paths[path_index].metadata.w & (~uint(1)));
}
void ordinarylight_clear_secondary_path(uint path_index)
{
    ordinarylight_secondary_paths[path_index].position_valid = vec4(0.0);
    ordinarylight_secondary_paths[path_index].normal_pdf = vec4(0.0);
    ordinarylight_secondary_paths[path_index].primary_throughput = vec4(0.0);
    ordinarylight_secondary_paths[path_index].primary_radiance = vec4(0.0);
    ordinarylight_secondary_paths[path_index].diffuse_radiance_hit_distance = vec4(0.0);
    ordinarylight_secondary_paths[path_index].specular_radiance_hit_distance = vec4(0.0);
    ordinarylight_secondary_paths[path_index].primary_position = vec4(0.0);
    ordinarylight_secondary_paths[path_index].primary_geometry = vec4(0.0);
}
float ordinarylight_secondary_primary_valid(uint path_index)
{
    return ordinarylight_secondary_paths[path_index].primary_throughput.w;
}
void ordinarylight_store_secondary_hit(uint path_index, vec4 position_valid, vec3 normal)
{
    ordinarylight_secondary_paths[path_index].position_valid = position_valid;
    ordinarylight_secondary_paths[path_index].normal_pdf.xyz = normal;
}
void ordinarylight_store_secondary_primary(uint path_index, vec3 throughput, vec3 radiance, float pdf, float sampled_specular, float specular_probability, vec3 position, float roughness, uint primitive, vec2 barycentrics, uint instance_key)
{
    ordinarylight_secondary_paths[path_index].primary_throughput = vec4(throughput, (1.0 + sampled_specular));
    ordinarylight_secondary_paths[path_index].primary_radiance = vec4(radiance, specular_probability);
    ordinarylight_secondary_paths[path_index].normal_pdf.w = pdf;
    ordinarylight_secondary_paths[path_index].primary_position = vec4(position, (1.0 + clamp(roughness, 0.0, 1.0)));
    ordinarylight_secondary_paths[path_index].primary_geometry = vec4(uintBitsToFloat(primitive), barycentrics, uintBitsToFloat(instance_key));
}
#endif
#if WAVE_ORDINARYSHADE_SECONDARY_ORCHESTRATION
float ordinarylight_medium_ior(uint path_index, uint depth)
{
    return ordinarylight_medium_stacks[path_index].ior[depth];
}
void ordinarylight_set_medium_ior(uint path_index, uint depth, float value)
{
    ordinarylight_medium_stacks[path_index].ior[depth] = value;
}
#endif
uvec2 ordinarylight_primary_scheduled_group(uvec2 group_id, uvec2 group_count, uint swizzle_width)
{
    uvec2 scheduled = group_id;
    if ((swizzle_width > uint(1)))
    {
        uint full_tiles = (group_count.x / swizzle_width);
        uint full_tile_groups = ((full_tiles * swizzle_width) * group_count.y);
        uint linear_group = ((group_id.y * group_count.x) + group_id.x);
        if ((linear_group < full_tile_groups))
        {
            uint groups_per_tile = (swizzle_width * group_count.y);
            uint tile = (linear_group / groups_per_tile);
            uint local = (linear_group - (tile * groups_per_tile));
            scheduled = uvec2(((tile * swizzle_width) + (local % swizzle_width)), (local / swizzle_width));
        }
        else
        {
            uint tail_width = (group_count.x - (full_tiles * swizzle_width));
            uint local = (linear_group - full_tile_groups);
            scheduled = uvec2(((full_tiles * swizzle_width) + (local % tail_width)), (local / tail_width));
        }
    }
    return scheduled;
}
#if WAVE_ORDINARYSHADE_SECONDARY_ORCHESTRATION
uint ordinarylight_reserve_output_index(uint subgroup_enqueue)
{
    if ((subgroup_enqueue == uint(0)))
    {
        return atomicAdd(ordinarylight_output_queue_count, uint(1));
    }
    uvec4 active_lanes = subgroupBallot(true);
    uint base = uint(0);
    if (subgroupElect())
    {
        base = atomicAdd(ordinarylight_output_queue_count, subgroupBallotBitCount(active_lanes));
    }
    base = subgroupBroadcastFirst(base);
    return (base + subgroupBallotExclusiveBitCount(active_lanes));
}
#endif
#if WAVE_ORDINARYSHADE_SECONDARY_ORCHESTRATION
vec3 ordinarylight_secondary_vertex_position(uint primitive, uint corner)
{
    return ordinarylight_vertices[((primitive * uint(3)) + corner)].xyz;
}
VertexAttributeData ordinarylight_secondary_vertex_attribute(uint primitive, uint corner)
{
    return ordinarylight_attributes[((primitive * uint(3)) + corner)];
}
MaterialData ordinarylight_secondary_material(uint primitive)
{
    return ordinarylight_materials[primitive];
}
#endif
#if WAVE_ORDINARYSHADE_SECONDARY_ORCHESTRATION
bool ordinarylight_enqueue_continuation(uint output_index, vec4 origin_tmin, vec4 direction_tmax, uint path_index, float cone_width, float cone_spread)
{
    if ((output_index >= ordinarylight_output_queue.capacity))
    {
        atomicAdd(ordinarylight_output_queue.overflow, uint(1));
        return false;
    }
    ordinarylight_output_queue.rays[output_index].origin_tmin = origin_tmin;
    ordinarylight_output_queue.rays[output_index].direction_tmax = direction_tmax;
    ordinarylight_output_queue.rays[output_index].path_index = path_index;
    ordinarylight_output_queue.rays[output_index].padding_a = floatBitsToUint(cone_width);
    ordinarylight_output_queue.rays[output_index].padding_b = floatBitsToUint(cone_spread);
    ordinarylight_output_queue.rays[output_index].padding_c = uint(0);
    return true;
}
#endif
uint ordinarylight_primary_hash(uint value)
{
    value = (value ^ (value >> uint(16)));
    value = (value * uint(2146121005));
    value = (value ^ (value >> uint(15)));
    value = (value * uint(2221713035));
    value = (value ^ (value >> uint(16)));
    return value;
}
uint ordinarylight_primary_rng_seed(uint pixel_index, uint frame_index, uint sample_index)
{
    return ordinarylight_primary_hash(((pixel_index ^ ordinarylight_primary_hash(frame_index)) ^ ordinarylight_primary_hash((sample_index + uint(1)))));
}
uint ordinarylight_primary_rng_step(uint value)
{
    return ordinarylight_primary_hash(value);
}
float ordinarylight_primary_rng_value(uint value)
{
    return (float(value) / 4294967296.0);
}
uint ordinarylight_primary_path_identity(uint frame_index, uint sample_index)
{
    return ((frame_index << uint(8)) | (sample_index & uint(255)));
}
uint ordinarylight_primary_path_flags(bool indirect_capture)
{
    uint flags = uint(257);
    if (indirect_capture)
    {
        flags = (flags | uint(8));
    }
    return flags;
}
vec3 ordinarylight_primary_ray_origin(vec3 origin, vec3 right, vec3 up, vec2 ndc, float aspect, int projection)
{
    vec3 ray_origin = origin;
    if ((projection == 1))
    {
        ray_origin = ((ray_origin + ((ndc.x * aspect) * right)) - (ndc.y * up));
    }
    return ray_origin;
}
vec3 ordinarylight_primary_ray_direction(vec3 forward, vec3 right, vec3 up, vec2 ndc, float aspect, int projection)
{
    if ((projection == 1))
    {
        return normalize(forward);
    }
    if ((projection == 2))
    {
        float yaw = (ndc.x * length(right));
        float pitch = ((-ndc.y) * length(up));
        return normalize(((((normalize(forward) * cos(pitch)) * cos(yaw)) + ((normalize(right) * cos(pitch)) * sin(yaw))) + (normalize(up) * sin(pitch))));
    }
    return normalize(((forward + ((ndc.x * aspect) * right)) - (ndc.y * up)));
}
vec3 ordinarylight_primary_barycentric_weights(vec2 barycentrics)
{
    return vec3(((1.0 - barycentrics.x) - barycentrics.y), barycentrics.x, barycentrics.y);
}
vec3 ordinarylight_primary_hit_position(vec3 ray_origin, vec3 incoming, float distance)
{
    return (ray_origin + (distance * incoming));
}
vec3 ordinarylight_primary_geometric_normal(vec3 a, vec3 b, vec3 c)
{
    return normalize(cross((b - a), (c - a)));
}
vec3 ordinarylight_primary_shading_normal(vec3 normal_a, vec3 normal_b, vec3 normal_c, vec3 weights, vec3 geometric_normal)
{
    vec3 shading_normal = normalize((((normal_a * weights.x) + (normal_b * weights.y)) + (normal_c * weights.z)));
    if ((dot(shading_normal, geometric_normal) < 0.0))
    {
        shading_normal = (-shading_normal);
    }
    return shading_normal;
}
bool ordinarylight_primary_is_entering(vec3 incoming, vec3 geometric_normal)
{
    return (dot(incoming, geometric_normal) < 0.0);
}
vec3 ordinarylight_primary_oriented_normal(vec3 shading_normal, bool entering)
{
    if (entering)
    {
        return shading_normal;
    }
    return (-shading_normal);
}
float ordinarylight_primary_cone_spread(vec3 camera_up, uint image_height)
{
    return ((2.0 * length(camera_up)) / float(max(image_height, uint(1))));
}
float ordinarylight_primary_surface_class(float transmission, float emissive, bool opaque_scene)
{
    if (((!opaque_scene) && (transmission > 0.001)))
    {
        return 2.0;
    }
    if ((emissive > 0.5))
    {
        return 1.0;
    }
    return 0.0;
}
vec4 ordinarylight_primary_interpolate_vec4(vec4 value_a, vec4 value_b, vec4 value_c, vec3 weights)
{
    return (((value_a * weights.x) + (value_b * weights.y)) + (value_c * weights.z));
}
float ordinarylight_primary_uv_density(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec2 uv_a, vec2 uv_b, vec2 uv_c)
{
    vec2 first_uv = (uv_b - uv_a);
    vec2 second_uv = (uv_c - uv_a);
    float uv_area = abs(((first_uv.x * second_uv.y) - (first_uv.y * second_uv.x)));
    float world_area = length(cross((vertex_b - vertex_a), (vertex_c - vertex_a)));
    return sqrt((uv_area / max(world_area, 1e-08)));
}
vec4 ordinarylight_primary_triangle_tangent(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec2 uv_a, vec2 uv_b, vec2 uv_c, vec3 shading_normal)
{
    vec3 edge_a = (vertex_b - vertex_a);
    vec3 edge_b = (vertex_c - vertex_a);
    vec2 delta_a = (uv_b - uv_a);
    vec2 delta_b = (uv_c - uv_a);
    float determinant = ((delta_a.x * delta_b.y) - (delta_a.y * delta_b.x));
    if ((abs(determinant) < 1e-08))
    {
        vec3 fallback = cross(shading_normal, vec3(0.0, 1.0, 0.0));
        if ((abs(shading_normal.z) < 0.999))
        {
            fallback = cross(shading_normal, vec3(0.0, 0.0, 1.0));
        }
        return vec4(normalize(fallback), 1.0);
    }
    float inverse = (1.0 / determinant);
    vec3 tangent = normalize((((edge_a * delta_b.y) - (edge_b * delta_a.y)) * inverse));
    vec3 bitangent = normalize((((edge_b * delta_a.x) - (edge_a * delta_b.x)) * inverse));
    float handedness = 1.0;
    if ((dot(cross(shading_normal, tangent), bitangent) < 0.0))
    {
        handedness = (-1.0);
    }
    return vec4(tangent, handedness);
}
vec3 ordinarylight_primary_correct_mapped_normal(vec3 mapped_normal, vec3 geometric_normal)
{
    if ((dot(mapped_normal, geometric_normal) < 0.0))
    {
        return (-mapped_normal);
    }
    return mapped_normal;
}
vec3 ordinarylight_texture_apply_rgb(vec3 base_value, vec3 texture_value)
{
    return (base_value * texture_value);
}
float ordinarylight_texture_apply_scalar(float base_value, float texture_value)
{
    return (base_value * texture_value);
}
float ordinarylight_texture_apply_occlusion(float occlusion, float strength)
{
    return mix(1.0, occlusion, strength);
}
vec3 ordinarylight_texture_apply_normal(vec3 sampled_normal, float normal_scale, vec3 shading_normal, vec4 tangent_data, vec2 rotation, vec2 texture_scale)
{
    vec3 tangent_normal = ((sampled_normal * 2.0) - 1.0);
    tangent_normal.xy = (tangent_normal.xy * normal_scale);
    tangent_normal = normalize(tangent_normal);
    vec3 tangent = normalize((tangent_data.xyz - (shading_normal * dot(shading_normal, tangent_data.xyz))));
    vec3 bitangent = (cross(shading_normal, tangent) * tangent_data.w);
    float inverse_x = (1.0 / texture_scale.x);
    float inverse_y = (1.0 / texture_scale.y);
    vec3 transformed_tangent = normalize(((tangent * (rotation.x * inverse_x)) + (bitangent * ((-rotation.y) * inverse_y))));
    vec3 transformed_bitangent = normalize(((tangent * (rotation.y * inverse_x)) + (bitangent * (rotation.x * inverse_y))));
    return normalize((((transformed_tangent * tangent_normal.x) + (transformed_bitangent * tangent_normal.y)) + (shading_normal * tangent_normal.z)));
}
vec4 ordinarylight_primary_invalid_position()
{
    return vec4((-1.0));
}
uvec4 ordinarylight_primary_invalid_material()
{
    return uvec4(uint(4294967295));
}
vec4 ordinarylight_primary_hit_position_payload(float distance)
{
    return vec4(distance);
}
uvec4 ordinarylight_primary_packed_payload(uint value)
{
    return uvec4(value);
}
vec3 ordinarylight_primary_emission(vec3 emission, bool entering, bool two_sided)
{
    if ((entering || two_sided))
    {
        return emission;
    }
    return vec3(0.0);
}
bool ordinarylight_primary_should_terminate(uint max_bounces)
{
    return (max_bounces <= uint(1));
}
uint ordinarylight_primary_deactivate(uint flags)
{
    return (flags & (~uint(1)));
}
float ordinarylight_primary_transmission(float material_transmission, bool opaque_scene)
{
    if (opaque_scene)
    {
        return 0.0;
    }
    return material_transmission;
}
float ordinarylight_primary_target_ior(float material_ior)
{
    return max(material_ior, 1.0001);
}
vec3 ordinarylight_primary_refracted_direction(vec3 incoming, vec3 normal, float target_ior)
{
    return refract(incoming, normal, (1.0 / target_ior));
}
vec3 ordinarylight_primary_resolve_transmission_direction(vec3 refracted, vec3 incoming, vec3 normal)
{
    if ((dot(refracted, refracted) < 0.01))
    {
        return (incoming - ((2.0 * dot(incoming, normal)) * normal));
    }
    return refracted;
}
bool ordinarylight_primary_enters_medium(vec3 refracted, bool entering)
{
    return (entering && (dot(refracted, refracted) >= 0.01));
}
uint ordinarylight_primary_medium_depth(bool entered_medium)
{
    if (entered_medium)
    {
        return uint(2);
    }
    return uint(1);
}
vec3 ordinarylight_primary_transmission_weight(vec3 base_color, float transmission)
{
    return (mix(vec3(1.0), base_color, 0.2) * transmission);
}
float ordinarylight_primary_initial_medium_ior()
{
    return 1.0;
}
vec3 ordinarylight_primary_apply_bsdf_weight(vec3 throughput, vec3 bsdf_weight)
{
    return (throughput * bsdf_weight);
}
float ordinarylight_primary_scattered_cone_spread(float cone_spread, float roughness)
{
    return (cone_spread + (roughness * 0.25));
}
vec3 ordinarylight_primary_continuation_direction(vec3 direction)
{
    return normalize(direction);
}
uint ordinarylight_primary_continuation_flags(uint previous_flags, uint medium_depth, float transmission, bool unified_nee)
{
    uint flags = (uint(1) | (medium_depth << uint(8)));
    flags = (flags | (previous_flags & uint(8)));
    if ((transmission <= 0.001))
    {
        flags = (flags | uint(2));
        if (unified_nee)
        {
            flags = (flags | uint(4));
        }
    }
    return flags;
}
float ordinarylight_primary_previous_pdf(float previous_pdf, float bsdf_pdf, float transmission)
{
    if ((transmission <= 0.001))
    {
        return bsdf_pdf;
    }
    return previous_pdf;
}
bool ordinarylight_primary_capture_secondary(uint flags, float transmission)
{
    return (((flags & uint(8)) != uint(0)) && (transmission <= 0.001));
}
vec3 ordinarylight_primary_continuation_origin(vec3 position, vec3 direction)
{
    return (position + (direction * 0.002));
}
vec4 ordinarylight_primary_ray_origin_payload(vec3 origin)
{
    return vec4(origin, 0.001);
}
vec4 ordinarylight_primary_ray_direction_payload(vec3 direction)
{
    return vec4(direction, 1e+30);
}
vec3 ordinarylight_pbr_cosine_hemisphere(vec3 normal, float random_u, float random_v)
{
    float radius = sqrt(random_u);
    float phi = (6.28318530718 * random_v);
    vec3 tangent = cross(normal, vec3(0.0, 1.0, 0.0));
    if ((abs(normal.z) < 0.999))
    {
        tangent = cross(normal, vec3(0.0, 0.0, 1.0));
    }
    tangent = normalize(tangent);
    vec3 bitangent = cross(normal, tangent);
    return normalize(((((tangent * radius) * cos(phi)) + ((bitangent * radius) * sin(phi))) + (normal * sqrt(max(0.0, (1.0 - random_u))))));
}
vec3 ordinarylight_pbr_fresnel(vec3 f0, float cosine)
{
    return (f0 + ((vec3(1.0) - f0) * pow((1.0 - clamp(cosine, 0.0, 1.0)), 5.0)));
}
float ordinarylight_pbr_ggx_distribution(float normal_half, float roughness)
{
    float alpha = max((roughness * roughness), 0.0009);
    float alpha_squared = (alpha * alpha);
    float denominator = (((normal_half * normal_half) * (alpha_squared - 1.0)) + 1.0);
    return (alpha_squared / max(((3.14159265359 * denominator) * denominator), 1e-06));
}
float ordinarylight_pbr_ggx_smith(float normal_direction, float roughness)
{
    float alpha = max((roughness * roughness), 0.0009);
    float alpha_squared = (alpha * alpha);
    return ((2.0 * normal_direction) / max((normal_direction + sqrt((alpha_squared + (((1.0 - alpha_squared) * normal_direction) * normal_direction)))), 1e-06));
}
float ordinarylight_pbr_specular_probability(vec3 base_color, float metallic)
{
    vec3 f0 = mix(vec3(0.04), base_color, metallic);
    return clamp(max(f0.r, max(f0.g, f0.b)), 0.1, 0.9);
}
vec3 ordinarylight_pbr_evaluate(vec3 base_color, float roughness, float metallic, vec3 normal, vec3 view, vec3 outgoing)
{
    float normal_view = max(dot(normal, view), 0.0);
    float normal_light = max(dot(normal, outgoing), 0.0);
    if (((normal_view <= 0.0) || (normal_light <= 0.0)))
    {
        return vec3(0.0);
    }
    vec3 half_vector = normalize((view + outgoing));
    float normal_half = max(dot(normal, half_vector), 0.0);
    float view_half = max(dot(view, half_vector), 0.0);
    vec3 f0 = mix(vec3(0.04), base_color, metallic);
    vec3 fresnel = (f0 + ((vec3(1.0) - f0) * pow((1.0 - clamp(view_half, 0.0, 1.0)), 5.0)));
    float alpha = max((roughness * roughness), 0.0009);
    float alpha_squared = (alpha * alpha);
    float distribution_denominator = (((normal_half * normal_half) * (alpha_squared - 1.0)) + 1.0);
    float distribution = (alpha_squared / max(((3.14159265359 * distribution_denominator) * distribution_denominator), 1e-06));
    float view_geometry = ((2.0 * normal_view) / max((normal_view + sqrt((alpha_squared + (((1.0 - alpha_squared) * normal_view) * normal_view)))), 1e-06));
    float light_geometry = ((2.0 * normal_light) / max((normal_light + sqrt((alpha_squared + (((1.0 - alpha_squared) * normal_light) * normal_light)))), 1e-06));
    float geometry = (view_geometry * light_geometry);
    vec3 specular = (((fresnel * distribution) * geometry) / max(((4.0 * normal_view) * normal_light), 1e-06));
    vec3 diffuse = ((((vec3(1.0) - fresnel) * (1.0 - metallic)) * base_color) / 3.14159265359);
    return (diffuse + specular);
}
float ordinarylight_pbr_pdf(vec3 base_color, float roughness, float metallic, vec3 normal, vec3 view, vec3 outgoing)
{
    float normal_light = max(dot(normal, outgoing), 0.0);
    if ((normal_light <= 0.0))
    {
        return 0.0;
    }
    vec3 half_vector = normalize((view + outgoing));
    float normal_half = max(dot(normal, half_vector), 0.0);
    float view_half = max(dot(view, half_vector), 1e-06);
    float alpha = max((roughness * roughness), 0.0009);
    float alpha_squared = (alpha * alpha);
    float denominator = (((normal_half * normal_half) * (alpha_squared - 1.0)) + 1.0);
    float distribution = (alpha_squared / max(((3.14159265359 * denominator) * denominator), 1e-06));
    float specular_pdf = ((distribution * normal_half) / (4.0 * view_half));
    float diffuse_pdf = (normal_light / 3.14159265359);
    vec3 f0 = mix(vec3(0.04), base_color, metallic);
    float probability = clamp(max(f0.r, max(f0.g, f0.b)), 0.1, 0.9);
    return mix(diffuse_pdf, specular_pdf, probability);
}
vec3 ordinarylight_pbr_sample_half_vector(vec3 normal, float roughness, float random_u, float random_v)
{
    float alpha = max((roughness * roughness), 0.0009);
    float alpha_squared = (alpha * alpha);
    float phi = (6.28318530718 * random_v);
    float cosine = sqrt(((1.0 - random_u) / max((1.0 + ((alpha_squared - 1.0) * random_u)), 1e-06)));
    float sine = sqrt(max(0.0, (1.0 - (cosine * cosine))));
    vec3 tangent = cross(normal, vec3(0.0, 1.0, 0.0));
    if ((abs(normal.z) < 0.999))
    {
        tangent = cross(normal, vec3(0.0, 0.0, 1.0));
    }
    tangent = normalize(tangent);
    vec3 bitangent = cross(normal, tangent);
    return normalize(((((tangent * sine) * cos(phi)) + ((bitangent * sine) * sin(phi))) + (normal * cosine)));
}
vec3 ordinarylight_pbr_reflect(vec3 incoming, vec3 half_vector)
{
    return (incoming - ((2.0 * dot(half_vector, incoming)) * half_vector));
}
vec3 ordinarylight_pbr_weight(vec3 evaluated, float metallic, float occlusion, vec3 normal, vec3 view, vec3 outgoing, float pdf)
{
    vec3 weight = ((evaluated * max(dot(normal, outgoing), 0.0)) / pdf);
    return (weight * mix(occlusion, 1.0, metallic));
}
vec3 ordinarylight_analytic_light_direction(int light_type, vec3 light_position, vec3 light_direction, vec3 hit)
{
    if ((light_type == 1))
    {
        return (-normalize(light_direction));
    }
    vec3 offset = (light_position - hit);
    float distance_squared = max(dot(offset, offset), 1e-06);
    return (offset / sqrt(distance_squared));
}
float ordinarylight_analytic_light_distance_squared(int light_type, vec3 light_position, vec3 hit)
{
    if ((light_type == 1))
    {
        return 1.0;
    }
    vec3 offset = (light_position - hit);
    return max(dot(offset, offset), 1e-06);
}
float ordinarylight_analytic_light_attenuation(int light_type, float distance_squared, vec3 direction, vec3 light_direction, float spot_inner, float spot_outer)
{
    if ((light_type == 1))
    {
        return 1.0;
    }
    float attenuation = (1.0 / distance_squared);
    if ((light_type == 2))
    {
        float cone = dot(normalize(light_direction), (-direction));
        float interpolation = clamp(((cone - spot_outer) / (spot_inner - spot_outer)), 0.0, 1.0);
        float spot = ((interpolation * interpolation) * (3.0 - (2.0 * interpolation)));
        attenuation = (attenuation * spot);
    }
    return attenuation;
}
float ordinarylight_analytic_light_cosine(vec3 normal, vec3 direction)
{
    return max(dot(normal, direction), 0.0);
}
float ordinarylight_analytic_light_shadow_distance(int light_type, float distance_to_light)
{
    if ((light_type == 1))
    {
        return 10000.0;
    }
    return max((distance_to_light - 0.004), 0.001);
}
vec3 ordinarylight_analytic_light_incident(vec3 color, float intensity, float attenuation, float transmittance)
{
    return (((color * intensity) * attenuation) * transmittance);
}
vec3 ordinarylight_analytic_light_contribution(vec3 evaluated_pbr, vec3 incident, float cosine)
{
    return ((evaluated_pbr * incident) * cosine);
}
vec3 ordinarylight_area_light_position(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, float root_u, float value_v)
{
    return ((((1.0 - root_u) * vertex_a) + ((root_u * (1.0 - value_v)) * vertex_b)) + ((root_u * value_v) * vertex_c));
}
vec3 ordinarylight_area_light_barycentric_position(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec2 barycentrics)
{
    float a_weight = max(((1.0 - barycentrics.x) - barycentrics.y), 0.0);
    return (((a_weight * vertex_a) + (barycentrics.x * vertex_b)) + (barycentrics.y * vertex_c));
}
float ordinarylight_area_light_cosine(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec3 direction, bool two_sided)
{
    vec3 light_normal = normalize(cross((vertex_b - vertex_a), (vertex_c - vertex_a)));
    float raw_cosine = dot(light_normal, (-direction));
    if (two_sided)
    {
        return abs(raw_cosine);
    }
    return max(raw_cosine, 0.0);
}
float ordinarylight_area_light_pdf(float selection_pdf, float distance_squared, float light_cosine, float area, float technique_probability)
{
    float light_pdf = ((selection_pdf * distance_squared) / max((light_cosine * area), 1e-06));
    return (light_pdf * max(technique_probability, 1e-06));
}
float ordinarylight_area_light_mis(float effective_pdf, float sample_count, float bsdf_pdf)
{
    float first_pdf = (effective_pdf * sample_count);
    float first_squared = (first_pdf * first_pdf);
    float second_squared = (bsdf_pdf * bsdf_pdf);
    return (first_squared / max((first_squared + second_squared), 1e-06));
}
vec3 ordinarylight_area_light_contribution(vec3 evaluated_pbr, vec3 emission, float surface_cosine, float mis, float transmittance, float effective_pdf)
{
    return (((((evaluated_pbr * emission) * surface_cosine) * mis) * transmittance) / max(effective_pdf, 1e-06));
}
vec3 ordinarylight_environment_analytic(vec3 direction)
{
    float sky = max(direction.y, 0.0);
    return mix(vec3(0.018, 0.022, 0.032), vec3(0.32, 0.46, 0.72), sky);
}
vec2 ordinarylight_environment_uv(vec3 direction, float rotation)
{
    float longitude = (atan(direction.z, direction.x) + rotation);
    return vec2(fract(((longitude * 0.15915494309189535) + 0.5)), (acos(clamp(direction.y, (-1.0), 1.0)) * 0.3183098861837907));
}
vec3 ordinarylight_environment_radiance(vec3 encoded, float exposure, vec3 color, float intensity, bool textured)
{
    vec3 radiance = vec3(1.0);
    if (textured)
    {
        radiance = (exp2((encoded * exposure)) - vec3(1.0));
    }
    return ((radiance * color) * intensity);
}
float ordinarylight_environment_effective_pdf(float cosine, float technique_probability)
{
    float pdf = (cosine / 3.14159265359);
    return (pdf * max(technique_probability, 1e-06));
}
float ordinarylight_environment_mis(float cosine, float effective_pdf, float sample_count)
{
    float first_pdf = (effective_pdf * sample_count);
    float second_pdf = (cosine / 3.14159265359);
    float first_squared = (first_pdf * first_pdf);
    float second_squared = (second_pdf * second_pdf);
    return (first_squared / max((first_squared + second_squared), 1e-06));
}
vec3 ordinarylight_environment_contribution(vec3 evaluated_pbr, vec3 radiance, float cosine, float mis, float transmittance, float effective_pdf, float occlusion, float metallic)
{
    float material_weight = mix(occlusion, 1.0, metallic);
    return ((((((evaluated_pbr * radiance) * cosine) * mis) * transmittance) / max(effective_pdf, 1e-06)) * material_weight);
}
vec2 ordinarylight_environment_encode_direction(vec3 direction_input)
{
    vec3 direction = (direction_input / ((abs(direction_input.x) + abs(direction_input.y)) + abs(direction_input.z)));
    vec2 encoded = direction.xy;
    if ((direction.z < 0.0))
    {
        encoded = ((vec2(1.0) - abs(encoded.yx)) * sign(encoded.xy));
    }
    return ((encoded * 0.5) + vec2(0.5));
}
vec3 ordinarylight_environment_decode_direction(vec2 encoded)
{
    vec2 value = ((encoded * 2.0) - vec2(1.0));
    vec3 direction = vec3(value, ((1.0 - abs(value.x)) - abs(value.y)));
    if ((direction.z < 0.0))
    {
        direction.xy = ((vec2(1.0) - abs(direction.yx)) * sign(direction.xy));
    }
    return normalize(direction);
}
float ordinarylight_unified_area_probability(uint area_light_count, uint environment_samples, float area_light_weight)
{
    if ((area_light_count == uint(0)))
    {
        return 0.0;
    }
    if ((environment_samples == uint(0)))
    {
        return 1.0;
    }
    float area_weight = sqrt(max(area_light_weight, 1e-06));
    return (area_weight / (area_weight + 1.0));
}
float ordinarylight_unified_secondary_area_probability(bool area_enabled, bool environment_enabled, float area_light_weight, uint secondary_area_samples, uint environment_samples)
{
    float area_weight = 0.0;
    if (area_enabled)
    {
        area_weight = (sqrt(max(area_light_weight, 1e-06)) * float(max(secondary_area_samples, uint(1))));
    }
    float environment_weight = 0.0;
    if (environment_enabled)
    {
        environment_weight = float(min(environment_samples, uint(4)));
    }
    return (area_weight / max((area_weight + environment_weight), 1e-06));
}
uint ordinarylight_secondary_nee_hash(uint value)
{
    value = (value ^ (value >> uint(16)));
    value = (value * uint(2146121005));
    value = (value ^ (value >> uint(15)));
    value = (value * uint(2221713035));
    return (value ^ (value >> uint(16)));
}
bool ordinarylight_secondary_nee_select(float probability, uint pixel_index, uint frame_sample, uint bounce)
{
    if ((probability >= 0.999999))
    {
        return true;
    }
    uint frame_index = (frame_sample >> uint(8));
    uint sample_index = (frame_sample & uint(255));
    uint bounce_hash = (bounce + uint(1));
    bounce_hash = (bounce_hash ^ (bounce_hash >> uint(16)));
    bounce_hash = (bounce_hash * uint(2146121005));
    bounce_hash = (bounce_hash ^ (bounce_hash >> uint(15)));
    bounce_hash = (bounce_hash * uint(2221713035));
    bounce_hash = (bounce_hash ^ (bounce_hash >> uint(16)));
    uint sample_hash = (sample_index + uint(1));
    sample_hash = (sample_hash ^ (sample_hash >> uint(16)));
    sample_hash = (sample_hash * uint(2146121005));
    sample_hash = (sample_hash ^ (sample_hash >> uint(15)));
    sample_hash = (sample_hash * uint(2221713035));
    sample_hash = (sample_hash ^ (sample_hash >> uint(16)));
    uint scramble = ((pixel_index ^ bounce_hash) ^ sample_hash);
    scramble = (scramble ^ (scramble >> uint(16)));
    scramble = (scramble * uint(2146121005));
    scramble = (scramble ^ (scramble >> uint(15)));
    scramble = (scramble * uint(2221713035));
    scramble = (scramble ^ (scramble >> uint(16)));
    uint sequence = (bitfieldReverse(frame_index) ^ scramble);
    float selector = ((float(sequence) + 0.5) * (1.0 / 4294967296.0));
    return (selector < probability);
}
float ordinarylight_light_candidate_target(vec3 contribution)
{
    return max(dot(contribution, vec3(0.2126, 0.7152, 0.0722)), 0.0);
}
float ordinarylight_environment_miss_mis(bool previous_diffuse, uint environment_samples, float previous_pdf, bool unified_nee, float area_probability)
{
    if (((!previous_diffuse) || (environment_samples == uint(0))))
    {
        return 1.0;
    }
    float light_pdf = (previous_pdf * float(environment_samples));
    if (unified_nee)
    {
        light_pdf = (previous_pdf * (1.0 - area_probability));
    }
    float path_squared = (previous_pdf * previous_pdf);
    float light_squared = (light_pdf * light_pdf);
    return (path_squared / max((path_squared + light_squared), 1e-06));
}
float ordinarylight_emissive_hit_mis(bool previous_diffuse, vec3 emission, vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec3 geometric_normal, vec3 incoming, float hit_distance, bool two_sided, float area_light_weight, uint secondary_area_samples, bool unified_nee, float area_probability, float previous_pdf)
{
    if (((!previous_diffuse) || (dot(emission, emission) <= 0.0)))
    {
        return 1.0;
    }
    float area = (0.5 * length(cross((vertex_b - vertex_a), (vertex_c - vertex_a))));
    float raw_cosine = dot(geometric_normal, (-incoming));
    float light_cosine = max(raw_cosine, 0.0);
    if (two_sided)
    {
        light_cosine = abs(raw_cosine);
    }
    float luminance = dot(emission, vec3(0.2126, 0.7152, 0.0722));
    float selection_pdf = ((area * luminance) / max(area_light_weight, 1e-06));
    float light_pdf = (((selection_pdf * hit_distance) * hit_distance) / max((light_cosine * area), 1e-06));
    float sampled_light_pdf = (light_pdf * float(max(secondary_area_samples, uint(1))));
    if (unified_nee)
    {
        sampled_light_pdf = (light_pdf * area_probability);
    }
    float path_squared = (previous_pdf * previous_pdf);
    float light_squared = (sampled_light_pdf * sampled_light_pdf);
    return (path_squared / max((path_squared + light_squared), 1e-06));
}
vec3 ordinarylight_emission_contribution(vec3 throughput, vec3 emission, float mis)
{
    return ((throughput * emission) * mis);
}
vec3 ordinarylight_secondary_direct_contribution(vec3 throughput, vec3 direct, float nee_probability)
{
    return ((throughput * direct) / max(nee_probability, 1e-06));
}
vec3 ordinarylight_secondary_scatter_throughput(vec3 throughput, vec3 bsdf_weight)
{
    return (throughput * bsdf_weight);
}
bool ordinarylight_secondary_roulette_enabled(uint roulette_start, uint next_bounce, float transmission)
{
    return (((roulette_start > uint(0)) && (next_bounce >= roulette_start)) && (transmission <= 0.001));
}
float ordinarylight_secondary_survival_probability(vec3 throughput, float minimum_survival)
{
    return clamp(max(throughput.r, max(throughput.g, throughput.b)), minimum_survival, 0.95);
}
bool ordinarylight_secondary_survives(float random_value, float survival_probability)
{
    return (random_value < survival_probability);
}
vec3 ordinarylight_secondary_survival_throughput(vec3 throughput, float survival_probability)
{
    return (throughput / survival_probability);
}
float ordinarylight_secondary_target_ior(bool entering, float material_ior, float previous_medium_ior, uint medium_depth)
{
    if (entering)
    {
        return max(material_ior, 1.0001);
    }
    if ((medium_depth > uint(1)))
    {
        return previous_medium_ior;
    }
    return 1.0;
}
vec3 ordinarylight_secondary_refracted_direction(vec3 incoming, vec3 normal, float current_ior, float target_ior)
{
    return refract(incoming, normal, (current_ior / target_ior));
}
bool ordinarylight_secondary_enters_medium(vec3 refracted, bool entering, uint medium_depth, uint maximum_depth)
{
    return (((dot(refracted, refracted) >= 0.01) && entering) && (medium_depth < maximum_depth));
}
uint ordinarylight_secondary_medium_depth(vec3 refracted, bool entering, uint medium_depth, uint maximum_depth)
{
    if ((dot(refracted, refracted) < 0.01))
    {
        return medium_depth;
    }
    if ((entering && (medium_depth < maximum_depth)))
    {
        return (medium_depth + uint(1));
    }
    if (((!entering) && (medium_depth > uint(1))))
    {
        return (medium_depth - uint(1));
    }
    return medium_depth;
}
vec3 ordinarylight_secondary_transmission_throughput(vec3 throughput, vec3 base_color, float transmission)
{
    vec3 tint = mix(vec3(1.0), base_color, 0.2);
    return ((throughput * tint) * transmission);
}
float ordinarylight_secondary_cone_width(float cone_width, float distance, float cone_spread)
{
    return (cone_width + (distance * cone_spread));
}
float ordinarylight_secondary_texture_footprint(float cone_width, float uv_density, bool textured)
{
    if ((!textured))
    {
        return 0.0;
    }
    return (cone_width * uv_density);
}
vec3 ordinarylight_secondary_correct_shading_normal(vec3 shading_normal, vec3 geometric_normal)
{
    if ((dot(shading_normal, geometric_normal) < 0.0))
    {
        return (-shading_normal);
    }
    return shading_normal;
}
uint ordinarylight_secondary_stop_bounce(bool hybrid, uint inline_bounces, uint maximum_bounces)
{
    if (hybrid)
    {
        return min(inline_bounces, maximum_bounces);
    }
    return maximum_bounces;
}
bool ordinarylight_secondary_throughput_visible(vec3 throughput)
{
    return (max(throughput.r, max(throughput.g, throughput.b)) >= 0.0001);
}
vec3 ordinarylight_secondary_miss_contribution(vec3 throughput, vec3 environment, float mis)
{
    return ((throughput * environment) * mis);
}
uint ordinarylight_secondary_next_bounce(uint bounce)
{
    return (bounce + uint(1));
}
bool ordinarylight_secondary_bounce_terminates(uint next_bounce, uint maximum_bounces)
{
    return (next_bounce >= maximum_bounces);
}
bool ordinarylight_secondary_capture_hit(uint flags, uint bounce, float primary_capture_valid)
{
    return ((((flags & uint(8)) != uint(0)) && (bounce == uint(1))) && (primary_capture_valid > 0.5));
}
uint ordinarylight_secondary_ser_hint(float transmission, float metallic, float two_sided, float roughness, bool textured)
{
    uint hint = uint((transmission > 0.001));
    hint = (hint | (uint((metallic > 0.5)) << uint(1)));
    hint = (hint | (uint((two_sided > 0.5)) << uint(2)));
    uint roughness_bucket = uint(clamp((roughness * 7.0), 0.0, 7.0));
    hint = (hint | (roughness_bucket << uint(3)));
    hint = (hint | (uint(textured) << uint(6)));
    return hint;
}
float ordinarylight_secondary_nee_probability(float value)
{
    return clamp(value, 1e-06, 1.0);
}
uint ordinarylight_secondary_area_sample_count(uint value)
{
    return clamp(value, uint(1), uint(16));
}
uint ordinarylight_secondary_environment_sample_count(uint value)
{
    return min(value, uint(4));
}
vec3 ordinarylight_secondary_average_contribution(vec3 contribution, uint sample_count)
{
    return (contribution / float(sample_count));
}
bool ordinarylight_secondary_emission_visible(bool entering, float two_sided)
{
    return (entering || (two_sided > 0.5));
}
vec4 ordinarylight_secondary_capture_position(vec3 position)
{
    return vec4(position, 1.0);
}
#endif
