// Generated by scripts/generate_effect_shaders.py using Ordinary Shade.
// The checked-in artifact keeps Ordinary Shade an optional development tool.
vec3 ordinarylight_tint(vec3 color, vec3 target, float strength)
{
    return mix(color, target, strength);
}
vec3 ordinarylight_emissive(vec3 color, vec3 emission, float strength)
{
    return min((color + (emission * strength)), vec3(1.0));
}
vec3 ordinarylight_isolation(vec3 color, float dimming)
{
    return (color * (1.0 - dimming));
}
vec3 ordinarylight_outline(vec3 color, vec3 outline, bool boundary)
{
    return (boundary ? outline : color);
}
