#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#if WAVE_SER
#extension GL_NV_shader_invocation_reorder : require
#endif

layout(buffer_reference, std430) buffer ProbeOutput {
    uint values[];
};

layout(push_constant) uniform ProbeParameters {
    uint64_t outputAddress;
};

void main()
{
    uint index = gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x;
#if WAVE_SER
    reorderThreadNV(index & 3u, 2u);
#endif
    ProbeOutput(outputAddress).values[index] = index ^ 0x51e4a9bdu;
}
