// Generated by scripts/generate_utility_shaders.py using OrdinaryShade.
@group(0) @binding(0) var<storage, read> source: array<f32>;
@group(0) @binding(1) var destination: texture_storage_3d<rgba16float, write>;

@compute @workgroup_size(4, 4, 4)
fn main(
    @builtin(global_invocation_id) global_invocation_id: vec3<u32>,
    @builtin(local_invocation_id) local_invocation_id: vec3<u32>,
    @builtin(local_invocation_index) local_invocation_index: u32,
    @builtin(workgroup_id) workgroup_id: vec3<u32>,
    @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
    let index: vec3<u32> = vec3<u32>(global_invocation_id.x, global_invocation_id.y, global_invocation_id.z);
    let size: vec3<u32> = vec3<u32>(vec3<i32>(textureDimensions(destination)));
    if (any((index >= size))) {
        return;
    }
    let offset: u32 = ((((index.z * size.y) + index.y) * size.x) + index.x);
    textureStore(destination, vec3<i32>(index), vec4<f32>(source[offset], 0.0, 0.0, 1.0));
}
