// Generated by scripts/generate_restir_shaders.py using Ordinary Shade.
// Edit ordinarylight/shaders/restir_programs.py.


struct DirectLightReservoir
{
    uvec4 data;
};

#if WAVE_RESTIR_PRIMARY
layout(std430, set = 0, binding = 16) buffer current_reservoir_words_Block
{
    uint current_reservoir_words[];
};
layout(std430, set = 0, binding = 17) readonly buffer previous_reservoir_words_Block
{
    uint previous_reservoir_words[];
};
#endif

DirectLightReservoir emptyDirectLightReservoir();
bool updateDirectLightReservoir(inout DirectLightReservoir reservoir, uint light_index, vec2 barycentrics, float target, float candidate_weight, float represented_samples, float random_value);
bool mergeDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float random_value);
bool mergeCanonicalDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float random_value);
bool mergePairwiseDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float target_at_source_surface, float random_value);
bool mergeBalancedDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float active_proposals_over_target_sum, float random_value);
float directLightReservoirNormalization(DirectLightReservoir reservoir);
DirectLightReservoir limitDirectLightReservoir(DirectLightReservoir reservoir, float maximum_samples);
#if WAVE_RESTIR_PRIMARY
DirectLightReservoir unpackStoredDirectLightReservoir(uint header, uint barycentrics, uint weight_target);
#endif
#if WAVE_RESTIR_PRIMARY
DirectLightReservoir loadPreviousDirectLightReservoir(uint reservoir_index);
#endif
#if WAVE_RESTIR_PRIMARY
void storeCurrentDirectLightReservoir(uint reservoir_index, DirectLightReservoir reservoir);
#endif
#if WAVE_RESTIR_PRIMARY
DirectLightReservoir loadPreviousEnvironmentReservoir(uint reservoir_index, uint pixel_count);
#endif
#if WAVE_RESTIR_PRIMARY
void storeCurrentEnvironmentReservoir(uint reservoir_index, uint pixel_count, DirectLightReservoir reservoir);
#endif

DirectLightReservoir emptyDirectLightReservoir()
{
    return DirectLightReservoir(uvec4(4294967295, 0, 0, 0));
}

bool updateDirectLightReservoir(inout DirectLightReservoir reservoir, uint light_index, vec2 barycentrics, float target, float candidate_weight, float represented_samples, float random_value)
{
    candidate_weight = max(candidate_weight, 0.0);
    float weight_sum = (uintBitsToFloat(reservoir.data.z) + candidate_weight);
    vec2 target_count = unpackHalf2x16(reservoir.data.w);
    float sample_count = (target_count.y + represented_samples);
    bool selected = ((candidate_weight > 0.0) && ((reservoir.data.x == uint(4294967295)) || ((random_value * weight_sum) < candidate_weight)));
    if (selected)
    {
        reservoir.data.x = light_index;
        reservoir.data.y = packHalf2x16(clamp(barycentrics, vec2(0.0), vec2(1.0)));
        target_count.x = min(max(target, 0.0), 65504.0);
    }
    reservoir.data.z = floatBitsToUint(weight_sum);
    reservoir.data.w = packHalf2x16(vec2(target_count.x, sample_count));
    return selected;
}

bool mergeDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float random_value)
{
    vec2 tc = unpackHalf2x16(source.data.w);
    if (((source.data.x == uint(4294967295)) || (tc.y <= 0.0)))
    {
        return false;
    }
    float weight = 0.0;
    if ((tc.x > 0.0))
    {
        weight = ((max(target_at_current_surface, 0.0) * uintBitsToFloat(source.data.z)) / tc.x);
    }
    return updateDirectLightReservoir(destination, source.data.x, unpackHalf2x16(source.data.y), target_at_current_surface, weight, tc.y, random_value);
}

bool mergeCanonicalDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float random_value)
{
    vec2 tc = unpackHalf2x16(source.data.w);
    if ((((source.data.x == uint(4294967295)) || (tc.x <= 0.0)) || (tc.y <= 0.0)))
    {
        return false;
    }
    float weight = ((max(target_at_current_surface, 0.0) * uintBitsToFloat(source.data.z)) / (tc.x * tc.y));
    return updateDirectLightReservoir(destination, source.data.x, unpackHalf2x16(source.data.y), target_at_current_surface, weight, 1.0, random_value);
}

bool mergePairwiseDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float target_at_source_surface, float random_value)
{
    vec2 tc = unpackHalf2x16(source.data.w);
    if ((((source.data.x == uint(4294967295)) || (tc.x <= 0.0)) || (tc.y <= 0.0)))
    {
        return false;
    }
    float total = (max(target_at_current_surface, 0.0) + max(target_at_source_surface, 0.0));
    float balance = 0.0;
    if ((total > 0.0))
    {
        balance = ((2.0 * max(target_at_source_surface, 0.0)) / total);
    }
    float weight = (((max(target_at_current_surface, 0.0) * uintBitsToFloat(source.data.z)) / (tc.x * tc.y)) * balance);
    return updateDirectLightReservoir(destination, source.data.x, unpackHalf2x16(source.data.y), target_at_current_surface, weight, 1.0, random_value);
}

bool mergeBalancedDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float active_proposals_over_target_sum, float random_value)
{
    vec2 tc = unpackHalf2x16(source.data.w);
    if ((((source.data.x == uint(4294967295)) || (tc.x <= 0.0)) || (tc.y <= 0.0)))
    {
        return false;
    }
    float weight = (((max(target_at_current_surface, 0.0) * uintBitsToFloat(source.data.z)) / tc.y) * max(active_proposals_over_target_sum, 0.0));
    return updateDirectLightReservoir(destination, source.data.x, unpackHalf2x16(source.data.y), target_at_current_surface, weight, 1.0, random_value);
}

float directLightReservoirNormalization(DirectLightReservoir reservoir)
{
    vec2 tc = unpackHalf2x16(reservoir.data.w);
    if ((((reservoir.data.x == uint(4294967295)) || (tc.x <= 0.0)) || (tc.y <= 0.0)))
    {
        return 0.0;
    }
    return (uintBitsToFloat(reservoir.data.z) / (tc.y * tc.x));
}

DirectLightReservoir limitDirectLightReservoir(DirectLightReservoir reservoir, float maximum_samples)
{
    vec2 tc = unpackHalf2x16(reservoir.data.w);
    maximum_samples = max(maximum_samples, 0.0);
    if (((tc.y > maximum_samples) && (tc.y > 0.0)))
    {
        float scale = (maximum_samples / tc.y);
        reservoir.data.z = floatBitsToUint((uintBitsToFloat(reservoir.data.z) * scale));
        reservoir.data.w = packHalf2x16(vec2(tc.x, maximum_samples));
    }
    return reservoir;
}

#if WAVE_RESTIR_PRIMARY
DirectLightReservoir unpackStoredDirectLightReservoir(uint header, uint barycentrics, uint weight_target)
{
    uint light = (header & uint(33554431));
    uint count = (header >> uint(25));
    vec2 unpacked = unpackHalf2x16(weight_target);
    if ((light == uint(33554431)))
    {
        light = uint(4294967295);
    }
    return DirectLightReservoir(uvec4(light, barycentrics, floatBitsToUint(unpacked.x), packHalf2x16(vec2(unpacked.y, float(count)))));
}
#endif

#if WAVE_RESTIR_PRIMARY
DirectLightReservoir loadPreviousDirectLightReservoir(uint reservoir_index)
{
    uint word = (reservoir_index * uint(3));
    return unpackStoredDirectLightReservoir(previous_reservoir_words[word], previous_reservoir_words[(word + uint(1))], previous_reservoir_words[(word + uint(2))]);
}
#endif

#if WAVE_RESTIR_PRIMARY
void storeCurrentDirectLightReservoir(uint reservoir_index, DirectLightReservoir reservoir)
{
    vec2 tc = unpackHalf2x16(reservoir.data.w);
    uint light = uint(33554431);
    if ((reservoir.data.x != uint(4294967295)))
    {
        light = min(reservoir.data.x, uint(33554430));
    }
    uint count = uint(clamp(round(tc.y), 0.0, 127.0));
    float weight = clamp(uintBitsToFloat(reservoir.data.z), 0.0, 65504.0);
    uint word = (reservoir_index * uint(3));
    current_reservoir_words[word] = (light | (count << uint(25)));
    current_reservoir_words[(word + uint(1))] = reservoir.data.y;
    current_reservoir_words[(word + uint(2))] = packHalf2x16(vec2(weight, tc.x));
}
#endif

#if WAVE_RESTIR_PRIMARY
DirectLightReservoir loadPreviousEnvironmentReservoir(uint reservoir_index, uint pixel_count)
{
    uint word = ((pixel_count * uint(3)) + (reservoir_index * uint(2)));
    uint header = previous_reservoir_words[word];
    uint count = ((header >> uint(24)) & uint(127));
    if ((count == uint(0)))
    {
        return emptyDirectLightReservoir();
    }
    vec2 encoded = (vec2(float((header & uint(4095))), float(((header >> uint(12)) & uint(4095)))) / 4095.0);
    vec2 wt = unpackHalf2x16(previous_reservoir_words[(word + uint(1))]);
    return DirectLightReservoir(uvec4(33554430, packHalf2x16(encoded), floatBitsToUint(wt.x), packHalf2x16(vec2(wt.y, float(count)))));
}
#endif

#if WAVE_RESTIR_PRIMARY
void storeCurrentEnvironmentReservoir(uint reservoir_index, uint pixel_count, DirectLightReservoir reservoir)
{
    uint word = ((pixel_count * uint(3)) + (reservoir_index * uint(2)));
    vec2 tc = unpackHalf2x16(reservoir.data.w);
    uint count = uint(0);
    if ((reservoir.data.x != uint(4294967295)))
    {
        count = uint(clamp(round(tc.y), 1.0, 127.0));
    }
    vec2 encoded = clamp(unpackHalf2x16(reservoir.data.y), vec2(0.0), vec2(1.0));
    uvec2 quantized = uvec2(round((encoded * 4095.0)));
    current_reservoir_words[word] = ((quantized.x | (quantized.y << uint(12))) | (count << uint(24)));
    current_reservoir_words[(word + uint(1))] = packHalf2x16(vec2(clamp(uintBitsToFloat(reservoir.data.z), 0.0, 65504.0), clamp(tc.x, 0.0, 65504.0)));
}
#endif
