// Generated by scripts/generate_fused_primary.py using OrdinaryShade.
#include "transport_v1/material_contracts.glsl"

#if !defined(WAVE_SHARED_PRIMARY_RESERVOIRS)
#define WAVE_SHARED_PRIMARY_RESERVOIRS 0
#endif
#if !defined(WAVE_LOCAL_SIZE_X)
#define WAVE_LOCAL_SIZE_X 8
#endif
#if !defined(WAVE_LOCAL_SIZE_Y)
#define WAVE_LOCAL_SIZE_Y 8
#endif
#if !defined(WAVE_RAYGEN)
#define WAVE_RAYGEN 0
#endif
#if !defined(WAVE_CUSTOM_MATERIAL_PROGRAM)
#define WAVE_CUSTOM_MATERIAL_PROGRAM 0
#endif
#if !defined(WAVE_UNTEXTURED_PRIMARY)
#define WAVE_UNTEXTURED_PRIMARY WAVE_UNTEXTURED_SCENE
#endif
#if !defined(WAVE_UNTEXTURED_SECONDARY)
#define WAVE_UNTEXTURED_SECONDARY WAVE_UNTEXTURED_SCENE
#endif
#if !WAVE_RAYGEN
layout(
    local_size_x = WAVE_LOCAL_SIZE_X,
    local_size_y = WAVE_LOCAL_SIZE_Y,
    local_size_z = 1
) in;
#endif

const uint WAVE_MAX_MEDIUM_STACK_DEPTH = 16u;
const uint PATH_ACTIVE_BIT = 1u;
const uint PATH_PREVIOUS_DIFFUSE_BIT = 2u;
const uint PATH_PREVIOUS_UNIFIED_NEE_BIT = 4u;
const uint PATH_INDIRECT_CAPTURE_BIT = 8u;

struct WaveRay {
    vec4 origin_tmin;
    vec4 direction_tmax;
    uint path_index;
    uint padding_a;
    uint padding_b;
    uint padding_c;
};
struct WavePathState {
    vec4 throughput;
    vec4 radiance;
    uvec4 metadata;
};
struct SecondaryPathState {
    vec4 position_valid;
    vec4 normal_pdf;
    vec4 primary_throughput;
    vec4 primary_radiance;
    vec4 diffuse_radiance_hit_distance;
    vec4 specular_radiance_hit_distance;
    vec4 primary_position;
    vec4 primary_geometry;
};

uint pathRng(WavePathState path)
{
    return path.metadata.z;
}
void setPathRng(inout WavePathState path, uint rng)
{
    path.metadata.z = rng;
}
uint pathBounce(WavePathState path)
{
    return uint(path.throughput.w);
}
void setPathBounce(inout WavePathState path, uint bounce)
{
    path.throughput.w = float(bounce);
}
float pathPreviousPdf(WavePathState path)
{
    return path.radiance.w;
}
void setPathPreviousPdf(inout WavePathState path, float pdf)
{
    path.radiance.w = pdf;
}
struct WaveMediumStack { float ior[WAVE_MAX_MEDIUM_STACK_DEPTH]; };
struct MaterialData {
    vec4 base_roughness;
    vec4 emission_metallic;
    vec4 attenuation_transmission;
    vec4 ior_distance;
    vec4 texture_indices;
    vec4 texture_parameters;
    vec4 advanced0;
    vec4 advanced1;
    vec4 sheen_color;
    vec4 subsurface_color;
    vec4 advanced_texture_indices;
    vec4 optical;
};

struct VertexAttributeData { vec4 normal; vec4 texcoord; vec4 tangent; };
struct PointLightData {
    vec4 position_type;
    vec4 direction_range;
    vec4 color_intensity;
    vec4 spot_parameters;
};
struct AreaLightData {
    vec4 a; vec4 b; vec4 c; vec4 emission_area; vec4 distribution;
};
struct TextureBindingData { vec4 texture_rotation; vec4 offset_scale; };

layout(set = 0, binding = 0) uniform accelerationStructureEXT scene_tlas;
layout(set = 0, binding = 1, std430) buffer PathStates {
    WavePathState paths[];
};
layout(set = 0, binding = 2, std430) readonly buffer MaterialBuffer {
    MaterialData materials[];
};
layout(set = 0, binding = 3, std430) readonly buffer VertexBuffer {
    vec4 vertices[];
};
layout(set = 0, binding = 4, std430) readonly buffer AttributeBuffer {
    VertexAttributeData attributes[];
};
layout(set = 0, binding = 5, std430) buffer OutputRayQueue {
    uint count; uint capacity; uint overflow; uint queue_padding;
    WaveRay rays[];
} output_queue;
layout(set = 0, binding = 6, std430) buffer MediumStacks {
    WaveMediumStack stacks[];
};
layout(set = 0, binding = 7, std430) readonly buffer CameraData {
    vec4 origin;
    vec4 forward;
    vec4 right;
    vec4 up;
#if WAVE_CAMERA_RESTIR_POLICY
    uvec4 restir_policy;
#endif
} camera;
layout(set = 0, binding = 8, r32f) uniform writeonly image2D position_image;
layout(set = 0, binding = 9, r32ui) uniform writeonly uimage2D normal_image;
layout(set = 0, binding = 18, std430) readonly buffer PreviousCameraData {
    vec4 origin;
    vec4 forward;
    vec4 right;
    vec4 up;
} previous_camera;
layout(set = 0, binding = 19, r32f) uniform readonly image2D previous_position_image;
layout(set = 0, binding = 20, r32ui) uniform readonly uimage2D previous_normal_image;
layout(set = 0, binding = 21, r32ui) uniform writeonly uimage2D material_image;
layout(set = 0, binding = 22, r32ui) uniform readonly uimage2D previous_material_image;
layout(set = 0, binding = 23, std430) buffer SecondaryPathStates {
    SecondaryPathState secondary_paths[];
};
layout(set = 0, binding = 10, std430) readonly buffer PointLightBuffer {
    PointLightData point_lights[];
};
layout(set = 0, binding = 11, std430) readonly buffer AreaLightBuffer {
    AreaLightData area_lights[];
};
layout(set = 0, binding = 12, std430) readonly buffer TextureBuffer {
    uint texture_words[];
};
layout(set = 0, binding = 13, std430) readonly buffer TextureBindingBuffer {
    TextureBindingData texture_bindings[];
};
#if WAVE_NATIVE_TEXTURES
layout(set = 0, binding = 14) uniform sampler2D native_textures[128];
#endif
#if WAVE_WORK_COUNTERS
layout(set = 0, binding = 15, std430) buffer WorkCounterBuffer {
    uint work_counters[];
};
uint profile_bounce = 0u;
void profileWork(uint counter, uint amount)
{
    atomicAdd(work_counters[counter], amount);
    uint bounce = min(profile_bounce, uint(7));
    if ((counter == uint(0)))
    {
        atomicAdd(work_counters[(uint(16) + bounce)], amount);
    }
    else
    {
        if ((counter == uint(1)))
        {
            atomicAdd(work_counters[(uint(24) + bounce)], amount);
        }
        else
        {
            if ((counter == uint(3)))
            {
                atomicAdd(work_counters[(uint(32) + bounce)], amount);
            }
        }
    }
}
#endif

layout(push_constant) uniform PushConstants {
    uvec4 image_tile;
    uvec4 tile_frame;
    uint max_bounces;
    uint point_light_count;
    uint area_light_count;
    uint area_light_samples;
    uint secondary_area_light_samples;
    float area_light_weight;
    uint gbuffer_enabled;
    uint environment_samples;
    uint subgroup_enqueue;
    uint russian_roulette_start;
    float russian_roulette_min_survival;
    float secondary_nee_probability;
    uint inline_bounces;
    uint restir_di;
    uint restir_history_valid;
    uint restir_history_limit;
    uint restir_candidate_count;
    uint restir_spatial_reuse;
    uint restir_spatial_neighbors;
    uint restir_spatial_radius;
    uint restir_pairwise_mis;
    uint restir_generalized_mis;
    float restir_generalized_balance_cap;
    uint unified_secondary_nee;
    uint unified_primary_restir;
    uint stratified_primary_restir;
    uint indirect_secondary_capture;
    uint indirect_capture_stride;
    uvec4 object_effect_ranges[2];
} push;

// The production specialization removes optional estimators that are disabled
// in the selected RendererConfig. The push-constant ABI stays unchanged so
// specialized and general pipelines remain interchangeable.
#if WAVE_PRODUCTION_RESTIR
#define WAVE_GENERALIZED_RESTIR 0u
#define WAVE_UNIFIED_PRIMARY_RESTIR 0u
#define WAVE_STRATIFIED_PRIMARY_RESTIR 0u
#else
#define WAVE_GENERALIZED_RESTIR push.restir_generalized_mis
#define WAVE_UNIFIED_PRIMARY_RESTIR push.unified_primary_restir
#define WAVE_STRATIFIED_PRIMARY_RESTIR push.stratified_primary_restir
#endif

uint hashValue(uint value);

vec2 restirEncodeNormal(vec3 normal)
{
    normal = (normal / ((abs(normal.x) + abs(normal.y)) + abs(normal.z)));
    vec2 encoded = normal.xy;
    if ((normal.z < 0.0))
    {
        encoded = ((1.0 - abs(encoded.yx)) * sign(encoded.xy));
    }
    return encoded;
}

vec3 restirDecodeNormal(vec2 encoded)
{
    vec3 normal = vec3(encoded, ((1.0 - abs(encoded.x)) - abs(encoded.y)));
    if ((normal.z < 0.0))
    {
        normal.xy = ((1.0 - abs(normal.yx)) * sign(normal.xy));
    }
    return normalize(normal);
}

vec2 restirEncodeNormal(vec3 normal);
uint restirPackNormalClass(vec3 normal, float surface_class)
{
    vec2 unit = ((restirEncodeNormal(normal) * 0.5) + 0.5);
    uvec2 quantized = uvec2(round((clamp(unit, 0.0, 1.0) * 32767.0)));
    uint classification = uint(clamp(round(surface_class), 0.0, 3.0));
    return ((quantized.x | (quantized.y << uint(15))) | (classification << uint(30)));
}

vec3 restirDecodeNormal(vec2 encoded);
vec4 restirUnpackNormalClass(uint packed)
{
    vec2 unit = (vec2(float((packed & uint(32767))), float(((packed >> uint(15)) & uint(32767)))) / 32767.0);
    return vec4(restirDecodeNormal(((unit * 2.0) - 1.0)), float((packed >> uint(30))));
}

ivec2 restirSpatialOffset(uint index, int radius)
{
    ivec2 directions[8];
    directions[0] = ivec2(1, 0);
    directions[1] = ivec2((-1), 0);
    directions[2] = ivec2(0, 1);
    directions[3] = ivec2(0, (-1));
    directions[4] = ivec2(1, 1);
    directions[5] = ivec2((-1), 1);
    directions[6] = ivec2(1, (-1));
    directions[7] = ivec2((-1), (-1));
    return (directions[(index & uint(7))] * radius);
}

uint hashValue(uint value);
uint restirMaterialSignature(MaterialData material)
{
    uint signature = hashValue(floatBitsToUint(material.base_roughness.x));
    signature = (signature ^ hashValue(floatBitsToUint(material.base_roughness.y)));
    signature = (signature ^ hashValue(floatBitsToUint(material.base_roughness.z)));
    signature = (signature ^ hashValue(floatBitsToUint(material.base_roughness.w)));
    signature = (signature ^ hashValue(floatBitsToUint(material.emission_metallic.w)));
    signature = (signature ^ hashValue(floatBitsToUint(material.attenuation_transmission.w)));
    signature = (signature ^ hashValue(floatBitsToUint(material.ior_distance.x)));
    signature = (signature ^ hashValue(floatBitsToUint(material.texture_indices.x)));
    signature = (signature ^ hashValue(floatBitsToUint(material.texture_indices.y)));
    signature = (signature ^ hashValue(floatBitsToUint(material.texture_indices.z)));
    signature = (signature ^ hashValue(floatBitsToUint(material.texture_indices.w)));
    return signature;
}

bool reprojectRestir(vec3 world_position, out ivec2 previous_pixel)
{
    vec3 offset = (world_position - previous_camera.origin.xyz);
    float previous_depth = dot(offset, previous_camera.forward.xyz);
    float scale = length(previous_camera.up.xyz);
    float aspect = (float(push.image_tile.x) / float(push.image_tile.y));
    if (((previous_depth <= 0.0001) || (scale <= 0.0001)))
    {
        return false;
    }
    vec2 ndc = vec2((dot(offset, normalize(previous_camera.right.xyz)) / ((previous_depth * aspect) * scale)), ((-dot(offset, normalize(previous_camera.up.xyz))) / (previous_depth * scale)));
    vec2 pixel = ((((ndc * 0.5) + 0.5) * vec2(push.image_tile.xy)) - 0.5);
    previous_pixel = ivec2(round(pixel));
    return (all(greaterThanEqual(previous_pixel, ivec2(0))) && all(lessThan(previous_pixel, ivec2(push.image_tile.xy))));
}

vec3 restirPreviousWorldPosition(ivec2 pixel, float ray_distance)
{
    vec2 ndc = ((((vec2(pixel) + 0.5) / vec2(push.image_tile.xy)) * 2.0) - 1.0);
    float aspect = (float(push.image_tile.x) / float(push.image_tile.y));
    vec3 direction = normalize(((previous_camera.forward.xyz + ((ndc.x * aspect) * previous_camera.right.xyz)) - (ndc.y * previous_camera.up.xyz)));
    return (previous_camera.origin.xyz + (direction * ray_distance));
}

vec3 restirPreviousWorldPosition(ivec2 pixel, float ray_distance);
vec4 restirUnpackNormalClass(uint packed);
bool restirHistorySurfaceCompatible(ivec2 history_pixel, vec3 position, vec3 shading_normal, float distance, float surface_class, uint material_signature, bool temporal_center, out vec4 old_position, out vec4 old_normal)
{
    float old_distance = imageLoad(previous_position_image, history_pixel).x;
    old_position = vec4(restirPreviousWorldPosition(history_pixel, old_distance), old_distance);
    old_normal = restirUnpackNormalClass(imageLoad(previous_normal_image, history_pixel).x);
    uint old_material = imageLoad(previous_material_image, history_pixel).x;
    vec3 position_delta = (old_position.xyz - position);
    float position_tolerance = max(0.03, (distance * 0.01));
    float position_error = (temporal_center ? length(position_delta) : abs(dot(position_delta, normalize(shading_normal))));
    float normal_agreement = dot(normalize(old_normal.xyz), normalize(shading_normal));
    return (((((old_position.w >= 0.0) && (position_error <= position_tolerance)) && (normal_agreement > 0.9)) && (abs((old_normal.w - surface_class)) < 0.25)) && (old_material == material_signature));
}

bool restirHistorySurfaceCompatible(ivec2 history_pixel, vec3 position, vec3 shading_normal, float distance, float surface_class, uint material_signature, bool temporal_center, out vec4 old_position, out vec4 old_normal);
bool restirHistorySurfaceMatches(ivec2 history_pixel, vec3 position, vec3 shading_normal, float distance, float surface_class, uint material_signature, bool temporal_center)
{
    vec4 history_position = vec4(0);
    vec4 history_normal = vec4(0);
    return restirHistorySurfaceCompatible(history_pixel, position, shading_normal, distance, surface_class, material_signature, temporal_center, history_position, history_normal);
}

uint ordinarylight_reserve_output_index(uint subgroup_enqueue);

uint ordinarylight_reserve_output_index(uint subgroup_enqueue);
uint reserveOutputIndex()
{
    return ordinarylight_reserve_output_index(push.subgroup_enqueue);
}

uint hashValue(uint value)
{
    value = (value ^ (value >> 16));
    value = (value * uint(2146121005));
    value = (value ^ (value >> 15));
    value = (value * uint(2221713035));
    value = (value ^ (value >> 16));
    return value;
}

#define WAVE_RESTIR_PRIMARY 1
#include "wavefront_textures.glsl"
#include "wavefront_volumes.glsl"
#include "wavefront_lighting.glsl"

#define WAVE_MEDIUM_IOR(path_index, depth)      ordinarylight_medium_ior(path_index, depth)
#define WAVE_SET_MEDIUM_IOR(path_index, depth, value)      ordinarylight_set_medium_ior(path_index, depth, value)

#define WAVE_STORE_PATH(path_index, path)      ordinarylight_store_path(path_index, path)
#define WAVE_DEACTIVATE_STORED_PATH(path_index)      ordinarylight_deactivate_stored_path(path_index)
#define WAVE_SECONDARY_PRIMARY_VALID(path_index)      ordinarylight_secondary_primary_valid(path_index)

#define WAVE_PROFILE_WORK(counter, amount)      ordinarylight_profile_work(counter, amount)
#define WAVE_INTEGRATE_VOLUMES(origin, direction, distance, radiance, throughput)      ordinarylight_integrate_secondary_volumes(          origin, direction, distance, radiance, throughput)

#if !defined(WAVE_GROUP_SWIZZLE_WIDTH)
#define WAVE_GROUP_SWIZZLE_WIDTH 1
#endif
#include "ordinaryshade_primary.glsl"

#if WAVE_MEGAKERNEL || WAVE_HYBRID
void applyMaterialTextures(inout MaterialData material, vec2 uv0, vec2 uv1, float uv0_footprint, float uv1_footprint);
vec3 applyNormalTexture(MaterialData material, vec2 uv0, vec2 uv1, float uv0_footprint, float uv1_footprint, vec3 shading_normal, vec4 tangent_data);
vec3 environmentColor(vec3 direction);
MaterialEvaluation evaluateMaterial(inout MaterialData material, inout vec3 normal, vec2 uv, vec3 direction, bool entering, float random_u, float random_v, float bounce_index, float current_ior, float exterior_ior);
bool materialHasTextures(MaterialData material);
vec3 ordinarylight_emission_contribution(vec3 throughput, vec3 emission, float mis);
float ordinarylight_emissive_hit_mis(bool previous_diffuse, vec3 emission, vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec3 geometric_normal, vec3 incoming, float hit_distance, bool two_sided, float area_light_weight, uint secondary_area_samples, bool unified_nee, float area_probability, float previous_pdf);
float ordinarylight_environment_miss_mis(bool previous_diffuse, uint environment_samples, float previous_pdf, bool unified_nee, float area_probability);
void ordinarylight_integrate_secondary_volumes(vec3 origin, vec3 direction, float distance, inout vec3 radiance, inout vec3 throughput);
float ordinarylight_medium_ior(uint path_index, uint depth);
vec3 ordinarylight_primary_barycentric_weights(vec2 barycentrics);
vec3 ordinarylight_primary_continuation_direction(vec3 direction);
uint ordinarylight_primary_continuation_flags(uint previous_flags, uint medium_depth, float transmission, bool unified_nee);
vec3 ordinarylight_primary_continuation_origin(vec3 position, vec3 direction);
uint ordinarylight_primary_deactivate(uint flags);
vec3 ordinarylight_primary_geometric_normal(vec3 a, vec3 b, vec3 c);
vec3 ordinarylight_primary_hit_position(vec3 ray_origin, vec3 incoming, float distance);
vec4 ordinarylight_primary_interpolate_vec4(vec4 value_a, vec4 value_b, vec4 value_c, vec3 weights);
bool ordinarylight_primary_is_entering(vec3 incoming, vec3 geometric_normal);
vec3 ordinarylight_primary_oriented_normal(vec3 shading_normal, bool entering);
float ordinarylight_primary_previous_pdf(float previous_pdf, float bsdf_pdf, float transmission);
vec3 ordinarylight_primary_resolve_transmission_direction(vec3 refracted, vec3 incoming, vec3 normal);
float ordinarylight_primary_scattered_cone_spread(float cone_spread, float roughness);
vec3 ordinarylight_primary_shading_normal(vec3 normal_a, vec3 normal_b, vec3 normal_c, vec3 weights, vec3 geometric_normal);
vec4 ordinarylight_primary_triangle_tangent(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec2 uv_a, vec2 uv_b, vec2 uv_c, vec3 shading_normal);
float ordinarylight_primary_uv_density(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec2 uv_a, vec2 uv_b, vec2 uv_c);
void ordinarylight_profile_work(uint counter, uint amount);
uint ordinarylight_secondary_area_sample_count(uint value);
vec3 ordinarylight_secondary_average_contribution(vec3 contribution, uint sample_count);
bool ordinarylight_secondary_bounce_terminates(uint next_bounce, uint maximum_bounces);
bool ordinarylight_secondary_capture_hit(uint flags, uint bounce, float primary_capture_valid);
vec4 ordinarylight_secondary_capture_position(vec3 position);
float ordinarylight_secondary_cone_width(float cone_width, float distance, float cone_spread);
vec3 ordinarylight_secondary_correct_shading_normal(vec3 shading_normal, vec3 geometric_normal);
vec3 ordinarylight_secondary_direct_contribution(vec3 throughput, vec3 direct, float nee_probability);
bool ordinarylight_secondary_emission_visible(bool entering, float two_sided);
bool ordinarylight_secondary_enters_medium(vec3 refracted, bool entering, uint medium_depth, uint maximum_depth);
uint ordinarylight_secondary_environment_sample_count(uint value);
MaterialData ordinarylight_secondary_material(uint primitive);
uint ordinarylight_secondary_medium_depth(vec3 refracted, bool entering, uint medium_depth, uint maximum_depth);
vec3 ordinarylight_secondary_miss_contribution(vec3 throughput, vec3 environment, float mis);
float ordinarylight_secondary_nee_probability(float value);
uint ordinarylight_secondary_next_bounce(uint bounce);
float ordinarylight_secondary_primary_valid(uint path_index);
vec3 ordinarylight_secondary_refracted_direction(vec3 incoming, vec3 normal, float current_ior, float target_ior);
void ordinarylight_secondary_reorder(uint hint);
bool ordinarylight_secondary_roulette_enabled(uint roulette_start, uint next_bounce, float transmission);
vec3 ordinarylight_secondary_scatter_throughput(vec3 throughput, vec3 bsdf_weight);
uint ordinarylight_secondary_ser_hint(float transmission, float metallic, float two_sided, float roughness, bool textured);
float ordinarylight_secondary_survival_probability(vec3 throughput, float minimum_survival);
vec3 ordinarylight_secondary_survival_throughput(vec3 throughput, float survival_probability);
bool ordinarylight_secondary_survives(float random_value, float survival_probability);
float ordinarylight_secondary_target_ior(bool entering, float material_ior, float previous_medium_ior, uint medium_depth);
float ordinarylight_secondary_texture_footprint(float cone_width, float uv_density, bool textured);
bool ordinarylight_secondary_throughput_visible(vec3 throughput);
void ordinarylight_secondary_trace_query(vec3 origin, vec3 direction, inout bool surface_hit, inout float distance, inout uint primitive, inout vec2 barycentrics);
VertexAttributeData ordinarylight_secondary_vertex_attribute(uint primitive, uint corner);
vec3 ordinarylight_secondary_vertex_position(uint primitive, uint corner);
void ordinarylight_set_medium_ior(uint path_index, uint depth, float value);
void ordinarylight_store_secondary_hit(uint path_index, vec4 position_valid, vec3 normal);
uint pathBounce(WavePathState path);
float pathPreviousPdf(WavePathState path);
float randomFloat(inout uint state);
vec3 sampleAreaLight(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count);
vec3 sampleEnvironment(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_count);
void samplePbr(MaterialData material, vec3 normal, vec3 incoming, inout uint rng, out vec3 outgoing, out vec3 weight, out float pdf, out float sampled_specular);
vec3 samplePointLights(vec3 hit, vec3 normal, vec3 incoming, MaterialData material);
vec3 sampleUnifiedSecondaryLight(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng);
bool selectSecondaryNee(float probability, uint pixel_index, uint frame_sample, uint bounce);
void setPathBounce(inout WavePathState path, uint bounce);
void setPathPreviousPdf(inout WavePathState path, float pdf);
bool textureBindingUsesUv1(float binding_index_value);
float unifiedAreaDomainProbability();
MaterialEvaluation waveApplyMaterialProgram(inout MaterialData material, vec3 normal, vec2 uv, vec3 direction, bool entering, uint primitive, vec3 weights, float bounce_index);
bool ordinarylightSecondaryBounce(inout WavePathState path, inout vec3 origin, inout vec3 direction, uint path_index, inout uint medium_depth, inout uint rng, inout float cone_width, inout float cone_spread)
{
    uint bounce = pathBounce(path);
#if WAVE_WORK_COUNTERS
    profile_bounce = bounce;
    ordinarylight_profile_work(uint(0), uint(1));
#endif
    bool surface_hit = false;
    float distance = 1e+30;
    uint primitive = uint(0);
    vec2 barycentrics = vec2(0.0);
    ordinarylight_secondary_trace_query(origin, direction, surface_hit, distance, primitive, barycentrics);
    ordinarylight_integrate_secondary_volumes(origin, direction, distance, path.radiance.rgb, path.throughput.rgb);
    if ((!ordinarylight_secondary_throughput_visible(path.throughput.rgb)))
    {
        path.metadata.w = ordinarylight_primary_deactivate(path.metadata.w);
        return false;
    }
    if ((!surface_hit))
    {
#if WAVE_WORK_COUNTERS
        ordinarylight_profile_work(uint(4), uint(1));
#endif
        float environment_mis = ordinarylight_environment_miss_mis(((path.metadata.w & PATH_PREVIOUS_DIFFUSE_BIT) != uint(0)), push.environment_samples, pathPreviousPdf(path), ((path.metadata.w & PATH_PREVIOUS_UNIFIED_NEE_BIT) != uint(0)), unifiedAreaDomainProbability());
        path.radiance.rgb = (path.radiance.rgb + ordinarylight_secondary_miss_contribution(path.throughput.rgb, environmentColor(direction), environment_mis));
        path.metadata.w = ordinarylight_primary_deactivate(path.metadata.w);
        return false;
    }
#if WAVE_WORK_COUNTERS
    ordinarylight_profile_work(uint(3), uint(1));
#endif
    cone_width = ordinarylight_secondary_cone_width(cone_width, distance, cone_spread);
    vec3 a = ordinarylight_secondary_vertex_position(primitive, uint(0));
    vec3 b = ordinarylight_secondary_vertex_position(primitive, uint(1));
    vec3 c = ordinarylight_secondary_vertex_position(primitive, uint(2));
    VertexAttributeData attribute_a = ordinarylight_secondary_vertex_attribute(primitive, uint(0));
    VertexAttributeData attribute_b = ordinarylight_secondary_vertex_attribute(primitive, uint(1));
    VertexAttributeData attribute_c = ordinarylight_secondary_vertex_attribute(primitive, uint(2));
    vec3 hit = ordinarylight_primary_hit_position(origin, direction, distance);
    vec3 geometric_normal = ordinarylight_primary_geometric_normal(a, b, c);
    vec3 weights = ordinarylight_primary_barycentric_weights(barycentrics);
    vec3 shading_normal = ordinarylight_primary_shading_normal(attribute_a.normal.xyz, attribute_b.normal.xyz, attribute_c.normal.xyz, weights, geometric_normal);
    bool entering = ordinarylight_primary_is_entering(direction, geometric_normal);
    vec3 normal = ordinarylight_primary_oriented_normal(shading_normal, entering);
    MaterialData material = ordinarylight_secondary_material(primitive);
#if WAVE_SER
    uint ser_hint = ordinarylight_secondary_ser_hint(material.attenuation_transmission.a, material.emission_metallic.a, material.emission_metallic.w, material.base_roughness.w, materialHasTextures(material));
    ordinarylight_secondary_reorder(ser_hint);
#endif
#if !WAVE_UNTEXTURED_SECONDARY
    vec2 uv0 = ordinarylight_primary_interpolate_vec4(attribute_a.texcoord, attribute_b.texcoord, attribute_c.texcoord, weights).xy;
    vec2 uv1 = ordinarylight_primary_interpolate_vec4(attribute_a.texcoord, attribute_b.texcoord, attribute_c.texcoord, weights).zw;
    bool textured_material = materialHasTextures(material);
    float uv0_footprint = ordinarylight_secondary_texture_footprint(cone_width, attribute_a.normal.w, textured_material);
    float uv1_density = ordinarylight_primary_uv_density(a, b, c, attribute_a.texcoord.zw, attribute_b.texcoord.zw, attribute_c.texcoord.zw);
    float uv1_footprint = ordinarylight_secondary_texture_footprint(cone_width, uv1_density, textured_material);
    applyMaterialTextures(material, uv0, uv1, uv0_footprint, uv1_footprint);
    vec4 tangent_data = ordinarylight_primary_interpolate_vec4(attribute_a.tangent, attribute_b.tangent, attribute_c.tangent, weights);
    if (textureBindingUsesUv1(material.texture_indices.w))
    {
        tangent_data = ordinarylight_primary_triangle_tangent(a, b, c, attribute_a.texcoord.zw, attribute_b.texcoord.zw, attribute_c.texcoord.zw, shading_normal);
    }
    shading_normal = applyNormalTexture(material, uv0, uv1, uv0_footprint, uv1_footprint, shading_normal, tangent_data);
    shading_normal = ordinarylight_secondary_correct_shading_normal(shading_normal, geometric_normal);
    normal = ordinarylight_primary_oriented_normal(shading_normal, entering);
#else
    material.texture_parameters.w = 1.0;
#endif
    if (ordinarylight_secondary_capture_hit(path.metadata.w, bounce, ordinarylight_secondary_primary_valid(path_index)))
    {
        vec4 captured_position = ordinarylight_secondary_capture_position(hit);
        ordinarylight_store_secondary_hit(path_index, captured_position, normal);
    }
    MaterialEvaluation wave_surface_response = MaterialEvaluation(vec3(0.0), vec3(0.0), 0.0, 0.0, 0.0, 0.0, vec3(0.0), 0.0, 0.0, vec3(0.0), vec3(0.0), 0.0, 0.0);
#if WAVE_CUSTOM_MATERIAL_PROGRAM
    vec2 wave_material_uv = (((attributes[(primitive * uint(3))].texcoord.xy * weights.x) + (attributes[((primitive * uint(3)) + uint(1))].texcoord.xy * weights.y)) + (attributes[((primitive * uint(3)) + uint(2))].texcoord.xy * weights.z));
    wave_surface_response = waveApplyMaterialProgram(material, normal, wave_material_uv, direction, entering, primitive, weights, float(bounce));
    if ((wave_surface_response.custom_scattering > 0.5))
    {
        float wave_current_ior = stacks[path_index].ior[(medium_depth - uint(1))];
        float wave_exterior_ior = (entering ? max(material.ior_distance.x, 1.0001) : ((medium_depth > uint(1)) ? stacks[path_index].ior[(medium_depth - uint(2))] : 1.0));
        float wave_random_u = randomFloat(rng);
        float wave_random_v = randomFloat(rng);
        wave_surface_response = evaluateMaterial(material, normal, wave_material_uv, direction, entering, wave_random_u, wave_random_v, float(bounce), wave_current_ior, wave_exterior_ior);
    }
#endif
    bool emission_visible = ordinarylight_secondary_emission_visible(entering, material.ior_distance.w);
    if (emission_visible)
    {
        float emission_mis = ordinarylight_emissive_hit_mis(((path.metadata.w & PATH_PREVIOUS_DIFFUSE_BIT) != uint(0)), material.emission_metallic.rgb, a, b, c, geometric_normal, direction, distance, (material.ior_distance.w > 0.5), push.area_light_weight, push.secondary_area_light_samples, ((path.metadata.w & PATH_PREVIOUS_UNIFIED_NEE_BIT) != uint(0)), unifiedAreaDomainProbability(), pathPreviousPdf(path));
        path.radiance.rgb = (path.radiance.rgb + ordinarylight_emission_contribution(path.throughput.rgb, material.emission_metallic.rgb, emission_mis));
    }
    uint next_bounce = ordinarylight_secondary_next_bounce(bounce);
    if (ordinarylight_secondary_bounce_terminates(next_bounce, push.max_bounces))
    {
        setPathBounce(path, next_bounce);
        path.metadata.w = ordinarylight_primary_deactivate(path.metadata.w);
        return false;
    }
    vec3 next_direction = vec3(0);
    float bsdf_pdf = 0.0;
#if WAVE_OPAQUE_SCENE
    float transmission = 0.0;
#else
    float transmission = material.attenuation_transmission.a;
#endif
    if ((wave_surface_response.custom_scattering > 0.5))
    {
        int wave_event = int((wave_surface_response.event + 0.5));
        if ((wave_event == 0))
        {
            path.metadata.w = (path.metadata.w & (~PATH_ACTIVE_BIT));
            return false;
        }
        next_direction = normalize(wave_surface_response.next_direction);
        bsdf_pdf = max(wave_surface_response.pdf, 1e-06);
        path.throughput.rgb = (path.throughput.rgb * (wave_surface_response.weight / bsdf_pdf));
        transmission = ((wave_event == 3) ? 1.0 : 0.0);
        if ((wave_event == 3))
        {
            float target_ior = max(material.ior_distance.x, 1.0001);
            if ((entering && (medium_depth < WAVE_MAX_MEDIUM_STACK_DEPTH)))
            {
                stacks[path_index].ior[medium_depth] = target_ior;
                medium_depth = (medium_depth + uint(1));
            }
            else
            {
                if (((!entering) && (medium_depth > uint(1))))
                {
                    medium_depth = (medium_depth - uint(1));
                }
            }
        }
    }
    else
    {
        if ((transmission > 0.001))
        {
            float current_ior = ordinarylight_medium_ior(path_index, (medium_depth - uint(1)));
            float previous_medium_ior = ((medium_depth > uint(1)) ? ordinarylight_medium_ior(path_index, (medium_depth - uint(2))) : 1.0);
            float target_ior = ordinarylight_secondary_target_ior(entering, material.ior_distance.x, previous_medium_ior, medium_depth);
            vec3 refracted = ordinarylight_secondary_refracted_direction(direction, normal, current_ior, target_ior);
            next_direction = ordinarylight_primary_resolve_transmission_direction(refracted, direction, normal);
            if (ordinarylight_secondary_enters_medium(refracted, entering, medium_depth, WAVE_MAX_MEDIUM_STACK_DEPTH))
            {
                ordinarylight_set_medium_ior(path_index, medium_depth, target_ior);
            }
            medium_depth = ordinarylight_secondary_medium_depth(refracted, entering, medium_depth, WAVE_MAX_MEDIUM_STACK_DEPTH);
            float optical_distance = (entering ? 0.0 : distance);
            if ((material.advanced1.z > 0.5))
            {
                optical_distance = material.advanced1.w;
            }
            vec3 absorption = pow(max(material.attenuation_transmission.rgb, vec3(1e-06)), vec3((optical_distance / max(material.ior_distance.y, 1e-06))));
            vec3 tint = mix(vec3(1.0), material.base_roughness.rgb, material.advanced1.z);
            path.throughput.rgb = (path.throughput.rgb * ((absorption * tint) * transmission));
        }
        else
        {
            float nee_probability = ordinarylight_secondary_nee_probability(push.secondary_nee_probability);
            bool sample_direct = selectSecondaryNee(nee_probability, path.metadata.x, path.metadata.y, next_bounce);
            if (sample_direct)
            {
                vec3 direct = samplePointLights(hit, normal, direction, material);
                if ((push.unified_secondary_nee != uint(0)))
                {
                    direct = (direct + sampleUnifiedSecondaryLight(hit, normal, direction, material, rng));
                }
                else
                {
                    uint light_samples = ordinarylight_secondary_area_sample_count(push.secondary_area_light_samples);
                    vec3 area_direct = vec3(0.0);
                    uint sample_index = uint(0);
                    while ((sample_index < light_samples))
                    {
                        area_direct = (area_direct + sampleAreaLight(hit, normal, direction, material, rng, sample_index, light_samples));
                        sample_index = (sample_index + 1);
                    }
                    direct = (direct + ordinarylight_secondary_average_contribution(area_direct, light_samples));
                    uint environment_samples = ordinarylight_secondary_environment_sample_count(push.environment_samples);
                    if ((environment_samples > uint(0)))
                    {
                        vec3 environment_direct = vec3(0.0);
                        sample_index = uint(0);
                        while ((sample_index < environment_samples))
                        {
                            environment_direct = (environment_direct + sampleEnvironment(hit, normal, direction, material, rng, environment_samples));
                            sample_index = (sample_index + 1);
                        }
                        direct = (direct + ordinarylight_secondary_average_contribution(environment_direct, environment_samples));
                    }
                }
                path.radiance.rgb = (path.radiance.rgb + ordinarylight_secondary_direct_contribution(path.throughput.rgb, direct, nee_probability));
            }
            vec3 bsdf_weight = vec3(0);
            float sampled_specular = float(0.0);
            samplePbr(material, normal, direction, rng, next_direction, bsdf_weight, bsdf_pdf, sampled_specular);
            path.throughput.rgb = ordinarylight_secondary_scatter_throughput(path.throughput.rgb, bsdf_weight);
            cone_spread = ordinarylight_primary_scattered_cone_spread(cone_spread, material.base_roughness.a);
        }
    }
    next_direction = ordinarylight_primary_continuation_direction(next_direction);
    setPathBounce(path, next_bounce);
    path.metadata.w = ordinarylight_primary_continuation_flags(path.metadata.w, medium_depth, transmission, (push.unified_secondary_nee != uint(0)));
    setPathPreviousPdf(path, ordinarylight_primary_previous_pdf(pathPreviousPdf(path), bsdf_pdf, transmission));
    if (ordinarylight_secondary_roulette_enabled(push.russian_roulette_start, next_bounce, transmission))
    {
        float survival = ordinarylight_secondary_survival_probability(path.throughput.rgb, push.russian_roulette_min_survival);
        if ((!ordinarylight_secondary_survives(randomFloat(rng), survival)))
        {
            path.metadata.w = ordinarylight_primary_deactivate(path.metadata.w);
            return false;
        }
        path.throughput.rgb = ordinarylight_secondary_survival_throughput(path.throughput.rgb, survival);
    }
    origin = ordinarylight_primary_continuation_origin(hit, next_direction);
    direction = next_direction;
    return true;
}

uint ordinarylight_secondary_stop_bounce(bool hybrid, uint inline_bounces, uint maximum_bounces);
void ordinarylight_trace_remaining(inout WavePathState path, inout vec3 origin, inout vec3 direction, uint path_index, inout uint medium_depth, inout uint rng, inout float cone_width, inout float cone_spread, uint stop_bounce);
void traceRemaining(inout WavePathState path, inout vec3 origin, inout vec3 direction, uint path_index, uint medium_depth, inout uint rng, inout float cone_width, inout float cone_spread)
{
    uint stop_bounce = ordinarylight_secondary_stop_bounce((WAVE_HYBRID != 0), push.inline_bounces, push.max_bounces);
    ordinarylight_trace_remaining(path, origin, direction, path_index, medium_depth, rng, cone_width, cone_spread, stop_bounce);
}
#endif

#if !WAVE_CONTINUATION
uint primaryRestirHistoryValid()
{
#if WAVE_CAMERA_RESTIR_POLICY
    if ((camera.restir_policy.x != uint(0)))
    {
        return camera.restir_policy.y;
    }
#endif
    return push.restir_history_valid;
}

uint primaryRestirHistoryLimit()
{
#if WAVE_CAMERA_RESTIR_POLICY
    if ((camera.restir_policy.x != uint(0)))
    {
        return camera.restir_policy.z;
    }
#endif
    return push.restir_history_limit;
}

void applyMaterialTextures(inout MaterialData material, vec2 uv0, vec2 uv1, float uv0_footprint, float uv1_footprint);
vec3 applyNormalTexture(MaterialData material, vec2 uv0, vec2 uv1, float uv0_footprint, float uv1_footprint, vec3 shading_normal, vec4 tangent_data);
float areaLightCandidateVisibility(vec3 hit, vec3 normal, vec3 direction, float distance_to_light);
vec3 cosineHemisphere(vec3 normal, float random_u, float random_v);
float directLightReservoirNormalization(DirectLightReservoir reservoir);
DirectLightReservoir emptyDirectLightReservoir();
vec2 encodeEnvironmentCandidateDirection(vec3 direction);
vec3 environmentColor(vec3 direction);
vec3 evaluateAreaLightCandidate(AreaLightCandidate candidate, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, out vec3 direction, out float distance_to_light);
vec3 evaluateEnvironmentCandidate(vec2 encoded_direction, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, float technique_probability, out vec3 direction, out float distance_to_light);
MaterialEvaluation evaluateMaterial(inout MaterialData material, inout vec3 normal, vec2 uv, vec3 direction, bool entering, float random_u, float random_v, float bounce_index, float current_ior, float exterior_ior);
vec3 evaluateUnifiedPrimaryCandidate(AreaLightCandidate candidate, vec3 hit, vec3 normal, vec3 incoming, MaterialData material, uint sample_count, out vec3 direction, out float distance_to_light);
AreaLightCandidate generateAreaLightCandidate(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count);
AreaLightCandidate generateUnifiedPrimaryCandidate(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count);
uint hashValue(uint value);
void integrateVolumesBeforeSurface(vec3 origin, vec3 direction, float surface_distance, inout vec3 radiance, inout vec3 throughput);
DirectLightReservoir limitDirectLightReservoir(DirectLightReservoir reservoir, float maximum_samples);
DirectLightReservoir loadPreviousDirectLightReservoir(uint reservoir_index);
DirectLightReservoir loadPreviousEnvironmentReservoir(uint reservoir_index, uint pixel_count);
bool materialHasTextures(MaterialData material);
bool mergeBalancedDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float active_proposals_over_target_sum, float random_value);
bool mergeCanonicalDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float random_value);
bool mergeDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float random_value);
bool mergePairwiseDirectLightReservoir(inout DirectLightReservoir destination, DirectLightReservoir source, float target_at_current_surface, float target_at_source_surface, float random_value);
void ordinarylight_clear_secondary_path(uint path_index);
void ordinarylight_deactivate_stored_path(uint path_index);
bool ordinarylight_enqueue_continuation(uint output_index, vec4 origin_tmin, vec4 direction_tmax, uint path_index, float cone_width, float cone_spread);
vec3 ordinarylight_primary_apply_bsdf_weight(vec3 throughput, vec3 bsdf_weight);
vec3 ordinarylight_primary_barycentric_weights(vec2 barycentrics);
bool ordinarylight_primary_capture_secondary(uint flags, float transmission);
float ordinarylight_primary_cone_spread(vec3 camera_up, uint image_height);
vec3 ordinarylight_primary_continuation_direction(vec3 direction);
uint ordinarylight_primary_continuation_flags(uint previous_flags, uint medium_depth, float transmission, bool unified_nee);
vec3 ordinarylight_primary_continuation_origin(vec3 position, vec3 direction);
vec3 ordinarylight_primary_correct_mapped_normal(vec3 mapped_normal, vec3 geometric_normal);
uint ordinarylight_primary_deactivate(uint flags);
vec3 ordinarylight_primary_emission(vec3 emission, bool entering, bool two_sided);
bool ordinarylight_primary_enters_medium(vec3 refracted, bool entering);
vec3 ordinarylight_primary_geometric_normal(vec3 a, vec3 b, vec3 c);
vec3 ordinarylight_primary_hit_position(vec3 ray_origin, vec3 incoming, float distance);
vec4 ordinarylight_primary_hit_position_payload(float distance);
float ordinarylight_primary_initial_medium_ior();
vec4 ordinarylight_primary_interpolate_vec4(vec4 value_a, vec4 value_b, vec4 value_c, vec3 weights);
uvec4 ordinarylight_primary_invalid_material();
vec4 ordinarylight_primary_invalid_position();
bool ordinarylight_primary_is_entering(vec3 incoming, vec3 geometric_normal);
uint ordinarylight_primary_medium_depth(bool entered_medium);
vec3 ordinarylight_primary_oriented_normal(vec3 shading_normal, bool entering);
uvec4 ordinarylight_primary_packed_payload(uint value);
uint ordinarylight_primary_path_flags(bool indirect_capture);
uint ordinarylight_primary_path_identity(uint frame_index, uint sample_index);
float ordinarylight_primary_previous_pdf(float previous_pdf, float bsdf_pdf, float transmission);
vec3 ordinarylight_primary_ray_direction(vec3 forward, vec3 right, vec3 up, vec2 ndc, float aspect, int projection);
vec4 ordinarylight_primary_ray_direction_payload(vec3 direction);
vec3 ordinarylight_primary_ray_origin(vec3 origin, vec3 right, vec3 up, vec2 ndc, float aspect, int projection);
vec4 ordinarylight_primary_ray_origin_payload(vec3 origin);
vec3 ordinarylight_primary_refracted_direction(vec3 incoming, vec3 normal, float target_ior);
vec3 ordinarylight_primary_resolve_transmission_direction(vec3 refracted, vec3 incoming, vec3 normal);
uint ordinarylight_primary_rng_seed(uint pixel_index, uint frame_index, uint sample_index);
uint ordinarylight_primary_rng_step(uint value);
float ordinarylight_primary_rng_value(uint value);
float ordinarylight_primary_scattered_cone_spread(float cone_spread, float roughness);
vec3 ordinarylight_primary_shading_normal(vec3 normal_a, vec3 normal_b, vec3 normal_c, vec3 weights, vec3 geometric_normal);
bool ordinarylight_primary_should_terminate(uint max_bounces);
float ordinarylight_primary_surface_class(float transmission, float emissive, bool opaque_scene);
float ordinarylight_primary_target_ior(float material_ior);
float ordinarylight_primary_transmission(float material_transmission, bool opaque_scene);
vec4 ordinarylight_primary_triangle_tangent(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec2 uv_a, vec2 uv_b, vec2 uv_c, vec3 shading_normal);
float ordinarylight_primary_uv_density(vec3 vertex_a, vec3 vertex_b, vec3 vertex_c, vec2 uv_a, vec2 uv_b, vec2 uv_c);
void ordinarylight_secondary_reorder(uint hint);
void ordinarylight_set_medium_ior(uint path_index, uint depth, float value);
void ordinarylight_store_path(uint path_index, WavePathState path);
void ordinarylight_store_secondary_primary(uint path_index, vec3 throughput, vec3 radiance, float pdf, float sampled_specular, float specular_probability, vec3 position, float roughness, uint primitive, vec2 barycentrics, uint instance_key);
float pathPreviousPdf(WavePathState path);
float pbrSpecularProbability(MaterialData material);
void preparePrimaryPbr(MaterialData material, vec3 normal, vec3 view);
uint primaryRestirHistoryLimit();
uint primaryRestirHistoryValid();
void profileWork(uint counter, uint amount);
float randomFloat(inout uint state);
bool reprojectRestir(vec3 world_position, out ivec2 previous_pixel);
uint reserveOutputIndex();
bool restirHistorySurfaceCompatible(ivec2 history_pixel, vec3 position, vec3 shading_normal, float distance, float surface_class, uint material_signature, bool temporal_center, out vec4 old_position, out vec4 old_normal);
bool restirHistorySurfaceMatches(ivec2 history_pixel, vec3 position, vec3 shading_normal, float distance, float surface_class, uint material_signature, bool temporal_center);
uint restirMaterialSignature(MaterialData material);
uint restirPackNormalClass(vec3 normal, float surface_class);
ivec2 restirSpatialOffset(uint index, int radius);
vec3 sampleAreaLight(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_index, uint sample_count);
vec3 sampleEnvironment(vec3 hit, vec3 normal, vec3 incoming, MaterialData material, inout uint rng, uint sample_count);
void samplePbr(MaterialData material, vec3 normal, vec3 incoming, inout uint rng, out vec3 outgoing, out vec3 weight, out float pdf, out float sampled_specular);
vec3 samplePointLights(vec3 hit, vec3 normal, vec3 incoming, MaterialData material);
void setPathBounce(inout WavePathState path, uint bounce);
void setPathPreviousPdf(inout WavePathState path, float pdf);
void setPathRng(inout WavePathState path, uint rng);
void storeCurrentDirectLightReservoir(uint reservoir_index, DirectLightReservoir reservoir);
void storeCurrentEnvironmentReservoir(uint reservoir_index, uint pixel_count, DirectLightReservoir reservoir);
bool textureBindingUsesUv1(float binding_index_value);
void traceRemaining(inout WavePathState path, inout vec3 origin, inout vec3 direction, uint path_index, uint medium_depth, inout uint rng, inout float cone_width, inout float cone_spread);
bool updateDirectLightReservoir(inout DirectLightReservoir reservoir, uint light_index, vec2 barycentrics, float target, float candidate_weight, float represented_samples, float random_value);
MaterialEvaluation waveApplyMaterialProgram(inout MaterialData material, vec3 normal, vec2 uv, vec3 direction, bool entering, uint primitive, vec3 weights, float bounce_index);
void processPrimaryPixel(uvec2 local_pixel)
{
#if WAVE_WORK_COUNTERS
    profile_bounce = uint(0);
#endif
    if (any(greaterThanEqual(local_pixel, push.tile_frame.xy)))
    {
        return;
    }
    uvec2 pixel = (push.image_tile.zw + local_pixel);
    if (any(greaterThanEqual(pixel, push.image_tile.xy)))
    {
        return;
    }
    uint path_index = ((local_pixel.y * push.tile_frame.x) + local_pixel.x);
    if ((path_index >= output_queue.capacity))
    {
        return;
    }
    uint pixel_index = ((pixel.y * push.image_tile.x) + pixel.x);
    uint restir_reservoir_count = max(push.tile_frame.z, uint(1));
    uint restir_stream = min(push.tile_frame.w, (restir_reservoir_count - uint(1)));
    uint restir_reservoir_index = ((pixel_index * restir_reservoir_count) + restir_stream);
#if WAVE_SHARED_PRIMARY_RESERVOIRS > 0
    uint direct_stream_count = ((push.restir_di != uint(0)) ? uint(WAVE_SHARED_PRIMARY_RESERVOIRS) : uint(1));
    restir_reservoir_count = (restir_reservoir_count * direct_stream_count);
    restir_stream = (push.tile_frame.w * direct_stream_count);
    restir_reservoir_index = ((pixel_index * restir_reservoir_count) + restir_stream);
#else
    uint direct_stream_count = uint(1);
#endif
    uint frame_index = uint((camera.origin.w + 0.5));
    if ((push.restir_di != uint(0)))
    {
        uint stream = uint(0);
        while ((stream < direct_stream_count))
        {
            storeCurrentDirectLightReservoir((restir_reservoir_index + stream), emptyDirectLightReservoir());
            stream = (stream + 1);
        }
    }
    uint rng = ordinarylight_primary_rng_seed(pixel_index, frame_index, push.tile_frame.w);
    rng = ordinarylight_primary_rng_step(rng);
    float jitter_x = ordinarylight_primary_rng_value(rng);
    rng = ordinarylight_primary_rng_step(rng);
    float jitter_y = ordinarylight_primary_rng_value(rng);
    vec2 jitter = vec2(jitter_x, jitter_y);
    if ((floatBitsToUint(camera.right.w) != uint(0)))
    {
        jitter = unpackHalf2x16(floatBitsToUint(camera.right.w));
    }
    vec2 ndc = ((((vec2(pixel) + jitter) / vec2(push.image_tile.xy)) * 2.0) - 1.0);
    float aspect = (float(push.image_tile.x) / float(push.image_tile.y));
    int camera_projection = int((camera.up.w + 0.5));
    vec3 ray_origin = ordinarylight_primary_ray_origin(camera.origin.xyz, camera.right.xyz, camera.up.xyz, ndc, aspect, camera_projection);
    vec3 incoming = ordinarylight_primary_ray_direction(camera.forward.xyz, camera.right.xyz, camera.up.xyz, ndc, aspect, camera_projection);
    WavePathState path = WavePathState(vec4(0), vec4(0), uvec4(0));
    path.throughput = vec4(1.0);
    path.radiance = vec4(0.0);
    bool indirect_capture_pixel = (push.indirect_secondary_capture != uint(0));
    if ((indirect_capture_pixel && (push.indirect_capture_stride > uint(1))))
    {
        uvec2 capture_offset = uvec2((push.indirect_capture_stride / uint(2)));
        indirect_capture_pixel = all(equal((pixel % push.indirect_capture_stride), capture_offset));
    }
    path.metadata = uvec4(pixel_index, ordinarylight_primary_path_identity(frame_index, push.tile_frame.w), rng, ordinarylight_primary_path_flags(indirect_capture_pixel));
    setPathBounce(path, uint(0));
#if !WAVE_OPAQUE_SCENE
    ordinarylight_set_medium_ior(path_index, uint(0), ordinarylight_primary_initial_medium_ior());
#endif
    if (indirect_capture_pixel)
    {
        ordinarylight_clear_secondary_path(path_index);
    }
    rayQueryEXT query;
#if WAVE_WORK_COUNTERS
    profileWork(uint(0), uint(1));
#endif
    rayQueryInitializeEXT(query, scene_tlas, gl_RayFlagsOpaqueEXT, 1, ray_origin, 0.001, incoming, 1e+30);
    while (rayQueryProceedEXT(query))
    {
    }
    bool surface_hit = (rayQueryGetIntersectionTypeEXT(query, true) == gl_RayQueryCommittedIntersectionTriangleEXT);
    float distance = (surface_hit ? rayQueryGetIntersectionTEXT(query, true) : 1e+30);
#if !WAVE_SURFACE_ONLY
    integrateVolumesBeforeSurface(ray_origin, incoming, distance, path.radiance.rgb, path.throughput.rgb);
#endif
    if (((!surface_hit) || (max(path.throughput.r, max(path.throughput.g, path.throughput.b)) < 0.0001)))
    {
#if WAVE_WORK_COUNTERS
        profileWork(uint(4), uint(1));
#endif
        if ((push.gbuffer_enabled != uint(0)))
        {
            imageStore(position_image, ivec2(pixel), ordinarylight_primary_invalid_position());
            imageStore(normal_image, ivec2(pixel), ordinarylight_primary_packed_payload(uint(0)));
            imageStore(material_image, ivec2(pixel), ordinarylight_primary_invalid_material());
        }
        if ((!surface_hit))
        {
            path.radiance.rgb = (path.radiance.rgb + (path.throughput.rgb * environmentColor(incoming)));
        }
        path.metadata.w = ordinarylight_primary_deactivate(path.metadata.w);
        ordinarylight_store_path(path_index, path);
        return;
    }
#if WAVE_WORK_COUNTERS
    profileWork(uint(3), uint(1));
#endif
    uint instance_key = rayQueryGetIntersectionInstanceCustomIndexEXT(query, true);
    uint primitive = (rayQueryGetIntersectionPrimitiveIndexEXT(query, true) + instance_key);
    vec2 barycentrics = rayQueryGetIntersectionBarycentricsEXT(query, true);
    float cone_spread = ordinarylight_primary_cone_spread(camera.up.xyz, push.image_tile.y);
    float cone_width = (distance * cone_spread);
    vec3 a = vertices[((primitive * uint(3)) + uint(0))].xyz;
    vec3 b = vertices[((primitive * uint(3)) + uint(1))].xyz;
    vec3 c = vertices[((primitive * uint(3)) + uint(2))].xyz;
    vec3 position = ordinarylight_primary_hit_position(ray_origin, incoming, distance);
    vec3 geometric_normal = ordinarylight_primary_geometric_normal(a, b, c);
    vec3 weights = ordinarylight_primary_barycentric_weights(barycentrics);
    vec3 shading_normal = ordinarylight_primary_shading_normal(attributes[((primitive * uint(3)) + uint(0))].normal.xyz, attributes[((primitive * uint(3)) + uint(1))].normal.xyz, attributes[((primitive * uint(3)) + uint(2))].normal.xyz, weights, geometric_normal);
    bool entering = ordinarylight_primary_is_entering(incoming, geometric_normal);
    vec3 normal = ordinarylight_primary_oriented_normal(shading_normal, entering);
    MaterialData material = materials[primitive];
#if WAVE_SER
    uint ser_hint = uint((material.attenuation_transmission.a > 0.001));
    ser_hint = (ser_hint | (uint((material.emission_metallic.a > 0.5)) << uint(1)));
    ser_hint = (ser_hint | (uint((material.emission_metallic.w > 0.5)) << uint(2)));
    ser_hint = (ser_hint | (uint(clamp((material.base_roughness.w * 7.0), 0.0, 7.0)) << uint(3)));
    ser_hint = (ser_hint | (uint(materialHasTextures(material)) << uint(6)));
    ordinarylight_secondary_reorder(ser_hint);
#endif
    uint material_signature = restirMaterialSignature(material);
    if ((push.object_effect_ranges[0].x < push.object_effect_ranges[0].y))
    {
        material_signature = (material_signature & uint(536870911));
        uint effect_index = uint(0);
        while ((effect_index < uint(4)))
        {
            uvec4 ranges = push.object_effect_ranges[(effect_index >> uint(1))];
            uint start = ranges[((effect_index & uint(1)) * uint(2))];
            uint end = ranges[(((effect_index & uint(1)) * uint(2)) + uint(1))];
            if ((((start < end) && (primitive >= start)) && (primitive < end)))
            {
                material_signature = (material_signature | ((effect_index + uint(1)) << uint(29)));
                break;
            }
            effect_index = (effect_index + 1);
        }
    }
#if WAVE_UNTEXTURED_PRIMARY
    bool material_textured = false;
    material.texture_parameters.w = 1.0;
#else
    bool material_textured = materialHasTextures(material);
    vec4 interpolated_uv = ordinarylight_primary_interpolate_vec4(attributes[((primitive * uint(3)) + uint(0))].texcoord, attributes[((primitive * uint(3)) + uint(1))].texcoord, attributes[((primitive * uint(3)) + uint(2))].texcoord, weights);
    vec2 uv0 = interpolated_uv.xy;
    vec2 uv1 = interpolated_uv.zw;
    float uv0_footprint = 0.0;
    float uv1_footprint = 0.0;
    if (material_textured)
    {
        uv0_footprint = (cone_width * attributes[((primitive * uint(3)) + uint(0))].normal.w);
        uv1_footprint = (cone_width * ordinarylight_primary_uv_density(a, b, c, attributes[((primitive * uint(3)) + uint(0))].texcoord.zw, attributes[((primitive * uint(3)) + uint(1))].texcoord.zw, attributes[((primitive * uint(3)) + uint(2))].texcoord.zw));
    }
    applyMaterialTextures(material, uv0, uv1, uv0_footprint, uv1_footprint);
    vec4 tangent_data = ordinarylight_primary_interpolate_vec4(attributes[((primitive * uint(3)) + uint(0))].tangent, attributes[((primitive * uint(3)) + uint(1))].tangent, attributes[((primitive * uint(3)) + uint(2))].tangent, weights);
    if (textureBindingUsesUv1(material.texture_indices.w))
    {
        tangent_data = ordinarylight_primary_triangle_tangent(a, b, c, attributes[((primitive * uint(3)) + uint(0))].texcoord.zw, attributes[((primitive * uint(3)) + uint(1))].texcoord.zw, attributes[((primitive * uint(3)) + uint(2))].texcoord.zw, shading_normal);
    }
    shading_normal = applyNormalTexture(material, uv0, uv1, uv0_footprint, uv1_footprint, shading_normal, tangent_data);
    shading_normal = ordinarylight_primary_correct_mapped_normal(shading_normal, geometric_normal);
    normal = (entering ? shading_normal : (-shading_normal));
#endif
    MaterialEvaluation wave_surface_response = MaterialEvaluation(vec3(0.0), vec3(0.0), 0.0, 0.0, 0.0, 0.0, vec3(0.0), 0.0, 0.0, vec3(0.0), vec3(0.0), 0.0, 0.0);
#if WAVE_CUSTOM_MATERIAL_PROGRAM
    vec2 wave_material_uv = (((attributes[(primitive * uint(3))].texcoord.xy * weights.x) + (attributes[((primitive * uint(3)) + uint(1))].texcoord.xy * weights.y)) + (attributes[((primitive * uint(3)) + uint(2))].texcoord.xy * weights.z));
    wave_surface_response = waveApplyMaterialProgram(material, normal, wave_material_uv, incoming, entering, primitive, weights, 0.0);
    if ((wave_surface_response.custom_scattering > 0.5))
    {
        float wave_current_ior = 1.0;
        float wave_exterior_ior = max(material.ior_distance.x, 1.0001);
        float wave_random_u = randomFloat(rng);
        float wave_random_v = randomFloat(rng);
        wave_surface_response = evaluateMaterial(material, normal, wave_material_uv, incoming, entering, wave_random_u, wave_random_v, 0.0, wave_current_ior, wave_exterior_ior);
    }
#endif
#if WAVE_OPAQUE_SCENE
    float surface_class = ordinarylight_primary_surface_class(material.attenuation_transmission.a, material.emission_metallic.a, true);
#else
    float surface_class = ordinarylight_primary_surface_class(material.attenuation_transmission.a, material.emission_metallic.a, false);
#endif
    if ((push.gbuffer_enabled != uint(0)))
    {
        imageStore(position_image, ivec2(pixel), ordinarylight_primary_hit_position_payload(distance));
        imageStore(normal_image, ivec2(pixel), ordinarylight_primary_packed_payload(restirPackNormalClass(shading_normal, surface_class)));
        imageStore(material_image, ivec2(pixel), ordinarylight_primary_packed_payload(material_signature));
    }
    path.radiance.rgb = (path.radiance.rgb + ordinarylight_primary_emission(material.emission_metallic.rgb, entering, (material.ior_distance.w > 0.5)));
    if (ordinarylight_primary_should_terminate(push.max_bounces))
    {
        setPathBounce(path, uint(1));
        path.metadata.w = ordinarylight_primary_deactivate(path.metadata.w);
        ordinarylight_store_path(path_index, path);
        return;
    }
    vec3 next_direction = vec3(0);
    float bsdf_pdf = 0.0;
#if WAVE_OPAQUE_SCENE
    float transmission = ordinarylight_primary_transmission(material.attenuation_transmission.a, true);
#else
    float transmission = ordinarylight_primary_transmission(material.attenuation_transmission.a, false);
#endif
    uint medium_depth = uint(1);
    float sampled_specular = 0.0;
    vec3 primary_specular = vec3(0.0);
    vec3 indirect_specular_fraction = vec3(1.0);
    if ((wave_surface_response.custom_scattering > 0.5))
    {
        int wave_event = int((wave_surface_response.event + 0.5));
        if ((wave_event == 0))
        {
            path.metadata.w = (path.metadata.w & (~PATH_ACTIVE_BIT));
            setPathRng(path, rng);
            paths[path_index] = path;
            return;
        }
        next_direction = normalize(wave_surface_response.next_direction);
        bsdf_pdf = max(wave_surface_response.pdf, 1e-06);
        path.throughput.rgb = (path.throughput.rgb * (wave_surface_response.weight / bsdf_pdf));
        transmission = ((wave_event == 3) ? 1.0 : 0.0);
        if ((wave_event == 3))
        {
            float target_ior = max(material.ior_distance.x, 1.0001);
            if ((entering && (medium_depth < WAVE_MAX_MEDIUM_STACK_DEPTH)))
            {
                stacks[path_index].ior[medium_depth] = target_ior;
                medium_depth = (medium_depth + uint(1));
            }
            else
            {
                if (((!entering) && (medium_depth > uint(1))))
                {
                    medium_depth = (medium_depth - uint(1));
                }
            }
        }
    }
    else
    {
        if ((transmission > 0.001))
        {
            float target_ior = ordinarylight_primary_target_ior(material.ior_distance.x);
            vec3 refracted_direction = ordinarylight_primary_refracted_direction(incoming, normal, target_ior);
            next_direction = ordinarylight_primary_resolve_transmission_direction(refracted_direction, incoming, normal);
            bool entered_medium = ordinarylight_primary_enters_medium(refracted_direction, entering);
            if (entered_medium)
            {
                ordinarylight_set_medium_ior(path_index, uint(1), target_ior);
            }
            medium_depth = ordinarylight_primary_medium_depth(entered_medium);
            float optical_distance = ((material.advanced1.z > 0.5) ? material.advanced1.w : 0.0);
            vec3 absorption = pow(max(material.attenuation_transmission.rgb, vec3(1e-06)), vec3((optical_distance / max(material.ior_distance.y, 1e-06))));
            vec3 tint = mix(vec3(1.0), material.base_roughness.rgb, material.advanced1.z);
            path.throughput.rgb = (path.throughput.rgb * ((absorption * tint) * transmission));
        }
        else
        {
#if WAVE_PRODUCTION_RESTIR && WAVE_PREPARED_PRIMARY_PBR
            preparePrimaryPbr(material, normal, (-incoming));
#endif
            path.radiance.rgb = (path.radiance.rgb + samplePointLights(position, normal, incoming, material));
            primary_specular = (primary_specular + transportPointSpecular);
            uint light_samples = clamp(push.area_light_samples, uint(1), uint(16));
            uint first_restir_stream = restir_stream;
            uint direct_stream = uint(0);
            while ((direct_stream < direct_stream_count))
            {
                restir_stream = (first_restir_stream + direct_stream);
                restir_reservoir_index = ((pixel_index * restir_reservoir_count) + restir_stream);
                vec3 radiance_before_direct = path.radiance.rgb;
                vec3 specular_before_direct = primary_specular;
                if (((push.restir_di != uint(0)) && (push.area_light_count > uint(0))))
                {
                    uint candidate_count = clamp(push.restir_candidate_count, uint(1), uint(4));
                    DirectLightReservoir reservoir = emptyDirectLightReservoir();
                    uint sample_index = uint(0);
                    while ((sample_index < candidate_count))
                    {
                        AreaLightCandidate candidate = ((WAVE_UNIFIED_PRIMARY_RESTIR != uint(0)) ? generateUnifiedPrimaryCandidate(position, normal, incoming, material, rng, sample_index, candidate_count) : generateAreaLightCandidate(position, normal, incoming, material, rng, sample_index, candidate_count));
                        updateDirectLightReservoir(reservoir, candidate.light_index, candidate.barycentrics, candidate.target, candidate.target, 1.0, randomFloat(rng));
                        sample_index = (sample_index + 1);
                    }
                    if ((primaryRestirHistoryValid() != uint(0)))
                    {
                        ivec2 previous_pixel = ivec2(0);
                        if (reprojectRestir(position, previous_pixel))
                        {
                            uint spatial_count = ((push.restir_spatial_reuse != uint(0)) ? clamp(push.restir_spatial_neighbors, uint(1), uint(8)) : uint(0));
                            uint spatial_rotation = (hashValue((pixel_index ^ frame_index)) & uint(7));
                            uint reuse_index = uint(0);
                            while ((reuse_index <= spatial_count))
                            {
                                ivec2 history_pixel = previous_pixel;
                                if ((reuse_index > uint(0)))
                                {
                                    history_pixel = (history_pixel + restirSpatialOffset(((reuse_index - uint(1)) + spatial_rotation), int(push.restir_spatial_radius)));
                                }
                                bool inside = (all(greaterThanEqual(history_pixel, ivec2(0))) && all(lessThan(history_pixel, ivec2(push.image_tile.xy))));
                                bool geometry_valid = false;
                                bool history_source_present = false;
                                DirectLightReservoir history = emptyDirectLightReservoir();
                                if (inside)
                                {
                                    uint previous_index = ((uint(history_pixel.y) * push.image_tile.x) + uint(history_pixel.x));
                                    history = loadPreviousDirectLightReservoir(((previous_index * restir_reservoir_count) + restir_stream));
                                    history_source_present = (history.data.x != uint(4294967295));
                                    if (history_source_present)
                                    {
                                        geometry_valid = restirHistorySurfaceMatches(history_pixel, position, shading_normal, distance, surface_class, material_signature, (reuse_index == uint(0)));
                                    }
                                }
#if WAVE_SHARED_PRIMARY_RESERVOIRS > 0
                                if ((!geometry_valid))
                                {
                                    history = emptyDirectLightReservoir();
                                }
#endif
                                if (geometry_valid)
                                {
                                    float current_count = unpackHalf2x16(reservoir.data.w).y;
                                    float remaining_history = max((float(primaryRestirHistoryLimit()) - current_count), 0.0);
                                    float source_history_limit = ((spatial_count > uint(0)) ? min(remaining_history, 1.0) : remaining_history);
                                    history = limitDirectLightReservoir(history, source_history_limit);
                                    if ((unpackHalf2x16(history.data.w).y <= 0.0))
                                    {
                                        history = emptyDirectLightReservoir();
                                    }
                                }
                                if ((history.data.x != uint(4294967295)))
                                {
#if WAVE_WORK_COUNTERS
                                    profileWork(uint(11), uint(1));
#endif
                                    AreaLightCandidate history_candidate = AreaLightCandidate(uint(0), vec2(0), float(0));
                                    history_candidate.light_index = history.data.x;
                                    history_candidate.barycentrics = unpackHalf2x16(history.data.y);
                                    history_candidate.target = 0.0;
                                    vec3 history_direction = vec3(0);
                                    float history_distance = float(0.0);
                                    vec3 history_contribution = ((WAVE_UNIFIED_PRIMARY_RESTIR != uint(0)) ? evaluateUnifiedPrimaryCandidate(history_candidate, position, normal, incoming, material, candidate_count, history_direction, history_distance) : evaluateAreaLightCandidate(history_candidate, position, normal, incoming, material, candidate_count, history_direction, history_distance));
                                    float history_target = max(dot(history_contribution, vec3(0.2126, 0.7152, 0.0722)), 0.0);
                                    bool pairwise = (((push.restir_pairwise_mis != uint(0)) && (reuse_index > uint(0))) && (!material_textured));
                                    float source_target = unpackHalf2x16(history.data.w).x;
                                    bool generalized = (((WAVE_GENERALIZED_RESTIR != uint(0)) && (reuse_index > uint(0))) && (!material_textured));
                                    float generalized_density_normalization = 1.0;
                                    if (generalized)
                                    {
                                        float target_sum = history_target;
                                        float active_proposals = ((history_target > 0.0) ? 1.0 : 0.0);
                                        uint proposal_index = uint(0);
                                        while ((proposal_index <= spatial_count))
                                        {
                                            ivec2 proposal_pixel = previous_pixel;
                                            if ((proposal_index > uint(0)))
                                            {
                                                proposal_pixel = (proposal_pixel + restirSpatialOffset(((proposal_index - uint(1)) + spatial_rotation), int(push.restir_spatial_radius)));
                                            }
                                            bool proposal_inside = (all(greaterThanEqual(proposal_pixel, ivec2(0))) && all(lessThan(proposal_pixel, ivec2(push.image_tile.xy))));
                                            if ((!proposal_inside))
                                            {
                                                proposal_index = (proposal_index + 1);
                                                continue;
                                            }
                                            uint proposal_flat_index = ((uint(proposal_pixel.y) * push.image_tile.x) + uint(proposal_pixel.x));
                                            DirectLightReservoir proposal = loadPreviousDirectLightReservoir(((proposal_flat_index * restir_reservoir_count) + restir_stream));
                                            if ((proposal.data.x == uint(4294967295)))
                                            {
                                                proposal_index = (proposal_index + 1);
                                                continue;
                                            }
                                            vec4 proposal_position = vec4(0);
                                            vec4 proposal_normal = vec4(0);
                                            if ((!restirHistorySurfaceCompatible(proposal_pixel, position, shading_normal, distance, surface_class, material_signature, (proposal_index == uint(0)), proposal_position, proposal_normal)))
                                            {
                                                proposal_index = (proposal_index + 1);
                                                continue;
                                            }
                                            float proposal_target = source_target;
                                            if ((proposal_index != reuse_index))
                                            {
                                                vec3 proposal_direction = vec3(0);
                                                float proposal_distance = float(0.0);
                                                vec3 proposal_incoming = normalize((proposal_position.xyz - previous_camera.origin.xyz));
                                                vec3 proposal_contribution = ((WAVE_UNIFIED_PRIMARY_RESTIR != uint(0)) ? evaluateUnifiedPrimaryCandidate(history_candidate, proposal_position.xyz, normalize(proposal_normal.xyz), proposal_incoming, material, candidate_count, proposal_direction, proposal_distance) : evaluateAreaLightCandidate(history_candidate, proposal_position.xyz, normalize(proposal_normal.xyz), proposal_incoming, material, candidate_count, proposal_direction, proposal_distance));
                                                proposal_target = max(dot(proposal_contribution, vec3(0.2126, 0.7152, 0.0722)), 0.0);
                                            }
                                            target_sum = (target_sum + proposal_target);
                                            if ((proposal_target > 0.0))
                                            {
                                                active_proposals = (active_proposals + 1.0);
                                            }
                                            proposal_index = (proposal_index + 1);
                                        }
                                        float canonical_normalization = ((source_target > 0.0) ? (1.0 / source_target) : 0.0);
                                        generalized_density_normalization = ((target_sum > 0.0) ? min((active_proposals / target_sum), (push.restir_generalized_balance_cap * canonical_normalization)) : 0.0);
                                    }
                                    bool history_selected = ((reuse_index == uint(0)) ? mergeDirectLightReservoir(reservoir, history, history_target, randomFloat(rng)) : (generalized ? mergeBalancedDirectLightReservoir(reservoir, history, history_target, generalized_density_normalization, randomFloat(rng)) : (pairwise ? mergePairwiseDirectLightReservoir(reservoir, history, history_target, source_target, randomFloat(rng)) : mergeCanonicalDirectLightReservoir(reservoir, history, history_target, randomFloat(rng)))));
                                    if (history_selected)
                                    {
#if WAVE_WORK_COUNTERS
                                        profileWork(uint(12), uint(1));
#endif
                                    }
                                }
                                else
                                {
#if WAVE_WORK_COUNTERS
                                    profileWork(uint(13), uint(1));
                                    profileWork((history_source_present ? uint(14) : uint(15)), uint(1));
#endif
                                    if (((reuse_index == uint(0)) && (!history_source_present)))
                                    {
                                        break;
                                    }
                                }
                                reuse_index = (reuse_index + 1);
                            }
                        }
                    }
                    storeCurrentDirectLightReservoir(restir_reservoir_index, reservoir);
                    if ((reservoir.data.x != uint(4294967295)))
                    {
                        AreaLightCandidate selected = AreaLightCandidate(uint(0), vec2(0), float(0));
                        selected.light_index = reservoir.data.x;
                        selected.barycentrics = unpackHalf2x16(reservoir.data.y);
                        selected.target = unpackHalf2x16(reservoir.data.w).x;
                        vec3 selected_direction = vec3(0);
                        float selected_distance = float(0.0);
                        vec3 selected_contribution = ((WAVE_UNIFIED_PRIMARY_RESTIR != uint(0)) ? evaluateUnifiedPrimaryCandidate(selected, position, normal, incoming, material, candidate_count, selected_direction, selected_distance) : evaluateAreaLightCandidate(selected, position, normal, incoming, material, candidate_count, selected_direction, selected_distance));
                        vec3 selected_specular = (selected_contribution * transportLastSpecularFraction);
                        float visibility = areaLightCandidateVisibility(position, normal, selected_direction, selected_distance);
                        path.radiance.rgb = (path.radiance.rgb + ((selected_contribution * visibility) * directLightReservoirNormalization(reservoir)));
                        primary_specular = (primary_specular + ((selected_specular * visibility) * directLightReservoirNormalization(reservoir)));
                    }
                }
                else
                {
                    vec3 area_direct = vec3(0.0);
                    uint sample_index = uint(0);
                    while ((sample_index < light_samples))
                    {
                        vec3 contribution = sampleAreaLight(position, normal, incoming, material, rng, sample_index, light_samples);
                        area_direct = (area_direct + contribution);
                        primary_specular = (primary_specular + ((contribution * transportLastSpecularFraction) / float(light_samples)));
                        sample_index = (sample_index + 1);
                    }
                    path.radiance.rgb = (path.radiance.rgb + (area_direct / float(light_samples)));
                }
                if ((((push.restir_di != uint(0)) && (WAVE_STRATIFIED_PRIMARY_RESTIR != uint(0))) && (push.environment_samples > uint(0))))
                {
                    uint reservoir_pixel_count = ((push.image_tile.x * push.image_tile.y) * restir_reservoir_count);
                    DirectLightReservoir environment_reservoir = emptyDirectLightReservoir();
                    uint environment_candidates = clamp(push.restir_candidate_count, uint(1), uint(4));
                    uint sample_index = uint(0);
                    while ((sample_index < environment_candidates))
                    {
                        AreaLightCandidate candidate = AreaLightCandidate(uint(0), vec2(0), float(0));
                        vec3 candidate_direction = cosineHemisphere(normal, randomFloat(rng), randomFloat(rng));
                        candidate.light_index = ENVIRONMENT_LIGHT_CANDIDATE_INDEX;
                        candidate.barycentrics = encodeEnvironmentCandidateDirection(candidate_direction);
                        float candidate_distance = float(0.0);
                        vec3 contribution = evaluateEnvironmentCandidate(candidate.barycentrics, position, normal, incoming, material, environment_candidates, 1.0, candidate_direction, candidate_distance);
                        candidate.target = max(dot(contribution, vec3(0.2126, 0.7152, 0.0722)), 0.0);
                        updateDirectLightReservoir(environment_reservoir, candidate.light_index, candidate.barycentrics, candidate.target, candidate.target, 1.0, randomFloat(rng));
                        sample_index = (sample_index + 1);
                    }
                    if ((primaryRestirHistoryValid() != uint(0)))
                    {
                        ivec2 history_pixel = ivec2(0);
                        if (((reprojectRestir(position, history_pixel) && all(greaterThanEqual(history_pixel, ivec2(0)))) && all(lessThan(history_pixel, ivec2(push.image_tile.xy)))))
                        {
                            if (restirHistorySurfaceMatches(history_pixel, position, shading_normal, distance, surface_class, material_signature, true))
                            {
                                uint history_index = ((uint(history_pixel.y) * push.image_tile.x) + uint(history_pixel.x));
                                DirectLightReservoir history = loadPreviousEnvironmentReservoir(((history_index * restir_reservoir_count) + restir_stream), reservoir_pixel_count);
                                history = limitDirectLightReservoir(history, max((float(primaryRestirHistoryLimit()) - unpackHalf2x16(environment_reservoir.data.w).y), 0.0));
                                if ((history.data.x != uint(4294967295)))
                                {
                                    AreaLightCandidate history_candidate = AreaLightCandidate(uint(0), vec2(0), float(0));
                                    history_candidate.light_index = history.data.x;
                                    history_candidate.barycentrics = unpackHalf2x16(history.data.y);
                                    vec3 history_direction = vec3(0);
                                    float history_distance = float(0.0);
                                    vec3 history_contribution = evaluateEnvironmentCandidate(history_candidate.barycentrics, position, normal, incoming, material, environment_candidates, 1.0, history_direction, history_distance);
                                    float history_target = max(dot(history_contribution, vec3(0.2126, 0.7152, 0.0722)), 0.0);
                                    mergeDirectLightReservoir(environment_reservoir, history, history_target, randomFloat(rng));
                                }
                            }
                        }
                    }
                    storeCurrentEnvironmentReservoir(restir_reservoir_index, reservoir_pixel_count, environment_reservoir);
                    if ((environment_reservoir.data.x != uint(4294967295)))
                    {
                        vec3 selected_direction = vec3(0);
                        float selected_distance = float(0.0);
                        vec3 selected_contribution = evaluateEnvironmentCandidate(unpackHalf2x16(environment_reservoir.data.y), position, normal, incoming, material, environment_candidates, 1.0, selected_direction, selected_distance);
                        vec3 selected_specular = (selected_contribution * transportLastSpecularFraction);
                        float visibility = areaLightCandidateVisibility(position, normal, selected_direction, selected_distance);
                        path.radiance.rgb = (path.radiance.rgb + ((selected_contribution * visibility) * directLightReservoirNormalization(environment_reservoir)));
                        primary_specular = (primary_specular + ((selected_specular * visibility) * directLightReservoirNormalization(environment_reservoir)));
                    }
                }
                path.radiance.rgb = (radiance_before_direct + ((path.radiance.rgb - radiance_before_direct) / float(direct_stream_count)));
                primary_specular = (specular_before_direct + ((primary_specular - specular_before_direct) / float(direct_stream_count)));
                direct_stream = (direct_stream + 1);
            }
            uint environment_samples = (((push.restir_di != uint(0)) && ((WAVE_UNIFIED_PRIMARY_RESTIR != uint(0)) || (WAVE_STRATIFIED_PRIMARY_RESTIR != uint(0)))) ? uint(0) : min(push.environment_samples, uint(4)));
            if ((environment_samples > uint(0)))
            {
                vec3 environment_direct = vec3(0.0);
                uint sample_index = uint(0);
                while ((sample_index < environment_samples))
                {
                    vec3 contribution = sampleEnvironment(position, normal, incoming, material, rng, environment_samples);
                    environment_direct = (environment_direct + contribution);
                    primary_specular = (primary_specular + ((contribution * transportLastSpecularFraction) / float(environment_samples)));
                    sample_index = (sample_index + 1);
                }
                path.radiance.rgb = (path.radiance.rgb + (environment_direct / float(environment_samples)));
            }
            transportPbrPrepared = false;
            vec3 bsdf_weight = vec3(0);
            samplePbr(material, normal, incoming, rng, next_direction, bsdf_weight, bsdf_pdf, sampled_specular);
            indirect_specular_fraction = transportLastSpecularFraction;
            path.throughput.rgb = ordinarylight_primary_apply_bsdf_weight(path.throughput.rgb, bsdf_weight);
            cone_spread = ordinarylight_primary_scattered_cone_spread(cone_spread, material.base_roughness.a);
        }
    }
    next_direction = ordinarylight_primary_continuation_direction(next_direction);
    setPathBounce(path, uint(1));
    path.metadata.w = ordinarylight_primary_continuation_flags(path.metadata.w, medium_depth, transmission, ((push.restir_di != uint(0)) && (WAVE_UNIFIED_PRIMARY_RESTIR != uint(0))));
    setPathPreviousPdf(path, ordinarylight_primary_previous_pdf(pathPreviousPdf(path), bsdf_pdf, transmission));
    setPathRng(path, rng);
    bool capture_secondary = bool(false);
#if WAVE_DENOISER_SIGNAL_CAPTURE
    capture_secondary = ((path.metadata.w & PATH_INDIRECT_CAPTURE_BIT) != uint(0));
#else
    capture_secondary = ordinarylight_primary_capture_secondary(path.metadata.w, transmission);
#endif
    if (capture_secondary)
    {
        ordinarylight_store_secondary_primary(path_index, path.throughput.rgb, path.radiance.rgb, bsdf_pdf, sampled_specular, pbrSpecularProbability(material), position, material.base_roughness.a, primitive, barycentrics, instance_key);
#if WAVE_DENOISER_SIGNAL_CAPTURE
        if ((material.attenuation_transmission.a > 0.001))
        {
            secondary_paths[path_index].primary_geometry.y = uintBitsToFloat((floatBitsToUint(secondary_paths[path_index].primary_geometry.y) | uint(2147483648)));
        }
#endif
        secondary_paths[path_index].specular_radiance_hit_distance = vec4(primary_specular, (-1.0));
        secondary_paths[path_index].diffuse_radiance_hit_distance = vec4(indirect_specular_fraction, (-1.0));
    }
    ordinarylight_store_path(path_index, path);
    vec3 continuation_origin = ordinarylight_primary_continuation_origin(position, next_direction);
    vec3 continuation_direction = next_direction;
#if WAVE_MEGAKERNEL || WAVE_HYBRID
    traceRemaining(path, continuation_origin, continuation_direction, path_index, medium_depth, rng, cone_width, cone_spread);
    ordinarylight_store_path(path_index, path);
#if WAVE_MEGAKERNEL
    return;
#endif
#endif
#if !WAVE_MEGAKERNEL
    if (((path.metadata.w & PATH_ACTIVE_BIT) == uint(0)))
    {
        return;
    }
    uint output_index = reserveOutputIndex();
    vec4 queued_origin = ordinarylight_primary_ray_origin_payload(continuation_origin);
    vec4 queued_direction = ordinarylight_primary_ray_direction_payload(continuation_direction);
    if ((!ordinarylight_enqueue_continuation(output_index, queued_origin, queued_direction, path_index, cone_width, cone_spread)))
    {
        ordinarylight_deactivate_stored_path(path_index);
        return;
    }
#endif
}
#endif

#if !WAVE_CONTINUATION
#if WAVE_PERSISTENT_COARSE && !1
shared uint persistent_tile_index;
#endif

void ordinarylight_persistent_coarse_schedule(uvec2 tile_extent);
uvec2 ordinarylight_primary_scheduled_group(uvec2 group_id, uvec2 group_count, uint swizzle_width);
void processPrimaryPixel(uvec2 local_pixel);
void main()
{
#if WAVE_RAYGEN
    uvec2 pixel = gl_LaunchIDEXT.xy;
    processPrimaryPixel(pixel);
#else
#if WAVE_PERSISTENT_COARSE
    ordinarylight_persistent_coarse_schedule(push.tile_frame.xy);
#else
    uvec2 group_id = ordinarylight_primary_scheduled_group(gl_WorkGroupID.xy, gl_NumWorkGroups.xy, uint(WAVE_GROUP_SWIZZLE_WIDTH));
    processPrimaryPixel(((group_id * gl_WorkGroupSize.xy) + gl_LocalInvocationID.xy));
#endif
#endif
}
#endif
