#version 460
#extension GL_EXT_ray_query : require
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#if WAVE_SER
#extension GL_NV_shader_invocation_reorder : require
#endif

#define WAVE_RAYGEN 1
#define WAVE_MEGAKERNEL 1
#define WAVE_HYBRID 0
#include "wavefront_primary_impl.glsl"
