"""Generate the secondary shading stage from OrdinaryShade."""
import argparse
import ast
import inspect
from pathlib import Path
import re
import textwrap
import ordinaryshade as osh
import generate_primary_shaders as primary
from ordinarylight.shaders import texture_programs, sampling_programs, restir_programs, transport_programs, lighting_programs, volume_programs, material_support_programs
from ordinarylight.shaders import secondary_programs as p
from ordinarylight.shaders.secondary_layout import LAYOUT


@osh.external
def profileWork(counter: osh.u32, amount: osh.u32) -> osh.void:
    pass


def generated_source():
    available = {name: value for module in (primary, texture_programs, sampling_programs, restir_programs, lighting_programs, volume_programs, material_support_programs, p) for name, value in vars(module).items()
                 if isinstance(value, (osh.ShaderFunction, osh.ExternalFunction))}
    # profileWork is implemented in this typed stage.
    values = {name: value for module in (transport_programs, primary, lighting_programs, p) for name, value in vars(module).items() if isinstance(value, osh.StructType)}
    values.update(scene_tlas=osh.acceleration_structure(), paths=osh.runtime_array(p.WavePathState),
                  secondary_paths=osh.runtime_array(p.SecondaryPathState), materials=osh.runtime_array(p.MaterialData),
                  vertices=osh.runtime_array(osh.vec4), attributes=osh.runtime_array(p.VertexAttributeData),
                  output_queue=p.RayQueue, input_queue=p.RayQueue, hit_queue=p.HitQueue, camera=p.CameraData, previous_camera=p.CameraData,
                  stacks=osh.runtime_array(p.WaveMediumStack), push=p.SecondaryConstants,
                  work_counters=osh.runtime_array(osh.u32), profile_bounce=osh.u32, transportLastSpecularFraction=osh.vec3, transportPointSpecular=osh.vec3,
                  gl_GlobalInvocationID=osh.uvec3, gl_LaunchIDEXT=osh.uvec3,
                  gl_LocalInvocationIndex=osh.u32, gl_WorkGroupID=osh.uvec3,
                  gl_LocalInvocationID=osh.uvec3, gl_NumWorkGroups=osh.uvec3)
    for name, format in (('position_image','r32f'),('normal_image','r32ui'),('material_image','r32ui'),
                         ('previous_position_image','r32f'),('previous_normal_image','r32ui'),('previous_material_image','r32ui')):
        values[name]=osh.storage_image(format)
    for name in ('gl_RayFlagsOpaqueEXT','gl_RayFlagsTerminateOnFirstHitEXT',
                 'gl_RayQueryCommittedIntersectionNoneEXT','gl_RayQueryCommittedIntersectionTriangleEXT',
                 'WAVE_GENERALIZED_RESTIR','WAVE_UNIFIED_PRIMARY_RESTIR','WAVE_STRATIFIED_PRIMARY_RESTIR',
                 'WAVE_SHARED_PRIMARY_RESERVOIRS','WAVE_HYBRID','WAVE_LOCAL_SIZE_X','WAVE_LOCAL_SIZE_Y','PATH_ACTIVE_BIT','PATH_PREVIOUS_DIFFUSE_BIT',
                 'PATH_PREVIOUS_UNIFIED_NEE_BIT','PATH_INDIRECT_CAPTURE_BIT','WAVE_MAX_MEDIUM_STACK_DEPTH'):
        values[name]=osh.u32
    source=LAYOUT
    for name in re.findall(r'@(\w+)@', LAYOUT):
        helper=available[name]
        tree=ast.parse(textwrap.dedent(inspect.getsource(helper.function)))
        calls={n.func.id for n in ast.walk(tree) if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)}
        externals=tuple(value if isinstance(value, osh.ExternalFunction) else osh.external(value.function)
                        for called in sorted(calls) if called in available and called != name
                        for value in (available[called],))
        compiled=osh.compile_function(helper, external_values=values, externals=externals, capabilities=("shader_reorder", "subgroup_ballot")).source
        compiled = re.sub(r'(?m)^vec3 OL_TRANSPORT_RAY_ORIGIN\([^;]*;\n', '', compiled)
        source=source.replace('@'+name+'@',compiled.rstrip())
    return '// Generated by scripts/generate_secondary_shaders.py using OrdinaryShade.\n'+source.rstrip()+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=Path(__file__).resolve().parents[1]/'ordinarylight/shaders/wavefront_shade.comp';source=generated_source()
    if args.check:
        if path.read_text()!=source:raise SystemExit(f'{path} is stale')
    else:path.write_text(source)
    print(('Verified ' if args.check else 'Wrote ')+path.name)


if __name__=='__main__':main()
