"""Generate texture lookup and application algorithms from OrdinaryShade."""
import argparse
import ast
import inspect
from pathlib import Path
import re
import textwrap
import ordinaryshade as osh
import generate_primary_shaders as primary
from ordinarylight.shaders import texture_programs as p
from ordinarylight.shaders.texture_layout import LAYOUT


@osh.external
def profileWork(counter: osh.u32, amount: osh.u32) -> osh.void:
    pass


def generated_source():
    available = {name: value for module in (primary, p) for name, value in vars(module).items()
                 if isinstance(value, osh.ShaderFunction)}
    available['profileWork'] = profileWork
    values = {'texture_words': osh.runtime_array(osh.u32),
              'texture_bindings': osh.runtime_array(p.TextureBindingData),
              'SRGB_TO_LINEAR': osh.runtime_array(osh.f32),
              'native_textures': osh.opaque_type('sampled_texture_2d_array'),
              'MaterialData': p.MaterialData}
    source=LAYOUT
    for name in re.findall(r'@(\w+)@', LAYOUT):
        helper=available[name]
        tree=ast.parse(textwrap.dedent(inspect.getsource(helper.function)))
        calls={n.func.id for n in ast.walk(tree) if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)}
        externals=tuple(value if isinstance(value, osh.ExternalFunction) else osh.external(value.function)
                        for called in sorted(calls) if called in available and called != name
                        for value in (available[called],))
        compiled=osh.compile_function(helper, external_values=values, externals=externals).source
        source=source.replace('@'+name+'@',compiled.rstrip())
    return '// Generated by scripts/generate_texture_shaders.py using OrdinaryShade.\n'+source.rstrip()+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=Path(__file__).resolve().parents[1]/'ordinarylight/shaders/wavefront_textures.glsl';source=generated_source()
    if args.check:
        if path.read_text()!=source:raise SystemExit(f'{path} is stale')
    else:path.write_text(source)
    print(('Verified ' if args.check else 'Wrote ')+path.name)


if __name__=='__main__':main()
