"""Generate the portable WGSL preview from OrdinaryShade graphics stages."""
import argparse
from pathlib import Path
import ordinaryshade as osh
from ordinarylight.shaders.portable_volume_programs import volume_preview_vertex, volume_preview_fragment, color_at


def generated_source():
    vertex = osh.compile(volume_preview_vertex, target='wgsl').source
    fragment = osh.compile(volume_preview_fragment, target='wgsl', helpers=(color_at,)).source
    return ('// Generated by scripts/generate_portable_volume.py using OrdinaryShade.\n'
            + vertex.replace('fn main(', 'fn vertex_main(').rstrip() + '\n\n'
            + fragment.replace('fn main(', 'fn fragment_main(').rstrip() + '\n')


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=Path(__file__).resolve().parents[1]/'ordinarylight/portable/volume.wgsl';source=generated_source()
    if args.check:
        if path.read_text()!=source:raise SystemExit(f'{path} is stale')
    else:path.write_text(source)
    print(('Verified ' if args.check else 'Wrote ')+path.name)


if __name__=='__main__':main()
