"""Generate transport kernels and reusable queries from typed OrdinaryShade."""
import argparse
import ast
import importlib
import inspect
from pathlib import Path
import re
import textwrap
import ordinaryshade as osh
from ordinarylight.shaders import transport_programs as common, sampling_programs as sampling, transport_callbacks as callbacks

MODULES = {
    'intersections':'transport_intersections', 'integrator':'transport_integrator',
    'box_batch':'transport_box', 'reduce':'transport_reduce',
    'gpu_reduction':'transport_gpu_reduction', 'gpu_geometry':'transport_gpu_geometry',
}


def generated_sources():
    modules={name: importlib.import_module('ordinarylight.shaders.'+stem+'_programs') for name,stem in MODULES.items()}
    available={name:value for module in (common,sampling,callbacks,*modules.values())
               for name,value in vars(module).items() if isinstance(value,(osh.ShaderFunction,osh.ExternalFunction)) and name!='main'}
    structures={name:value for module in (common,*modules.values()) for name,value in vars(module).items() if isinstance(value,osh.StructType)}
    for name, module in modules.items():
        source=importlib.import_module('ordinarylight.shaders.'+MODULES[name]+'_layout').LAYOUT
        values=dict(structures)
        values.update(transport_tlas=osh.acceleration_structure(),
                      transport_vertices=osh.runtime_array(osh.vec4),transport_attributes=osh.runtime_array(osh.vec4),
                      triangle_records=osh.runtime_array(osh.uvec4),custom_geometry=osh.runtime_array(common.CustomRecord),
                      transport_materials=osh.runtime_array(common.TransportMaterialRecord),optical_media=osh.runtime_array(osh.vec4),
                      medium_boundaries=osh.runtime_array(osh.uvec4),analytic_lights=osh.runtime_array(osh.vec4),
                      transport_samples=osh.runtime_array(common.OrdinaryLightSurfaceSample),initial_stack=osh.runtime_array(osh.uvec4),
                      gpu_control=osh.uvec4,OL_BOX_INDICES=osh.runtime_array(osh.u32),OL_BOX_RESOURCE=osh.runtime_array(osh.vec4),
                      counts=osh.uvec4,state=osh.uvec4,commands=osh.runtime_array(osh.uvec4),
                      groups=osh.runtime_array(osh.uvec4),indices=osh.runtime_array(osh.u32),weights=osh.runtime_array(osh.vec2),
                      samples=osh.runtime_array(common.OrdinaryLightSurfaceSample),
                      bounds=osh.runtime_array(osh.f32),diagnostics=osh.runtime_array(osh.u32),gl_GlobalInvocationID=osh.uvec3)
        if hasattr(module,'PipelineConstants'):values['pc']=module.PipelineConstants;values['PipelineConstants']=module.PipelineConstants
        if hasattr(module,'SampleAccumulation'):
            values['accumulated']=osh.runtime_array(module.SampleAccumulation)
            values['contributions']=osh.runtime_array(module.SampleAccumulation)
        if hasattr(module,'Record'):
            values['input_records']=osh.runtime_array(module.Record)
            values['output_records']=osh.runtime_array(module.Record)
        for constant in ('OL_MATERIAL_COUNT','OL_BOUNDARY_COUNT','OL_CUSTOM_MATERIAL_OFFSET','OL_NO_BOUNDARY',
                         'OL_HIT_MATERIAL','OL_HIT_BOUNDARY','OL_HIT_IDENTITY','OL_HIT_UV','OL_HIT_SHADING_NORMAL',
                         'OL_SURFACE_SLOT_COUNT','OL_TRIANGLE_COUNT','OL_ANALYTIC_LIGHT_COUNT','OL_BOX_INDEX_COUNT','OL_BOX_INDEX',
                         'gl_RayFlagsOpaqueEXT','gl_RayQueryCandidateIntersectionAABBEXT',
                         'gl_RayQueryCommittedIntersectionNoneEXT','gl_RayQueryCommittedIntersectionTriangleEXT',
                         'CAPACITY','PROGRAMS','MATERIALS','TRIANGLES'):
            values[constant]=osh.u32
        values['OL_PI']=osh.f32
        for helper_name in re.findall(r'@(\w+)@', source):
            helper=getattr(module,helper_name)
            calls={n.func.id for n in ast.walk(ast.parse(textwrap.dedent(inspect.getsource(helper.function))))
                   if isinstance(n,ast.Call) and isinstance(n.func,ast.Name)}
            externals=tuple(h if isinstance(h,osh.ExternalFunction) else osh.external(h.function)
                            for called in sorted(calls) if called in available and called!=helper_name
                            for h in (available[called],))
            try:
                compiled=osh.compile_function(helper,external_values=values,externals=externals).source
            except Exception as error:
                raise RuntimeError(f'{name}/{helper_name}: {error}') from error
            source=source.replace('@'+helper_name+'@',compiled.rstrip())
        yield name, '// Generated by scripts/generate_transport_kernels.py using OrdinaryShade.\n'+source.rstrip()+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    root=Path(__file__).resolve().parents[1]/'ordinarylight/shaders/transport_v1'
    for name,source in generated_sources():
        path=root/(name+'.glsl')
        if args.check:
            if path.read_text()!=source:raise SystemExit(f'{path} is stale')
        else:path.write_text(source)
        print(('Verified ' if args.check else 'Wrote ')+path.name)


if __name__=='__main__':main()
