"""Generate thin Vulkan stage wrappers and their typed entry points."""
import argparse
from pathlib import Path
import ordinaryshade as osh
from ordinarylight.shaders import entrypoint_programs as p, fused_primary_programs as primary, secondary_programs as secondary
from ordinarylight.shaders.entrypoint_layouts import LAYOUTS
from ordinarylight.shaders.srgb_table import SRGB_TO_LINEAR


def generated_sources():
    for name, layout in LAYOUTS.items():
        source=layout
        if '@main@' in source:
            if name=='ser_probe.rgen':
                function=p.ser_probe
                values=dict(gl_LaunchIDEXT=osh.uvec3, gl_LaunchSizeEXT=osh.uvec3, probe_output=p.ProbeOutput)
                externals=()
            elif name=='ser_probe.rmiss':
                function=p.empty_miss;values={};externals=()
            else:
                function=p.continuation
                values=dict(gl_GlobalInvocationID=osh.uvec3,gl_NumWorkGroups=osh.uvec3,gl_WorkGroupSize=osh.uvec3,
                            output_queue=secondary.RayQueue, paths=osh.runtime_array(primary.WavePathState))
                externals=(osh.external(primary.pathRng.function),osh.external(primary.traceRemaining.function))
            compiled=osh.compile_function(function,external_values=values,externals=externals,capabilities=('shader_reorder',)).source
            compiled=compiled.replace('void '+function.function.__name__+'(', 'void main(')
            source=source.replace('@main@',compiled.rstrip())
        yield name, '// Generated by scripts/generate_entrypoint_shaders.py using OrdinaryShade.\n'+source.rstrip()+'\n'
    # A constant-data declaration: texture decode behavior lives in texture_programs.py.
    yield 'wavefront_srgb.glsl', ('// Generated by scripts/generate_entrypoint_shaders.py from typed table data.\n'
                                 'const float SRGB_TO_LINEAR[256] = float[](\n    '
                                 + ',\n    '.join(repr(v) for v in SRGB_TO_LINEAR) + '\n);\n')


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    root=Path(__file__).resolve().parents[1]/'ordinarylight/shaders'
    for name,source in generated_sources():
        path=root/name
        if args.check:
            if path.read_text()!=source:raise SystemExit(f'{path} is stale')
        else:path.write_text(source)
        print(('Verified ' if args.check else 'Wrote ')+name)


if __name__=='__main__':main()
