"""Generate volume algorithms from OrdinaryShade."""
import argparse
import ast
import inspect
from pathlib import Path
import re
import textwrap
import ordinaryshade as osh
import generate_primary_shaders as primary
from ordinarylight.shaders import texture_programs, sampling_programs, restir_programs, transport_programs, lighting_programs
from ordinarylight.shaders import volume_programs as p
from ordinarylight.shaders.volume_layout import LAYOUT


@osh.external
def profileWork(counter: osh.u32, amount: osh.u32) -> osh.void:
    pass


def generated_source():
    available = {name: value for module in (primary, texture_programs, sampling_programs, restir_programs, lighting_programs, p) for name, value in vars(module).items()
                 if isinstance(value, (osh.ShaderFunction, osh.ExternalFunction))}
    available['profileWork'] = profileWork
    values = {name: value for module in (transport_programs, p) for name, value in vars(module).items() if isinstance(value, osh.StructType)}
    values.update(point_lights=osh.runtime_array(p.PointLightData),
                  area_lights=osh.runtime_array(transport_programs.AreaLightData),
                  scene_tlas=osh.opaque_type('acceleration_structure'),
                  volume_headers=osh.runtime_array(p.VolumeHeader), volume_scalars=osh.runtime_array(osh.f32),
                  volume_transfer=osh.runtime_array(osh.vec4), triangle_volumes=osh.runtime_array(osh.u32),
                  volume_textures=osh.opaque_type('sampled_texture_3d_array'), push=p.VolumeLightingContext)
    for name in ('gl_RayFlagsOpaqueEXT','gl_RayFlagsTerminateOnFirstHitEXT',
                 'gl_RayQueryCommittedIntersectionNoneEXT','gl_RayQueryCommittedIntersectionTriangleEXT'):
        values[name]=osh.u32
    source=LAYOUT
    for name in re.findall(r'@(\w+)@', LAYOUT):
        helper=available[name]
        tree=ast.parse(textwrap.dedent(inspect.getsource(helper.function)))
        calls={n.func.id for n in ast.walk(tree) if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)}
        externals=tuple(value if isinstance(value, osh.ExternalFunction) else osh.external(value.function)
                        for called in sorted(calls) if called in available and called != name
                        for value in (available[called],))
        compiled=osh.compile_function(helper, external_values=values, externals=externals).source
        compiled = re.sub(r'(?m)^vec3 OL_TRANSPORT_RAY_ORIGIN\([^;]*;\n', '', compiled)
        source=source.replace('@'+name+'@',compiled.rstrip())
    return '// Generated by scripts/generate_volume_shaders.py using OrdinaryShade.\n'+source.rstrip()+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=Path(__file__).resolve().parents[1]/'ordinarylight/shaders/transport_v1/volumes.glsl';source=generated_source()
    if args.check:
        if path.read_text()!=source:raise SystemExit(f'{path} is stale')
    else:path.write_text(source)
    print(('Verified ' if args.check else 'Wrote ')+path.name)


if __name__=='__main__':main()
