"""Generate transport sampling helpers from OrdinaryShade."""
import argparse
from pathlib import Path
import ordinaryshade as osh
from ordinarylight.shaders.sampling_programs import HELPERS, sampling_module

ROOT = Path(__file__).resolve().parents[1]


def generated_source():
    source = osh.compile(sampling_module, helpers=HELPERS).source
    source = source[:source.rindex('void main()')]
    source = '\n'.join(line for line in source.splitlines()
                       if not line.startswith(('#version', 'layout(local_size_')))
    return ('// Generated by scripts/generate_sampling_shaders.py using OrdinaryShade.\n'
            '#ifndef ORDINARYLIGHT_SAMPLING_V1\n#define ORDINARYLIGHT_SAMPLING_V1 1\n'
            + source + '\n#endif\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'ordinarylight/shaders/transport_v1/sampling.glsl'
    source = generated_source()
    if args.check:
        if path.read_text() != source:
            raise SystemExit(f'{path} is stale; regenerate it')
    else:
        path.write_text(source)
    print(('Verified ' if args.check else 'Wrote ') + path.name)


if __name__ == '__main__':
    main()
