"""Generate the shared ReSTIR library from typed OrdinaryShade functions."""
import argparse
from pathlib import Path
import ordinaryshade as osh
from ordinarylight.shaders.restir_programs import COMMON, STORAGE, reservoir_module

ROOT = Path(__file__).resolve().parents[1]


def generated_source():
    # The compute entry supplies resource types to the OrdinaryShade linker.
    # Emit its library as an include, omitting only the entry and workgroup ABI.
    source = osh.compile(reservoir_module, helpers=COMMON + STORAGE).source
    source = source[:source.rindex('void main()')]
    lines = source.splitlines()
    source = '\n'.join(line for line in lines if not line.startswith('#version')
                       and not line.startswith('layout(local_size_')) + '\n'
    # Storage resources/functions exist only in the primary shader variant.
    # These are mechanical module guards; function bodies come wholly from osh.
    start = source.index('layout(std430, set = 0, binding = 16)')
    end = source.index('\n};', source.index('layout(std430, set = 0, binding = 17)')) + 3
    source = source[:start] + '#if WAVE_RESTIR_PRIMARY\n' + source[start:end] + '\n#endif' + source[end:]
    # Guard prototypes and definitions for the storage-only library members.
    import re
    for helper in STORAGE:
        name = helper.function.__name__
        pattern = re.compile(r'(?m)^\w+ ' + name + r'\([^;{]*\)(?:;|\n\{.*?\n\})', re.S)
        source = pattern.sub(lambda m: '#if WAVE_RESTIR_PRIMARY\n' + m[0] + '\n#endif', source)
    return ('// Generated by scripts/generate_restir_shaders.py using Ordinary Shade.\n'
            '// Edit ordinarylight/shaders/restir_programs.py.\n' + source.rstrip() + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'ordinarylight/shaders/wavefront_restir.glsl'
    source = generated_source()
    if args.check:
        if path.read_text() != source:
            raise SystemExit(f'{path} is stale; regenerate it')
    else:
        path.write_text(source)
    print(('Verified ' if args.check else 'Wrote ') + path.name)


if __name__ == '__main__':
    main()
