"""Generate utility shader artifacts from typed OrdinaryShade sources."""
import argparse
from pathlib import Path
import ordinaryshade as osh
from ordinarylight.shaders.utility_programs import PROGRAMS, volume_upload

ROOT = Path(__file__).resolve().parents[1]


def generated_source(program):
    source = osh.compile(program).source
    return source.replace('#version 460\n', '#version 460\n\n'
                          '// Generated by scripts/generate_utility_shaders.py using Ordinary Shade.\n'
                          '// Edit ordinarylight/shaders/utility_programs.py.\n', 1)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, program in {**PROGRAMS, "volume_upload": volume_upload}.items():
        output = ROOT / 'ordinarylight' / 'shaders' / f'{name}.comp'
        source = generated_source(program)
        if args.check:
            if output.read_text() != source:
                raise SystemExit(f'{output} is stale; regenerate it')
        else:
            output.write_text(source)
        print(('Verified ' if args.check else 'Wrote ') + output.name)
    output = ROOT / 'ordinarylight/shaders/volume_upload.wgsl'
    source = '// Generated by scripts/generate_utility_shaders.py using OrdinaryShade.\n' + osh.compile(volume_upload, target='wgsl').source
    if args.check:
        if output.read_text() != source:
            raise SystemExit(f'{output} is stale; regenerate it')
    else:
        output.write_text(source)


if __name__ == '__main__':
    main()
