"""Generate shared Ordinary Light color helpers with Ordinary Shade."""

from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
DEFAULT_ORDINARYSHADE = ROOT.parent / "ordinaryshade"
if DEFAULT_ORDINARYSHADE.is_dir():
    sys.path.insert(0, str(DEFAULT_ORDINARYSHADE))

import ordinaryshade as osh
from ordinaryshade_library import acesApproximation, linearToSrgb


def generated_source():
    generated = "\n".join((
        osh.compile_function(acesApproximation).source.rstrip(),
        osh.compile_function(linearToSrgb).source.rstrip(),
    ))
    return (
        "// Generated by scripts/generate_color_shaders.py using Ordinary Shade.\n"
        "// The checked-in artifact keeps Ordinary Shade an optional development tool.\n"
        f"{generated}\n"
    )


def main():
    output = ROOT / "ordinarylight/shaders/ordinaryshade_color.glsl"
    source = generated_source()
    if "--check" in sys.argv:
        if output.read_text() != source:
            raise SystemExit(f"{output} is stale; regenerate it")
        print(f"Verified {output.relative_to(ROOT)}")
        return
    output.write_text(source)
    print(f"Wrote {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
