"""Generate the indirect reservoir include from the existing typed library."""
import argparse
from pathlib import Path
import re
import ordinaryshade as osh
from ordinaryshade_library import (
    IndirectLightSample, IndirectLightReservoir, indirectEncodeNormal,
    indirectDecodeNormal, indirectPackRgb9e5, indirectUnpackRgb9e5,
    emptyIndirectLightReservoir, storeIndirectLightReservoir, loadIndirectLightReservoir,
)

HELPERS = (indirectEncodeNormal, indirectDecodeNormal, indirectPackRgb9e5,
           indirectUnpackRgb9e5, emptyIndirectLightReservoir,
           storeIndirectLightReservoir, loadIndirectLightReservoir)


@osh.compute()
def library(indirect_reservoir_words: osh.storage_buffer(osh.u32, binding=0)):
    pass


def generated_source():
    source = osh.compile(library, helpers=HELPERS).source
    source = source[:source.rindex('void main()')]
    source = '\n'.join(line for line in source.splitlines()
                       if not line.startswith(('#version', 'layout(local_size_')))
    start=source.index('layout(std430, set = 0, binding = 0)')
    end=source.index('\n};',start)+3
    resource=source[start:end].replace('binding = 0','binding = WAVE_INDIRECT_REUSE_BINDING')
    source=source[:start]+'#if WAVE_INDIRECT_REUSE_STORAGE\n#ifndef WAVE_INDIRECT_REUSE_BINDING\n#define WAVE_INDIRECT_REUSE_BINDING 0\n#endif\n'+resource+'\n#endif'+source[end:]
    for helper in HELPERS[-2:]:
        pattern=re.compile(r'(?m)^\w+ '+helper.function.__name__+r'\([^;{]*\)(?:;|\n\{.*?\n\})',re.S)
        source=pattern.sub(lambda m:'#if WAVE_INDIRECT_REUSE_STORAGE\n'+m[0]+'\n#endif',source)
    return '// Generated by scripts/generate_indirect_library.py using OrdinaryShade.\n'+source.strip()+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=Path(__file__).resolve().parents[1]/'ordinarylight/shaders/wavefront_indirect_reuse.glsl'
    source=generated_source()
    if args.check:
        if path.read_text()!=source:raise SystemExit(f'{path} is stale')
    else:path.write_text(source)
    print(('Verified ' if args.check else 'Wrote ')+path.name)


if __name__=='__main__':main()
