"""Generate the shared native intersection implementation from OrdinaryShade."""

import argparse
from pathlib import Path

import ordinaryshade as osh
from ordinarylight.shaders.native_intersection_programs import (
    NativeIntersection, nativeIntersectionMiss, nativeTraceSurface, nativeIntersectCandidate, nativeSurfaceMask, NativeOpticalBoundary, nativeBoundaryEnabled, nativeEvaluateBoundary,
)


from ordinarylight.shaders.native_emitter_programs import (NativeEmitterSample,
    nativeAreaLightCount, nativeEmitterValid, nativeEmitterCount)


def generated_source():
    # Struct declarations and include guards are mechanical ABI, not shader logic.
    declaration = """// Generated by scripts/generate_native_intersection.py using OrdinaryShade.
#ifndef ORDINARYLIGHT_NATIVE_INTERSECTION
#define ORDINARYLIGHT_NATIVE_INTERSECTION 1
struct NativeEmitterSample {
    vec3 position;
    vec3 normal;
    vec3 emission;
    float area_pdf;
    bool two_sided;
};
struct NativeOpticalBoundary {
    vec2 ior;
    bool enabled;
};
struct NativeIntersection {
    vec4 position_distance;
    vec4 geometric_normal;
    vec4 shading_normal;
    uvec4 identity;
    uvec4 address;
    vec4 texcoord;
    vec4 previous_position;
};
"""
    values = {"NativeIntersection": NativeIntersection, "NativeOpticalBoundary": NativeOpticalBoundary,
              "NativeEmitterSample": NativeEmitterSample, "scene_tlas": osh.acceleration_structure()}
    body = osh.compile_function(nativeIntersectionMiss, external_values=values).source
    body += osh.compile_function(nativeSurfaceMask).source
    body += osh.compile_function(nativeBoundaryEnabled, external_values=values).source
    body += osh.compile_function(nativeTraceSurface, external_values=values, externals=(
        osh.external(nativeIntersectionMiss.function), nativeIntersectCandidate,
        nativeEvaluateBoundary, osh.external(nativeBoundaryEnabled.function),
    )).source
    body += osh.compile_function(nativeAreaLightCount, externals=(nativeEmitterCount,)).source
    body += osh.compile_function(nativeEmitterValid, external_values=values).source
    return declaration + body + "#endif\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = Path(__file__).resolve().parents[1] / "ordinarylight/shaders/native_intersection.glsl"
    source = generated_source()
    if args.check:
        if path.read_text() != source:
            raise SystemExit(f"{path} is stale")
    else:
        path.write_text(source)
    print(("Verified " if args.check else "Wrote ") + path.name)


if __name__ == "__main__":
    main()
