"""Generate the shared transport ABI and algorithms from typed OrdinaryShade."""
import argparse
from pathlib import Path
import ordinaryshade as osh
from ordinarylight.shaders import transport_programs as p
from ordinarylight.shaders.sampling_programs import cosineHemisphere

ROOT = Path(__file__).resolve().parents[1]
LIBRARIES = {
    'emissive': ((p.OrdinaryLightEmitterSample,), (p.ordinarylightValidAreaPdf, p.ordinarylightTriangleArea, p.ordinarylightSampleSurface, p.ordinarylightSurfaceLightPdf, p.ordinarylightValidTransportMaterial, p.ordinarylightEmissiveMisWeight)),
    'bsdf': ((), (p.olDistribution, p.olMask, p.olMicroNormal, p.olBsdf, p.olSampleBsdf)),
    'types': ((p.MaterialData, p.PointLightData, p.AreaLightData), ()),
    'material_contracts': ((p.MaterialEvaluation,), ()),
    'contracts': ((p.OrdinaryLightSurfaceSample,), (p.ordinarylightEnteringMedium, p.ordinarylightDestinationMedium)),
    'dielectric': ((p.OrdinaryLightDielectricEvent,), (p.ordinarylightBeer, p.ordinarylightDielectric)),
    'sample_sphere': ((), (p.ordinarylightSampleSphere_pdf, p.ordinarylightSampleSphere)),
    'sdf_sphere': ((), (p.ordinarylightSdfSphere,)),
}


def generated_sources():
    for name, (structures, helpers) in LIBRARIES.items():
        parts = ["struct " + s.name + "\n{\n" + "".join(
            f"    {field.type.name} {field.name};\n" for field in s.fields) + "};\n"
                 for s in structures]
        if name == "bsdf":
            parts.append(f"const float OL_PI = {p.OL_PI!r};\n")
        linked_helpers = helpers + ((p.ordinarylightDielectric, cosineHemisphere) if name == 'bsdf' else ())
        extra = (p.ordinarylightCustomSurfaceSample, p.ordinarylightCustomSurfacePdf) if name == 'emissive' else ()
        values = {name: value for name, value in vars(p).items() if isinstance(value, osh.StructType)}
        values.update(transport_vertices=osh.runtime_array(osh.vec4),
                      custom_geometry=osh.runtime_array(p.CustomRecord),
                      optical_media=osh.runtime_array(osh.vec4),
                      OL_SURFACE_SLOT_COUNT=osh.u32, OL_TRIANGLE_COUNT=osh.u32)
        for helper in helpers:
            parts.append(osh.compile_function(helper, external_values=values, externals=tuple(
                osh.external(h.function) for h in linked_helpers if h is not helper) + extra).source)
        guard = 'ORDINARYLIGHT_GENERATED_TRANSPORT_' + name.upper()
        yield name, ('// Generated by scripts/generate_transport_shaders.py using OrdinaryShade.\n'
                     '// Edit ordinarylight/shaders/transport_programs.py.\n'
                     f'#ifndef {guard}\n#define {guard} 1\n'
                     + '\n'.join(parts).rstrip() + '\n#endif\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, source in generated_sources():
        path = ROOT / 'ordinarylight/shaders/transport_v1' / (name + '.glsl')
        if args.check:
            if path.read_text() != source:
                raise SystemExit(f'{path} is stale; regenerate it')
        else:
            path.write_text(source)
        print(('Verified ' if args.check else 'Wrote ') + path.name)


if __name__ == '__main__':
    main()
