"""Generate Ordinary Light effect helpers with the sibling Ordinary Shade."""

from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ORDINARYSHADE = ROOT.parent / "ordinaryshade"
if DEFAULT_ORDINARYSHADE.is_dir():
    sys.path.insert(0, str(DEFAULT_ORDINARYSHADE))

import ordinaryshade as osh


@osh.function
def ordinarylight_tint(
    color: osh.vec3, target: osh.vec3, strength: osh.f32,
) -> osh.vec3:
    return osh.mix(color, target, strength)


@osh.function
def ordinarylight_emissive(
    color: osh.vec3, emission: osh.vec3, strength: osh.f32,
) -> osh.vec3:
    return osh.minimum(color + emission * strength, osh.vec3(1.0))


@osh.function
def ordinarylight_isolation(
    color: osh.vec3, dimming: osh.f32,
) -> osh.vec3:
    return color * (1.0 - dimming)


@osh.function
def ordinarylight_outline(
    color: osh.vec3, outline: osh.vec3, boundary: osh.boolean,
) -> osh.vec3:
    return osh.select(boundary, outline, color)


def generated_source():
    functions = (
        ordinarylight_tint, ordinarylight_emissive, ordinarylight_isolation,
        ordinarylight_outline,
    )
    generated = "\n".join(
        osh.compile_function(function).source.rstrip() for function in functions
    )
    return (
        "// Generated by scripts/generate_effect_shaders.py using Ordinary Shade.\n"
        "// The checked-in artifact keeps Ordinary Shade an optional development tool.\n"
        f"{generated}\n"
    )


def main():
    output = ROOT / "ordinarylight/shaders/ordinaryshade_effects.glsl"
    source = generated_source()
    if "--check" in sys.argv:
        if output.read_text() != source:
            raise SystemExit(f"{output} is stale; regenerate it")
        print(f"Verified {output.relative_to(ROOT)}")
        return
    output.write_text(source)
    print(f"Wrote {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
