// Generated by scripts/generate_portable_volume.py using OrdinaryShade.
struct VolumePreviewVertex {
    @builtin(position) position: vec4<f32>,
    @location(0) uv: vec2<f32>,
}

@vertex
fn vertex_main(
    @builtin(vertex_index) index: u32
) -> VolumePreviewVertex {
    var position: vec2<f32> = vec2<f32>((-1.0), (-1.0));
    if ((index == u32(1))) {
        position = vec2<f32>(3.0, (-1.0));
    }
    if ((index == u32(2))) {
        position = vec2<f32>((-1.0), 3.0);
    }
    return VolumePreviewVertex(vec4<f32>(position, 0.0, 1.0), position);
}

struct Settings {
    viewport: vec4<f32>,
    camera: vec4<f32>,
    slice: vec4<f32>,
    dimensions: vec4<f32>,
}

@group(0) @binding(0) var<storage, read> density: array<f32>;
@group(0) @binding(1) var<uniform> settings: Settings;
@group(0) @binding(2) var<storage, read> transfer: array<vec4<f32>>;

fn color_at(position: vec3<f32>) -> vec4<f32> {
    let dimensions: vec3<u32> = vec3<u32>(settings.dimensions.xyz);
    let cell: vec3<u32> = min(vec3<u32>((clamp(((position * 0.5) + 0.5), vec3<f32>(0.0), vec3<f32>(1.0)) * vec3<f32>(dimensions))), (dimensions - u32(1)));
    let value: f32 = density[((((cell.z * dimensions.y) + cell.y) * dimensions.x) + cell.x)];
    let fraction: f32 = clamp((value / settings.viewport.w), 0.0, 1.0);
    let index: u32 = u32((fraction * f32((arrayLength(&transfer) - u32(1)))));
    return transfer[index];
}

@fragment
fn fragment_main(
    @location(0) uv: vec2<f32>
) -> @location(0) vec4<f32> {
    let yaw: f32 = settings.camera.x;
    let pitch: f32 = settings.camera.y;
    let eye: vec3<f32> = (settings.camera.z * vec3<f32>((cos(pitch) * sin(yaw)), sin(pitch), (cos(pitch) * cos(yaw))));
    let forward: vec3<f32> = normalize((-eye));
    let right: vec3<f32> = normalize(cross(forward, vec3<f32>(0.0, 1.0, 0.0)));
    let up: vec3<f32> = cross(right, forward);
    let ray: vec3<f32> = normalize(((forward + ((((right * uv.x) * settings.viewport.x) / settings.viewport.y) * 0.5)) + ((up * uv.y) * 0.5)));
    let inverse: vec3<f32> = (1.0 / select(vec3<f32>(1e-07), ray, (abs(ray) > vec3<f32>(1e-07))));
    let a: vec3<f32> = (((-vec3<f32>(1.0)) - eye) * inverse);
    let b: vec3<f32> = ((vec3<f32>(1.0) - eye) * inverse);
    let near: f32 = max(max(min(a.x, b.x), min(a.y, b.y)), min(a.z, b.z));
    let far: f32 = min(min(max(a.x, b.x), max(a.y, b.y)), max(a.z, b.z));
    var result: vec4<f32> = vec4<f32>(0.0);
    if ((far >= max(near, 0.0))) {
        if ((settings.slice.x > 0.5)) {
            var distance: f32 = ((((settings.slice.y * 2.0) - 1.0) - eye.z) * inverse.z);
            if (((distance >= max(near, 0.0)) && (distance <= far))) {
                result = color_at((eye + (distance * ray)));
                result.a = 1.0;
            }
        } else {
            var distance: f32 = max(near, 0.0);
            var steps: u32 = u32(0);
            while (true) {
                if ((((distance > far) || (result.a > 0.995)) || (steps >= u32(1024)))) {
                    break;
                }
                let color: vec4<f32> = color_at((eye + (distance * ray)));
                let alpha: f32 = (1.0 - exp(((((-color.a) * settings.viewport.z) * settings.camera.w) * 40.0)));
                result = vec4<f32>((result.rgb + (((1.0 - result.a) * alpha) * color.rgb)), (result.a + ((1.0 - result.a) * alpha)));
                distance = (distance + settings.camera.w);
                steps = (steps + u32(1));
            }
        }
    }
    return vec4<f32>((result.rgb + ((1.0 - result.a) * vec3<f32>(0.025, 0.03, 0.04))), 1.0);
}
